# Analyze the AMG benchmark data

In [1]:
! pip install polars --quiet

In [2]:
from pathlib import Path
ROOT_DIR = Path("/storage2/scratch/kosmopoulos/projects/checkAMG/benchmarks")
MAIN_DIR = ROOT_DIR.joinpath("metabolism_benchmark")
AMG_TABLES_DIR = MAIN_DIR.joinpath("amg_tables")
OUTPUT_TABLES_DIR = Path("./tables/amg_benchmark")
OUTPUT_TABLES_DIR.mkdir(exist_ok=True, parents=True)

In [3]:
import os
os.environ["POLARS_MAX_THREADS"] = str(50)
import polars as pl
pl.Config.set_fmt_str_lengths(100)
pl.Config.set_tbl_rows(10)

polars.config.Config

In [4]:
AMG_PREDICTIONS_PARQUET = AMG_TABLES_DIR.joinpath("amg_predictions_combined.parquet")

In [5]:
amg_predictions = pl.read_parquet(AMG_PREDICTIONS_PARQUET)
amg_predictions

shape: (1_977_870, 31)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ gene       ┆ scaffold  ┆ source    ┆ sample    ┆ … ┆ DRAMV_F ┆ VIBRANT_h ┆ VIBRANT_m ┆ VIBRANT_l │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---     ┆ igh       ┆ edium     ┆ ow        │
│ str        ┆ str       ┆ str       ┆ str       ┆   ┆ bool    ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆         ┆ bool      ┆ bool      ┆ bool      │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ Ga0485157_ ┆ Ga0485157 ┆ Mixed met ┆ freshwate ┆ … ┆ false   ┆ false     ┆ false     ┆ false     │
│ 0000001_10 ┆ _0000001  ┆ agenomes  ┆ r_Ga04851 ┆   ┆         ┆           ┆           ┆           │
│            ┆           ┆           ┆ 57_contig ┆   ┆         ┆           ┆           ┆           │
│            ┆           ┆           ┆ s         ┆   ┆         ┆           ┆           ┆           │
│ Ga0485157_ ┆ Ga0485157 ┆ Mixed met ┆ freshwate ┆ … ┆ false   ┆ false     ┆ false     ┆ false     │
│ 0000001_10 ┆ _0000001  ┆ agenomes  ┆ r_Ga04851 ┆   ┆         ┆           ┆           ┆           │
│ 0          ┆           ┆           ┆ 57_contig ┆   ┆         ┆           ┆           ┆           │
│            ┆           ┆           ┆ s         ┆   ┆         ┆           ┆           ┆           │
│ Ga0485157_ ┆ Ga0485157 ┆ Mixed met ┆ freshwate ┆ … ┆ false   ┆ false     ┆ false     ┆ false     │
│ 0000001_10 ┆ _0000001  ┆ agenomes  ┆ r_Ga04851 ┆   ┆         ┆           ┆           ┆           │
│ 1          ┆           ┆           ┆ 57_contig ┆   ┆         ┆           ┆           ┆           │
│            ┆           ┆           ┆ s         ┆   ┆         ┆           ┆           ┆           │
│ Ga0485157_ ┆ Ga0485157 ┆ Mixed met ┆ freshwate ┆ … ┆ false   ┆ false     ┆ false     ┆ false     │
│ 0000001_10 ┆ _0000001  ┆ agenomes  ┆ r_Ga04851 ┆   ┆         ┆           ┆           ┆           │
│ 2          ┆           ┆           ┆ 57_contig ┆   ┆         ┆           ┆           ┆           │
│            ┆           ┆           ┆ s         ┆   ┆         ┆           ┆           ┆           │
│ Ga0485157_ ┆ Ga0485157 ┆ Mixed met ┆ freshwate ┆ … ┆ false   ┆ false     ┆ false     ┆ false     │
│ 0000001_10 ┆ _0000001  ┆ agenomes  ┆ r_Ga04851 ┆   ┆         ┆           ┆           ┆           │
│ 3          ┆           ┆           ┆ 57_contig ┆   ┆         ┆           ┆           ┆           │
│            ┆           ┆           ┆ s         ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ scaffold_9 ┆ scaffold_ ┆ Viromes   ┆ soil_T42_ ┆ … ┆ false   ┆ false     ┆ false     ┆ false     │
│ _c1_5      ┆ 9_c1      ┆           ┆ 15_3_45   ┆   ┆         ┆           ┆           ┆           │
│ scaffold_9 ┆ scaffold_ ┆ Viromes   ┆ soil_T42_ ┆ … ┆ false   ┆ false     ┆ false     ┆ false     │
│ _c1_6      ┆ 9_c1      ┆           ┆ 15_3_45   ┆   ┆         ┆           ┆           ┆           │
│ scaffold_9 ┆ scaffold_ ┆ Viromes   ┆ soil_T42_ ┆ … ┆ false   ┆ false     ┆ false     ┆ false     │
│ _c1_7      ┆ 9_c1      ┆           ┆ 15_3_45   ┆   ┆         ┆           ┆           ┆           │
│ scaffold_9 ┆ scaffold_ ┆ Viromes   ┆ soil_T42_ ┆ … ┆ false   ┆ false     ┆ false     ┆ false     │
│ _c1_8      ┆ 9_c1      ┆           ┆ 15_3_45   ┆   ┆         ┆           ┆           ┆           │
│ scaffold_9 ┆ scaffold_ ┆ Viromes   ┆ soil_T42_ ┆ … ┆ false   ┆ false     ┆ false     ┆ false     │
│ _c1_9      ┆ 9_c1      ┆           ┆ 15_3_45   ┆   ┆         ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [6]:
DEFAULT_TIERS = {
    "CheckAMG_high": "CheckAMG (high)",
    "DRAMV_default": "DRAM-V (default)",
    "VIBRANT_high":  "VIBRANT (high)",
}

ALL_TIERS = {
    "CheckAMG_high": "CheckAMG (high)",
    "CheckAMG_medium": "CheckAMG (medium)",
    "CheckAMG_low": "CheckAMG (low)",
    "DRAMV_default": "DRAM-V (default)",
    "DRAMV_allow_T": "DRAM-V (allow T)",
    "DRAMV_aux_4": "DRAM-V (aux <= 4)",
    "DRAMV_aux_4_allow_T": "DRAM-V (aux <= 4, allow T)",
    "VIBRANT_high":  "VIBRANT (high)",
    "VIBRANT_medium":  "VIBRANT (medium)",
    "VIBRANT_low":  "VIBRANT (low)",
}

SOURCE_LABELS = {
    "complete_virus_genomes": "Viral genomes",
    "metagenomes":            "Mixed metagenomes",
    "viromes":                "Viromes",
}

ECO_LABELS = {
    "gut":        "Human gut",
    "marine":     "Aquatic",
    "freshwater": "Aquatic",
    "soil":       "Soil",
}

## Get AMG counts

### Per tool x tier

Every tool has multiple tiers. DRAM-V's are stringency flags (default, allow T flag, aux score 4, aux 4 + T), not rank-ordered confidences like CheckAMG and VIBRANT. CheckAMG and VIBRANT tier as high / medium / low. Default / high are the advertised outputs.

In [7]:
count_rows = []
for tier in ALL_TIERS.keys():
    n = int(amg_predictions.select(pl.col(tier).sum()).item())
    n_viral = int(amg_predictions.filter(pl.col(tier) & pl.col("genomad_viral")).height)
    tool = tier.split("_")[0] if not tier.startswith("DRAMV") else "DRAM-V"
    count_rows.append({
        "tool": "CheckAMG" if tier.startswith("CheckAMG") else ("VIBRANT" if tier.startswith("VIBRANT") else "DRAM-V"),
        "tier": tier,
        "n_amg": n,
        "n_amg_genomad_viral": n_viral,
        "pct_genomad_viral": round(100.0 * n_viral / n, 3) if n else 0.0,
    })
counts_tier = pl.DataFrame(count_rows).sort(["tool", "tier"])

In [8]:
counts_tier

shape: (10, 5)
┌──────────┬─────────────────────┬─────────┬─────────────────────┬───────────────────┐
│ tool     ┆ tier                ┆ n_amg   ┆ n_amg_genomad_viral ┆ pct_genomad_viral │
│ ---      ┆ ---                 ┆ ---     ┆ ---                 ┆ ---               │
│ str      ┆ str                 ┆ i64     ┆ i64                 ┆ f64               │
╞══════════╪═════════════════════╪═════════╪═════════════════════╪═══════════════════╡
│ CheckAMG ┆ CheckAMG_high       ┆ 3218    ┆ 3151                ┆ 97.918            │
│ CheckAMG ┆ CheckAMG_low        ┆ 169511  ┆ 8847                ┆ 5.219             │
│ CheckAMG ┆ CheckAMG_medium     ┆ 6706    ┆ 5825                ┆ 86.863            │
│ DRAM-V   ┆ DRAMV_allow_T       ┆ 10736   ┆ 9846                ┆ 91.71             │
│ DRAM-V   ┆ DRAMV_aux_4         ┆ 116657  ┆ 61378               ┆ 52.614            │
│ DRAM-V   ┆ DRAMV_aux_4_allow_T ┆ 1900029 ┆ 1199111             ┆ 63.11             │
│ DRAM-V   ┆ DRAMV_default       ┆ 664     ┆ 621                 ┆ 93.524            │
│ VIBRANT  ┆ VIBRANT_high        ┆ 1270    ┆ 1263                ┆ 99.449            │
│ VIBRANT  ┆ VIBRANT_low         ┆ 12641   ┆ 12497               ┆ 98.861            │
│ VIBRANT  ┆ VIBRANT_medium      ┆ 3720    ┆ 3708                ┆ 99.677            │
└──────────┴─────────────────────┴─────────┴─────────────────────┴───────────────────┘

In [9]:
counts_tier.write_csv(OUTPUT_TABLES_DIR.joinpath("AMG_counts_by_tier.tsv"), separator="\t")

### Per source x ecosystem

In [10]:
srcs_eco = []
for tier in ALL_TIERS.keys():
    g = (
        amg_predictions
        .group_by(["source", "ecosystem"])
        .agg([
            pl.col(tier).sum().alias("n_amg"),
            (pl.col(tier) & pl.col("genomad_viral")).sum().alias("n_amg_genomad_viral"),
        ])
        .with_columns([
            pl.lit(tier).alias("tier"),
            pl.when(pl.col("n_amg") > 0)
            .then(100.0 * pl.col("n_amg_genomad_viral") / pl.col("n_amg"))
            .otherwise(0.0)
            .round(3)
            .alias("pct_genomad_viral"),
        ])
    )
    srcs_eco.append(g)

counts_source_eco = pl.concat(srcs_eco, how="vertical_relaxed")

counts_source_eco = counts_source_eco.sort(
    ["n_amg", "n_amg_genomad_viral", "source", "ecosystem", "tier"],
    descending=[True, True, False, False, False]
)

In [11]:
counts_source_eco

shape: (90, 6)
┌───────────────┬───────────┬────────┬────────────────────┬────────────────────┬───────────────────┐
│ source        ┆ ecosystem ┆ n_amg  ┆ n_amg_genomad_vira ┆ tier               ┆ pct_genomad_viral │
│ ---           ┆ ---       ┆ ---    ┆ l                  ┆ ---                ┆ ---               │
│ str           ┆ str       ┆ u64    ┆ ---                ┆ str                ┆ f64               │
│               ┆           ┆        ┆ u64                ┆                    ┆                   │
╞═══════════════╪═══════════╪════════╪════════════════════╪════════════════════╪═══════════════════╡
│ Mixed         ┆ Soil      ┆ 606564 ┆ 596406             ┆ DRAMV_aux_4_allow_ ┆ 98.325            │
│ metagenomes   ┆           ┆        ┆                    ┆ T                  ┆                   │
│ Viromes       ┆ Aquatic   ┆ 491455 ┆ 323098             ┆ DRAMV_aux_4_allow_ ┆ 65.743            │
│               ┆           ┆        ┆                    ┆ T                  ┆                   │
│ Viromes       ┆ Human gut ┆ 293055 ┆ 29180              ┆ DRAMV_aux_4_allow_ ┆ 9.957             │
│               ┆           ┆        ┆                    ┆ T                  ┆                   │
│ Mixed         ┆ Aquatic   ┆ 254973 ┆ 75108              ┆ DRAMV_aux_4_allow_ ┆ 29.457            │
│ metagenomes   ┆           ┆        ┆                    ┆ T                  ┆                   │
│ Viral genomes ┆ Human gut ┆ 63275  ┆ 63272              ┆ DRAMV_aux_4_allow_ ┆ 99.995            │
│               ┆           ┆        ┆                    ┆ T                  ┆                   │
│ …             ┆ …         ┆ …      ┆ …                  ┆ …                  ┆ …                 │
│ Mixed         ┆ Human gut ┆ 2      ┆ 2                  ┆ VIBRANT_high       ┆ 100.0             │
│ metagenomes   ┆           ┆        ┆                    ┆                    ┆                   │
│ Viromes       ┆ Soil      ┆ 2      ┆ 0                  ┆ DRAMV_default      ┆ 0.0               │
│ Viral genomes ┆ Aquatic   ┆ 1      ┆ 1                  ┆ DRAMV_default      ┆ 100.0             │
│ Viral genomes ┆ Human gut ┆ 1      ┆ 1                  ┆ DRAMV_default      ┆ 100.0             │
│ Viral genomes ┆ Soil      ┆ 0      ┆ 0                  ┆ DRAMV_default      ┆ 0.0               │
└───────────────┴───────────┴────────┴────────────────────┴────────────────────┴───────────────────┘

## Calculate overlapping/unique AMG calls

### Default/high-confidence tiers

Keep genes with at least one default/high call.

In [12]:
default_cols = list(DEFAULT_TIERS.keys())
any_default = pl.any_horizontal([pl.col(c) for c in default_cols])

members = (
    amg_predictions.filter(any_default)
        .select(
            "gene", "scaffold", "source", "sample", "ecosystem",
            "genomad_viral", "in_strict_viral_region",
            "viral_gene_left_dist", "viral_gene_right_dist",
            "MGE_gene_left_dist", "MGE_gene_right_dist",
            "MGE_gene_left_V_score", "MGE_gene_right_V_score",
            *ALL_TIERS.keys(),
            "DRAMV_auxiliary_score",
            "DRAMV_M", "DRAMV_T", "DRAMV_V", "DRAMV_A", "DRAMV_P", "DRAMV_B", "DRAMV_F",
        )
)

In [13]:
members

shape: (4_931, 31)
┌─────────────┬─────────────┬─────────────┬────────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ gene        ┆ scaffold    ┆ source      ┆ sample     ┆ … ┆ DRAMV_A ┆ DRAMV_P ┆ DRAMV_B ┆ DRAMV_F │
│ ---         ┆ ---         ┆ ---         ┆ ---        ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ str         ┆ str         ┆ str         ┆ str        ┆   ┆ bool    ┆ bool    ┆ bool    ┆ bool    │
╞═════════════╪═════════════╪═════════════╪════════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ Ga0485157_0 ┆ Ga0485157_0 ┆ Mixed       ┆ freshwater ┆ … ┆ false   ┆ false   ┆ false   ┆ false   │
│ 000020_8    ┆ 000020      ┆ metagenomes ┆ _Ga0485157 ┆   ┆         ┆         ┆         ┆         │
│             ┆             ┆             ┆ _contigs   ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_0 ┆ Ga0485157_0 ┆ Mixed       ┆ freshwater ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 000095_62   ┆ 000095      ┆ metagenomes ┆ _Ga0485157 ┆   ┆         ┆         ┆         ┆         │
│             ┆             ┆             ┆ _contigs   ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_0 ┆ Ga0485157_0 ┆ Mixed       ┆ freshwater ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 000095_70   ┆ 000095      ┆ metagenomes ┆ _Ga0485157 ┆   ┆         ┆         ┆         ┆         │
│             ┆             ┆             ┆ _contigs   ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_0 ┆ Ga0485157_0 ┆ Mixed       ┆ freshwater ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 000095_73   ┆ 000095      ┆ metagenomes ┆ _Ga0485157 ┆   ┆         ┆         ┆         ┆         │
│             ┆             ┆             ┆ _contigs   ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_0 ┆ Ga0485157_0 ┆ Mixed       ┆ freshwater ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 000261_37   ┆ 000261      ┆ metagenomes ┆ _Ga0485157 ┆   ┆         ┆         ┆         ┆         │
│             ┆             ┆             ┆ _contigs   ┆   ┆         ┆         ┆         ┆         │
│ …           ┆ …           ┆ …           ┆ …          ┆ … ┆ …       ┆ …       ┆ …       ┆ …       │
│ scaffold_40 ┆ scaffold_40 ┆ Viromes     ┆ soil_T42_1 ┆ … ┆ false   ┆ false   ┆ true    ┆ true    │
│ 0_c1_20     ┆ 0_c1        ┆             ┆ 5_2_44     ┆   ┆         ┆         ┆         ┆         │
│ scaffold_48 ┆ scaffold_48 ┆ Viromes     ┆ soil_T42_1 ┆ … ┆ false   ┆ false   ┆ true    ┆ true    │
│ 30_c1_3     ┆ 30_c1       ┆             ┆ 5_2_44     ┆   ┆         ┆         ┆         ┆         │
│ scaffold_80 ┆ scaffold_80 ┆ Viromes     ┆ soil_T42_1 ┆ … ┆ false   ┆ false   ┆ true    ┆ true    │
│ 6_c1_10     ┆ 6_c1        ┆             ┆ 5_2_44     ┆   ┆         ┆         ┆         ┆         │
│ scaffold_12 ┆ scaffold_12 ┆ Viromes     ┆ soil_T42_1 ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 1_c1_4      ┆ 1_c1        ┆             ┆ 5_3_45     ┆   ┆         ┆         ┆         ┆         │
│ scaffold_47 ┆ scaffold_47 ┆ Viromes     ┆ soil_T42_1 ┆ … ┆ false   ┆ false   ┆ true    ┆ true    │
│ 2_c1_3      ┆ 2_c1        ┆             ┆ 5_3_45     ┆   ┆         ┆         ┆         ┆         │
└─────────────┴─────────────┴─────────────┴────────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [14]:
members.write_csv(OUTPUT_TABLES_DIR.joinpath("AMG_default_high_members.tsv"), separator="\t")

In [15]:
members_viral = members.filter(pl.col("genomad_viral"))

In [16]:
members_viral

shape: (4_814, 31)
┌─────────────┬─────────────┬─────────────┬────────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ gene        ┆ scaffold    ┆ source      ┆ sample     ┆ … ┆ DRAMV_A ┆ DRAMV_P ┆ DRAMV_B ┆ DRAMV_F │
│ ---         ┆ ---         ┆ ---         ┆ ---        ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ str         ┆ str         ┆ str         ┆ str        ┆   ┆ bool    ┆ bool    ┆ bool    ┆ bool    │
╞═════════════╪═════════════╪═════════════╪════════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ Ga0485157_0 ┆ Ga0485157_0 ┆ Mixed       ┆ freshwater ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 000095_62   ┆ 000095      ┆ metagenomes ┆ _Ga0485157 ┆   ┆         ┆         ┆         ┆         │
│             ┆             ┆             ┆ _contigs   ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_0 ┆ Ga0485157_0 ┆ Mixed       ┆ freshwater ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 000095_70   ┆ 000095      ┆ metagenomes ┆ _Ga0485157 ┆   ┆         ┆         ┆         ┆         │
│             ┆             ┆             ┆ _contigs   ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_0 ┆ Ga0485157_0 ┆ Mixed       ┆ freshwater ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 000095_73   ┆ 000095      ┆ metagenomes ┆ _Ga0485157 ┆   ┆         ┆         ┆         ┆         │
│             ┆             ┆             ┆ _contigs   ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_0 ┆ Ga0485157_0 ┆ Mixed       ┆ freshwater ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 000331_45   ┆ 000331      ┆ metagenomes ┆ _Ga0485157 ┆   ┆         ┆         ┆         ┆         │
│             ┆             ┆             ┆ _contigs   ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_0 ┆ Ga0485157_0 ┆ Mixed       ┆ freshwater ┆ … ┆ false   ┆ false   ┆ true    ┆ true    │
│ 000578_2    ┆ 000578      ┆ metagenomes ┆ _Ga0485157 ┆   ┆         ┆         ┆         ┆         │
│             ┆             ┆             ┆ _contigs   ┆   ┆         ┆         ┆         ┆         │
│ …           ┆ …           ┆ …           ┆ …          ┆ … ┆ …       ┆ …       ┆ …       ┆ …       │
│ scaffold_37 ┆ scaffold_37 ┆ Viromes     ┆ soil_T42_1 ┆ … ┆ false   ┆ false   ┆ false   ┆ false   │
│ _c1_5       ┆ _c1         ┆             ┆ 5_1_43     ┆   ┆         ┆         ┆         ┆         │
│ scaffold_61 ┆ scaffold_61 ┆ Viromes     ┆ soil_T42_1 ┆ … ┆ false   ┆ false   ┆ true    ┆ true    │
│ 99_c1_12    ┆ 99_c1       ┆             ┆ 5_1_43     ┆   ┆         ┆         ┆         ┆         │
│ scaffold_8_ ┆ scaffold_8_ ┆ Viromes     ┆ soil_T42_1 ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ c1_7        ┆ c1          ┆             ┆ 5_1_43     ┆   ┆         ┆         ┆         ┆         │
│ scaffold_8_ ┆ scaffold_8_ ┆ Viromes     ┆ soil_T42_1 ┆ … ┆ false   ┆ false   ┆ true    ┆ true    │
│ c1_90       ┆ c1          ┆             ┆ 5_1_43     ┆   ┆         ┆         ┆         ┆         │
│ scaffold_40 ┆ scaffold_40 ┆ Viromes     ┆ soil_T42_1 ┆ … ┆ false   ┆ false   ┆ true    ┆ true    │
│ 0_c1_20     ┆ 0_c1        ┆             ┆ 5_2_44     ┆   ┆         ┆         ┆         ┆         │
└─────────────┴─────────────┴─────────────┴────────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [17]:

from itertools import combinations

def set_counts(frame, tiers, name):

    rows = []
    cols = list(tiers.keys())

    for r in range(1, len(cols) + 1):
        for combo in combinations(cols, r):
            expr = pl.lit(True)

            for col in combo:
                expr = expr & pl.col(col)

            for col in cols:
                if col not in combo:
                    expr = expr & ~pl.col(col)

            rows.append({
                "set": " & ".join(tiers[c] for c in combo),
                "n_genes": int(frame.filter(expr).height),
                "scope": name,
            })

    union_expr = pl.lit(False)
    for col in cols:
        union_expr = union_expr | pl.col(col)

    rows.append({
        "set": "Total (any selected tier)",
        "n_genes": int(frame.filter(union_expr).height),
        "scope": name,
    })

    return pl.DataFrame(rows)

In [18]:
overall = set_counts(members, DEFAULT_TIERS, "all")

In [19]:
overall

shape: (8, 3)
┌─────────────────────────────────────────────────────┬─────────┬───────┐
│ set                                                 ┆ n_genes ┆ scope │
│ ---                                                 ┆ ---     ┆ ---   │
│ str                                                 ┆ i64     ┆ str   │
╞═════════════════════════════════════════════════════╪═════════╪═══════╡
│ CheckAMG (high)                                     ┆ 2997    ┆ all   │
│ DRAM-V (default)                                    ┆ 664     ┆ all   │
│ VIBRANT (high)                                      ┆ 1049    ┆ all   │
│ CheckAMG (high) & DRAM-V (default)                  ┆ 0       ┆ all   │
│ CheckAMG (high) & VIBRANT (high)                    ┆ 221     ┆ all   │
│ DRAM-V (default) & VIBRANT (high)                   ┆ 0       ┆ all   │
│ CheckAMG (high) & DRAM-V (default) & VIBRANT (high) ┆ 0       ┆ all   │
│ Total (any selected tier)                           ┆ 4931    ┆ all   │
└─────────────────────────────────────────────────────┴─────────┴───────┘

In [20]:
viral = set_counts(members_viral, DEFAULT_TIERS, "genomad_viral")

In [21]:
viral

shape: (8, 3)
┌─────────────────────────────────────────────────────┬─────────┬───────────────┐
│ set                                                 ┆ n_genes ┆ scope         │
│ ---                                                 ┆ ---     ┆ ---           │
│ str                                                 ┆ i64     ┆ str           │
╞═════════════════════════════════════════════════════╪═════════╪═══════════════╡
│ CheckAMG (high)                                     ┆ 2930    ┆ genomad_viral │
│ DRAM-V (default)                                    ┆ 621     ┆ genomad_viral │
│ VIBRANT (high)                                      ┆ 1042    ┆ genomad_viral │
│ CheckAMG (high) & DRAM-V (default)                  ┆ 0       ┆ genomad_viral │
│ CheckAMG (high) & VIBRANT (high)                    ┆ 221     ┆ genomad_viral │
│ DRAM-V (default) & VIBRANT (high)                   ┆ 0       ┆ genomad_viral │
│ CheckAMG (high) & DRAM-V (default) & VIBRANT (high) ┆ 0       ┆ genomad_viral │
│ Total (any selected tier)                           ┆ 4814    ┆ genomad_viral │
└─────────────────────────────────────────────────────┴─────────┴───────────────┘

### All tiers

In [22]:
members_any = (
    amg_predictions
    .select(
        "gene", "scaffold", "source", "sample", "ecosystem",
        "genomad_viral", "in_strict_viral_region",
        "viral_gene_left_dist", "viral_gene_right_dist",
        "MGE_gene_left_dist", "MGE_gene_right_dist",
        "MGE_gene_left_V_score", "MGE_gene_right_V_score",
        *ALL_TIERS.keys(),
        "DRAMV_auxiliary_score",
        "DRAMV_M", "DRAMV_T", "DRAMV_V", "DRAMV_A", "DRAMV_P", "DRAMV_B", "DRAMV_F",
    )
)

In [23]:
members_any_viral = members_any.filter(pl.col("genomad_viral"))

In [24]:
overall_any = set_counts(members_any, ALL_TIERS, "all").sort(["n_genes"], descending=True)

In [25]:
overall_any

shape: (1_024, 3)
┌─────────────────────────────────────────────────────────────────────────────┬─────────┬───────┐
│ set                                                                         ┆ n_genes ┆ scope │
│ ---                                                                         ┆ ---     ┆ ---   │
│ str                                                                         ┆ i64     ┆ str   │
╞═════════════════════════════════════════════════════════════════════════════╪═════════╪═══════╡
│ Total (any selected tier)                                                   ┆ 1977870 ┆ all   │
│ DRAM-V (aux <= 4, allow T)                                                  ┆ 1679639 ┆ all   │
│ DRAM-V (aux <= 4) & DRAM-V (aux <= 4, allow T)                              ┆ 108149  ┆ all   │
│ CheckAMG (low) & DRAM-V (aux <= 4, allow T)                                 ┆ 79664   ┆ all   │
│ CheckAMG (low)                                                              ┆ 75423   ┆ all   │
│ …                                                                           ┆ …       ┆ …     │
│ CheckAMG (high) & CheckAMG (medium) & CheckAMG (low) & DRAM-V (allow T) &   ┆ 0       ┆ all   │
│ DRAM-V (aux <= 4) & DRAM-V…                                                 ┆         ┆       │
│ CheckAMG (high) & CheckAMG (medium) & DRAM-V (default) & DRAM-V (allow T) & ┆ 0       ┆ all   │
│ DRAM-V (aux <= 4) & DRAM…                                                   ┆         ┆       │
│ CheckAMG (high) & CheckAMG (low) & DRAM-V (default) & DRAM-V (allow T) &    ┆ 0       ┆ all   │
│ DRAM-V (aux <= 4) & DRAM-V …                                                ┆         ┆       │
│ CheckAMG (medium) & CheckAMG (low) & DRAM-V (default) & DRAM-V (allow T) &  ┆ 0       ┆ all   │
│ DRAM-V (aux <= 4) & DRAM-…                                                  ┆         ┆       │
│ CheckAMG (high) & CheckAMG (medium) & CheckAMG (low) & DRAM-V (default) &   ┆ 0       ┆ all   │
│ DRAM-V (allow T) & DRAM-V …                                                 ┆         ┆       │
└─────────────────────────────────────────────────────────────────────────────┴─────────┴───────┘

In [26]:
viral_any = set_counts(members_viral, ALL_TIERS, "genomad_viral").sort(["n_genes"], descending=True)

In [27]:
viral_any

shape: (1_024, 3)
┌────────────────────────────────────────────────────────────────────────┬─────────┬───────────────┐
│ set                                                                    ┆ n_genes ┆ scope         │
│ ---                                                                    ┆ ---     ┆ ---           │
│ str                                                                    ┆ i64     ┆ str           │
╞════════════════════════════════════════════════════════════════════════╪═════════╪═══════════════╡
│ Total (any selected tier)                                              ┆ 4814    ┆ genomad_viral │
│ CheckAMG (high) & CheckAMG (medium) & CheckAMG (low) & DRAM-V (aux <=  ┆ 1663    ┆ genomad_viral │
│ 4, allow T)                                                            ┆         ┆               │
│ DRAM-V (aux <= 4, allow T) & VIBRANT (high) & VIBRANT (medium) &       ┆ 884     ┆ genomad_viral │
│ VIBRANT (low)                                                          ┆         ┆               │
│ CheckAMG (high) & CheckAMG (medium) & CheckAMG (low) & DRAM-V (aux <=  ┆ 644     ┆ genomad_viral │
│ 4, allow T) & VIBRANT (low)                                            ┆         ┆               │
│ DRAM-V (default) & DRAM-V (allow T) & DRAM-V (aux <= 4) & DRAM-V (aux  ┆ 615     ┆ genomad_viral │
│ <= 4, allow T)                                                         ┆         ┆               │
│ …                                                                      ┆ …       ┆ …             │
│ CheckAMG (high) & CheckAMG (medium) & CheckAMG (low) & DRAM-V (allow   ┆ 0       ┆ genomad_viral │
│ T) & DRAM-V (aux <= 4) & DRAM-V…                                       ┆         ┆               │
│ CheckAMG (high) & CheckAMG (medium) & DRAM-V (default) & DRAM-V (allow ┆ 0       ┆ genomad_viral │
│ T) & DRAM-V (aux <= 4) & DRAM…                                         ┆         ┆               │
│ CheckAMG (high) & CheckAMG (low) & DRAM-V (default) & DRAM-V (allow T) ┆ 0       ┆ genomad_viral │
│ & DRAM-V (aux <= 4) & DRAM-V …                                         ┆         ┆               │
│ CheckAMG (medium) & CheckAMG (low) & DRAM-V (default) & DRAM-V (allow  ┆ 0       ┆ genomad_viral │
│ T) & DRAM-V (aux <= 4) & DRAM-…                                        ┆         ┆               │
│ CheckAMG (high) & CheckAMG (medium) & CheckAMG (low) & DRAM-V          ┆ 0       ┆ genomad_viral │
│ (default) & DRAM-V (allow T) & DRAM-V …                                ┆         ┆               │
└────────────────────────────────────────────────────────────────────────┴─────────┴───────────────┘

### Pairwise jaccard and overlap percentages

In [28]:
def pairwise(frame):
    rows = []
    sets = {
        "CheckAMG (high)": pl.col("CheckAMG_high"),
        "CheckAMG (medium)": pl.col("CheckAMG_medium"),
        "CheckAMG (low)": pl.col("CheckAMG_low"),
        "DRAM-V (default)": pl.col("DRAMV_default"),
        "DRAM-V (allow T)": pl.col("DRAMV_allow_T"),
        "DRAM-V (aux <= 4)": pl.col("DRAMV_aux_4"),
        "DRAM-V (aux <= 4, allow T)": pl.col("DRAMV_aux_4_allow_T"),
        "VIBRANT (high)":  pl.col("VIBRANT_high"),
        "VIBRANT (medium)":  pl.col("VIBRANT_medium"),
        "VIBRANT (low)":  pl.col("VIBRANT_low"),
    }
    for a_name, a_expr in sets.items():
        for b_name, b_expr in sets.items():
            if a_name >= b_name:
                continue
            na = frame.filter(a_expr).height
            nb = frame.filter(b_expr).height
            nab = frame.filter(a_expr & b_expr).height
            union = frame.filter(a_expr | b_expr).height
            rows.append({
                "tier_a": a_name, "tier_b": b_name,
                "n_a": na, "n_b": nb, "n_intersection": nab, "n_union": union,
                "jaccard": round(nab / union, 4) if union else 0.0,
                "pct_a_in_b": round(100.0 * nab / na, 2) if na else 0.0,
                "pct_b_in_a": round(100.0 * nab / nb, 2) if nb else 0.0,
            })
    return pl.DataFrame(rows)

In [29]:
pw = pairwise(members_any)
pw

shape: (45, 9)
┌──────────────┬──────────────┬─────────┬────────┬───┬─────────┬─────────┬────────────┬────────────┐
│ tier_a       ┆ tier_b       ┆ n_a     ┆ n_b    ┆ … ┆ n_union ┆ jaccard ┆ pct_a_in_b ┆ pct_b_in_a │
│ ---          ┆ ---          ┆ ---     ┆ ---    ┆   ┆ ---     ┆ ---     ┆ ---        ┆ ---        │
│ str          ┆ str          ┆ i64     ┆ i64    ┆   ┆ i64     ┆ f64     ┆ f64        ┆ f64        │
╞══════════════╪══════════════╪═════════╪════════╪═══╪═════════╪═════════╪════════════╪════════════╡
│ CheckAMG     ┆ CheckAMG     ┆ 3218    ┆ 6706   ┆ … ┆ 6706    ┆ 0.4799  ┆ 100.0      ┆ 47.99      │
│ (high)       ┆ (medium)     ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ CheckAMG     ┆ CheckAMG     ┆ 3218    ┆ 169511 ┆ … ┆ 169511  ┆ 0.019   ┆ 100.0      ┆ 1.9        │
│ (high)       ┆ (low)        ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ CheckAMG     ┆ DRAM-V       ┆ 3218    ┆ 664    ┆ … ┆ 3882    ┆ 0.0     ┆ 0.0        ┆ 0.0        │
│ (high)       ┆ (default)    ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ CheckAMG     ┆ DRAM-V       ┆ 3218    ┆ 10736  ┆ … ┆ 13933   ┆ 0.0015  ┆ 0.65       ┆ 0.2        │
│ (high)       ┆ (allow T)    ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ CheckAMG     ┆ DRAM-V (aux  ┆ 3218    ┆ 116657 ┆ … ┆ 119757  ┆ 0.001   ┆ 3.67       ┆ 0.1        │
│ (high)       ┆ <= 4)        ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ …            ┆ …            ┆ …       ┆ …      ┆ … ┆ …       ┆ …       ┆ …          ┆ …          │
│ DRAM-V (aux  ┆ VIBRANT      ┆ 1900029 ┆ 3720   ┆ … ┆ 1900375 ┆ 0.0018  ┆ 0.18       ┆ 90.7       │
│ <= 4, allow  ┆ (medium)     ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ T)           ┆              ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ DRAM-V (aux  ┆ VIBRANT      ┆ 1900029 ┆ 12641  ┆ … ┆ 1901828 ┆ 0.0057  ┆ 0.57       ┆ 85.77      │
│ <= 4, allow  ┆ (low)        ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ T)           ┆              ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ VIBRANT      ┆ VIBRANT      ┆ 1270    ┆ 3720   ┆ … ┆ 3720    ┆ 0.3414  ┆ 100.0      ┆ 34.14      │
│ (high)       ┆ (medium)     ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ VIBRANT      ┆ VIBRANT      ┆ 1270    ┆ 12641  ┆ … ┆ 12641   ┆ 0.1005  ┆ 100.0      ┆ 10.05      │
│ (high)       ┆ (low)        ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
│ VIBRANT      ┆ VIBRANT      ┆ 12641   ┆ 3720   ┆ … ┆ 12641   ┆ 0.2943  ┆ 29.43      ┆ 100.0      │
│ (low)        ┆ (medium)     ┆         ┆        ┆   ┆         ┆         ┆            ┆            │
└──────────────┴──────────────┴─────────┴────────┴───┴─────────┴─────────┴────────────┴────────────┘

In [30]:
pw_v = pairwise(members_any_viral)
pw_v

shape: (45, 9)
┌───────────────┬──────────────┬─────────┬───────┬───┬─────────┬─────────┬────────────┬────────────┐
│ tier_a        ┆ tier_b       ┆ n_a     ┆ n_b   ┆ … ┆ n_union ┆ jaccard ┆ pct_a_in_b ┆ pct_b_in_a │
│ ---           ┆ ---          ┆ ---     ┆ ---   ┆   ┆ ---     ┆ ---     ┆ ---        ┆ ---        │
│ str           ┆ str          ┆ i64     ┆ i64   ┆   ┆ i64     ┆ f64     ┆ f64        ┆ f64        │
╞═══════════════╪══════════════╪═════════╪═══════╪═══╪═════════╪═════════╪════════════╪════════════╡
│ CheckAMG      ┆ CheckAMG     ┆ 3151    ┆ 5825  ┆ … ┆ 5825    ┆ 0.5409  ┆ 100.0      ┆ 54.09      │
│ (high)        ┆ (medium)     ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ CheckAMG      ┆ CheckAMG     ┆ 3151    ┆ 8847  ┆ … ┆ 8847    ┆ 0.3562  ┆ 100.0      ┆ 35.62      │
│ (high)        ┆ (low)        ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ CheckAMG      ┆ DRAM-V       ┆ 3151    ┆ 621   ┆ … ┆ 3772    ┆ 0.0     ┆ 0.0        ┆ 0.0        │
│ (high)        ┆ (default)    ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ CheckAMG      ┆ DRAM-V       ┆ 3151    ┆ 9846  ┆ … ┆ 12976   ┆ 0.0016  ┆ 0.67       ┆ 0.21       │
│ (high)        ┆ (allow T)    ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ CheckAMG      ┆ DRAM-V (aux  ┆ 3151    ┆ 61378 ┆ … ┆ 64418   ┆ 0.0017  ┆ 3.52       ┆ 0.18       │
│ (high)        ┆ <= 4)        ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ …             ┆ …            ┆ …       ┆ …     ┆ … ┆ …       ┆ …       ┆ …          ┆ …          │
│ DRAM-V (aux   ┆ VIBRANT      ┆ 1199111 ┆ 3708  ┆ … ┆ 1199457 ┆ 0.0028  ┆ 0.28       ┆ 90.67      │
│ <= 4, allow   ┆ (medium)     ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ T)            ┆              ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ DRAM-V (aux   ┆ VIBRANT      ┆ 1199111 ┆ 12497 ┆ … ┆ 1200868 ┆ 0.0089  ┆ 0.9        ┆ 85.94      │
│ <= 4, allow   ┆ (low)        ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ T)            ┆              ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ VIBRANT       ┆ VIBRANT      ┆ 1263    ┆ 3708  ┆ … ┆ 3708    ┆ 0.3406  ┆ 100.0      ┆ 34.06      │
│ (high)        ┆ (medium)     ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ VIBRANT       ┆ VIBRANT      ┆ 1263    ┆ 12497 ┆ … ┆ 12497   ┆ 0.1011  ┆ 100.0      ┆ 10.11      │
│ (high)        ┆ (low)        ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
│ VIBRANT (low) ┆ VIBRANT      ┆ 12497   ┆ 3708  ┆ … ┆ 12497   ┆ 0.2967  ┆ 29.67      ┆ 100.0      │
│               ┆ (medium)     ┆         ┆       ┆   ┆         ┆         ┆            ┆            │
└───────────────┴──────────────┴─────────┴───────┴───┴─────────┴─────────┴────────────┴────────────┘

In [31]:
pairwise_df = pl.concat(
    [pw.with_columns(pl.lit("all").alias("scope")), pw_v.with_columns(pl.lit("genomad_viral").alias("scope"))],
    how="vertical_relaxed"
)
pairwise_df

shape: (90, 10)
┌─────────────┬────────────┬─────────┬────────┬───┬─────────┬────────────┬────────────┬────────────┐
│ tier_a      ┆ tier_b     ┆ n_a     ┆ n_b    ┆ … ┆ jaccard ┆ pct_a_in_b ┆ pct_b_in_a ┆ scope      │
│ ---         ┆ ---        ┆ ---     ┆ ---    ┆   ┆ ---     ┆ ---        ┆ ---        ┆ ---        │
│ str         ┆ str        ┆ i64     ┆ i64    ┆   ┆ f64     ┆ f64        ┆ f64        ┆ str        │
╞═════════════╪════════════╪═════════╪════════╪═══╪═════════╪════════════╪════════════╪════════════╡
│ CheckAMG    ┆ CheckAMG   ┆ 3218    ┆ 6706   ┆ … ┆ 0.4799  ┆ 100.0      ┆ 47.99      ┆ all        │
│ (high)      ┆ (medium)   ┆         ┆        ┆   ┆         ┆            ┆            ┆            │
│ CheckAMG    ┆ CheckAMG   ┆ 3218    ┆ 169511 ┆ … ┆ 0.019   ┆ 100.0      ┆ 1.9        ┆ all        │
│ (high)      ┆ (low)      ┆         ┆        ┆   ┆         ┆            ┆            ┆            │
│ CheckAMG    ┆ DRAM-V     ┆ 3218    ┆ 664    ┆ … ┆ 0.0     ┆ 0.0        ┆ 0.0        ┆ all        │
│ (high)      ┆ (default)  ┆         ┆        ┆   ┆         ┆            ┆            ┆            │
│ CheckAMG    ┆ DRAM-V     ┆ 3218    ┆ 10736  ┆ … ┆ 0.0015  ┆ 0.65       ┆ 0.2        ┆ all        │
│ (high)      ┆ (allow T)  ┆         ┆        ┆   ┆         ┆            ┆            ┆            │
│ CheckAMG    ┆ DRAM-V     ┆ 3218    ┆ 116657 ┆ … ┆ 0.001   ┆ 3.67       ┆ 0.1        ┆ all        │
│ (high)      ┆ (aux <= 4) ┆         ┆        ┆   ┆         ┆            ┆            ┆            │
│ …           ┆ …          ┆ …       ┆ …      ┆ … ┆ …       ┆ …          ┆ …          ┆ …          │
│ DRAM-V (aux ┆ VIBRANT    ┆ 1199111 ┆ 3708   ┆ … ┆ 0.0028  ┆ 0.28       ┆ 90.67      ┆ genomad_vi │
│ <= 4, allow ┆ (medium)   ┆         ┆        ┆   ┆         ┆            ┆            ┆ ral        │
│ T)          ┆            ┆         ┆        ┆   ┆         ┆            ┆            ┆            │
│ DRAM-V (aux ┆ VIBRANT    ┆ 1199111 ┆ 12497  ┆ … ┆ 0.0089  ┆ 0.9        ┆ 85.94      ┆ genomad_vi │
│ <= 4, allow ┆ (low)      ┆         ┆        ┆   ┆         ┆            ┆            ┆ ral        │
│ T)          ┆            ┆         ┆        ┆   ┆         ┆            ┆            ┆            │
│ VIBRANT     ┆ VIBRANT    ┆ 1263    ┆ 3708   ┆ … ┆ 0.3406  ┆ 100.0      ┆ 34.06      ┆ genomad_vi │
│ (high)      ┆ (medium)   ┆         ┆        ┆   ┆         ┆            ┆            ┆ ral        │
│ VIBRANT     ┆ VIBRANT    ┆ 1263    ┆ 12497  ┆ … ┆ 0.1011  ┆ 100.0      ┆ 10.11      ┆ genomad_vi │
│ (high)      ┆ (low)      ┆         ┆        ┆   ┆         ┆            ┆            ┆ ral        │
│ VIBRANT     ┆ VIBRANT    ┆ 12497   ┆ 3708   ┆ … ┆ 0.2967  ┆ 29.67      ┆ 100.0      ┆ genomad_vi │
│ (low)       ┆ (medium)   ┆         ┆        ┆   ┆         ┆            ┆            ┆ ral        │
└─────────────┴────────────┴─────────┴────────┴───┴─────────┴────────────┴────────────┴────────────┘

In [32]:
(
    pairwise_df
    .filter(
        (pl.col("tier_a").is_in(DEFAULT_TIERS.values())) & (pl.col("tier_b").is_in(DEFAULT_TIERS.values()))
    )
    .sort(["scope", "jaccard"], descending=[False, True])
)

shape: (6, 10)
┌───────────┬───────────┬──────┬──────┬───┬─────────┬────────────┬────────────┬───────────────┐
│ tier_a    ┆ tier_b    ┆ n_a  ┆ n_b  ┆ … ┆ jaccard ┆ pct_a_in_b ┆ pct_b_in_a ┆ scope         │
│ ---       ┆ ---       ┆ ---  ┆ ---  ┆   ┆ ---     ┆ ---        ┆ ---        ┆ ---           │
│ str       ┆ str       ┆ i64  ┆ i64  ┆   ┆ f64     ┆ f64        ┆ f64        ┆ str           │
╞═══════════╪═══════════╪══════╪══════╪═══╪═════════╪════════════╪════════════╪═══════════════╡
│ CheckAMG  ┆ VIBRANT   ┆ 3218 ┆ 1270 ┆ … ┆ 0.0518  ┆ 6.87       ┆ 17.4       ┆ all           │
│ (high)    ┆ (high)    ┆      ┆      ┆   ┆         ┆            ┆            ┆               │
│ CheckAMG  ┆ DRAM-V    ┆ 3218 ┆ 664  ┆ … ┆ 0.0     ┆ 0.0        ┆ 0.0        ┆ all           │
│ (high)    ┆ (default) ┆      ┆      ┆   ┆         ┆            ┆            ┆               │
│ DRAM-V    ┆ VIBRANT   ┆ 664  ┆ 1270 ┆ … ┆ 0.0     ┆ 0.0        ┆ 0.0        ┆ all           │
│ (default) ┆ (high)    ┆      ┆      ┆   ┆         ┆            ┆            ┆               │
│ CheckAMG  ┆ VIBRANT   ┆ 3151 ┆ 1263 ┆ … ┆ 0.0527  ┆ 7.01       ┆ 17.5       ┆ genomad_viral │
│ (high)    ┆ (high)    ┆      ┆      ┆   ┆         ┆            ┆            ┆               │
│ CheckAMG  ┆ DRAM-V    ┆ 3151 ┆ 621  ┆ … ┆ 0.0     ┆ 0.0        ┆ 0.0        ┆ genomad_viral │
│ (high)    ┆ (default) ┆      ┆      ┆   ┆         ┆            ┆            ┆               │
│ DRAM-V    ┆ VIBRANT   ┆ 621  ┆ 1263 ┆ … ┆ 0.0     ┆ 0.0        ┆ 0.0        ┆ genomad_viral │
│ (default) ┆ (high)    ┆      ┆      ┆   ┆         ┆            ┆            ┆               │
└───────────┴───────────┴──────┴──────┴───┴─────────┴────────────┴────────────┴───────────────┘

## Load and format gene annotations and get per-gene final annotations per tool

Aggregate per-gene lists of hit ids and databases across each tool's `final_annot` annotations. CheckAMG and VIBRANT keep one best hit per gene x reference database, while DRAM-V accepts every hit that passes its filters so multi-domain proteins contribute multiple rows per gene (mostly in Pfam). We keep the multiplicity and test set membership downstream rather than picking a single best hit.

In [33]:
annotations = pl.read_parquet(AMG_TABLES_DIR.joinpath("amg_all_annotations.parquet"))

In [34]:
annotations

shape: (903_000_986, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene      ┆ source    ┆ sample    ┆ ecosystem ┆ … ┆ hit_desc  ┆ bitscore  ┆ evalue    ┆ final_an │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ not      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ bool     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Ga0485157 ┆ Mixed met ┆ freshwate ┆ Aquatic   ┆ … ┆ KDSR,     ┆ 297.57296 ┆ 2.4026e-8 ┆ true     │
│ _0000001_ ┆ agenomes  ┆ r_Ga04851 ┆           ┆   ┆ kdsr; 3-d ┆ 8         ┆ 7         ┆          │
│ 10        ┆           ┆ 57_contig ┆           ┆   ┆ ehydrosph ┆           ┆           ┆          │
│           ┆           ┆ s         ┆           ┆   ┆ inganine  ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ reductase ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ [EC:1.1.1 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ .102]     ┆           ┆           ┆          │
│ Ga0485157 ┆ Mixed met ┆ freshwate ┆ Aquatic   ┆ … ┆ K07124;   ┆ 185.18724 ┆ 3.0093e-5 ┆ false    │
│ _0000001_ ┆ agenomes  ┆ r_Ga04851 ┆           ┆   ┆ uncharact ┆ 1         ┆ 3         ┆          │
│ 10        ┆           ┆ 57_contig ┆           ┆   ┆ erized    ┆           ┆           ┆          │
│           ┆           ┆ s         ┆           ┆   ┆ protein   ┆           ┆           ┆          │
│ Ga0485157 ┆ Mixed met ┆ freshwate ┆ Aquatic   ┆ … ┆ 2-hydroxy ┆ 178.95089 ┆ 2.1448e-5 ┆ true     │
│ _0000001_ ┆ agenomes  ┆ r_Ga04851 ┆           ┆   ┆ cyclohexa ┆ 7         ┆ 1         ┆          │
│ 10        ┆           ┆ 57_contig ┆           ┆   ┆ necarboxy ┆           ┆           ┆          │
│           ┆           ┆ s         ┆           ┆   ┆ l-CoA deh ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ydrogenas ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e [EC:1.1 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ .1.-]     ┆           ┆           ┆          │
│ Ga0485157 ┆ Mixed met ┆ freshwate ┆ Aquatic   ┆ … ┆ badH; 2-h ┆ 178.95089 ┆ 2.1448e-5 ┆ true     │
│ _0000001_ ┆ agenomes  ┆ r_Ga04851 ┆           ┆   ┆ ydroxycyc ┆ 7         ┆ 1         ┆          │
│ 10        ┆           ┆ 57_contig ┆           ┆   ┆ lohexanec ┆           ┆           ┆          │
│           ┆           ┆ s         ┆           ┆   ┆ arboxyl-C ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ oA dehydr ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ogenase   ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ [EC:1.1.1 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ .-]       ┆           ┆           ┆          │
│ Ga0485157 ┆ Mixed met ┆ freshwate ┆ Aquatic   ┆ … ┆ short     ┆ 177.69316 ┆ 2.3708e-5 ┆ true     │
│ _0000001_ ┆ agenomes  ┆ r_Ga04851 ┆           ┆   ┆ chain deh ┆ 1         ┆ 1         ┆          │
│ 10        ┆           ┆ 57_contig ┆           ┆   ┆ ydrogenas ┆           ┆           ┆          │
│           ┆           ┆ s         ┆           ┆   ┆ e         ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ scaffold_ ┆ Viromes   ┆ soil_T42_ ┆ Soil      ┆ … ┆ metN; D-m ┆ 41.1      ┆ 2.1000e-1 ┆ false    │
│ 9_c1_8    ┆           ┆ 15_3_45   ┆           ┆   ┆ ethionine ┆           ┆ 1         ┆          │
│           ┆           ┆           ┆           ┆   ┆ transport ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ system    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ATP-bindi ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ng        ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ protein   ┆           ┆           ┆          │
│ scaffold_ ┆ Viromes   ┆ soil_T42_ ┆ Soil      ┆ … ┆ lsrA,     ┆ 40.3      ┆ 2.5000e-1 ┆ false    │
│ 9_c1_8    ┆           ┆ 15_3_45   ┆           ┆   ┆ ego; AI-2 ┆           ┆ 1         ┆          │
│           ┆           ┆           ┆           ┆   ┆ transport ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ system    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ATP-bindi ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ng        ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ protein   ┆           ┆           ┆          │
│ scaffold_ ┆ Viromes   ┆ soil_T42_ ┆ Soil      ┆ … ┆ occP,     ┆ 40.4      ┆ 2.8000e-1 ┆ false    │
│ 9_c1_8    ┆           ┆ 15_3_45   ┆           ┆   ┆ nocP; oct ┆           ┆ 1         ┆          │
│           ┆           ┆           ┆           ┆   ┆ opine/nop ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ aline     ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ transport ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ system    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ATP-bindi ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ng        ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ protein   ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ [EC:7.4.2 ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ .1]       ┆           ┆           ┆          │
│ scaffold_ ┆ Viromes   ┆ soil_T42_ ┆ Soil      ┆ … ┆ phnK;     ┆ 40.3      ┆ 3.7000e-1 ┆ false    │
│ 9_c1_8    ┆           ┆ 15_3_45   ┆           ┆   ┆ putative  ┆           ┆ 1         ┆          │
│           ┆           ┆           ┆           ┆   ┆ phosphona ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ te        ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ transport ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ system    ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ATP-bindi ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ng        ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ protein   ┆           ┆           ┆          │
│ scaffold_ ┆ Viromes   ┆ soil_T42_ ┆ Soil      ┆ … ┆ rpoE; RNA ┆ 85.8      ┆ 7.0000e-2 ┆ false    │
│ 9_c1_9    ┆           ┆ 15_3_45   ┆           ┆   ┆ polymeras ┆           ┆ 5         ┆          │
│           ┆           ┆           ┆           ┆   ┆ e         ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ sigma-70  ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ factor,   ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ECF       ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ subfamily ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [35]:
annotations_high_default = (
    members
    .join(
        annotations,
        left_on=["source", "sample", "ecosystem", "gene"],
        right_on=["source", "sample", "ecosystem", "gene"],
        how = "left"
    )
)

In [36]:
DB_SUPPORT = {
    "CheckAMG": {"CAMPER", "FOAM", "KEGG", "METABOLIC", "PHROG", "Pfam", "dbCAN"},
    "DRAMV":    {"KEGG", "Pfam", "dbCAN", "VOG", "MEROPS", "RefSeq Viral"},
    "VIBRANT":  {"KEGG", "Pfam", "VOG"},
}

ANNOT_TOOL = {"CheckAMG": "CheckAMG", "DRAMV": "DRAM-V", "VIBRANT": "VIBRANT"}

In [37]:
def likely_false_positive_expr():
    """Gene lacks viral evidence: no genomad viral, no strict region, no nearby viral gene."""
    has_left_viral = pl.col("viral_gene_left_dist").is_not_null()
    has_right_viral = pl.col("viral_gene_right_dist").is_not_null()
    return ~(pl.col("genomad_viral") | pl.col("in_strict_viral_region") | has_left_viral | has_right_viral)

def hits_per_gene(subset: pl.DataFrame, tool: str, prefix: str | None = None) -> pl.DataFrame:
    """Per-gene set of hit_ids and databases for a given annotation-tool string.
    Column names use `prefix` (defaults to `tool`) so tier-prefix-style names
    like DRAMV_hit_ids line up with tier columns.
    """
    pref = prefix or tool
    return (
        subset.filter(pl.col("tool") == tool)
              .group_by("gene", "source", "sample", "ecosystem")
              .agg([
                  pl.col("hit_id").unique().alias(f"{pref}_hit_ids"),
                  pl.col("database").unique().alias(f"{pref}_hit_dbs"),
                  pl.len().alias(f"{pref}_n_hits"),
              ])
    )

def final_hits_per_gene(df: pl.DataFrame, tool: str, prefix: str) -> pl.DataFrame:
    """Per-gene sets of (final_annot=True) hit_ids and databases for a tool."""
    return (
        df.filter((pl.col("tool") == tool) & pl.col("final_annot"))
             .group_by("gene", "source", "sample", "ecosystem")
             .agg([
                 pl.col("hit_id").unique().alias(f"{prefix}_final_hit_ids"),
                 pl.col("database").unique().alias(f"{prefix}_final_hit_dbs"),
                 pl.len().alias(f"{prefix}_n_final_hits"),
             ])
    )

In [38]:
checkamg_hits = hits_per_gene(annotations_high_default, "CheckAMG")
dramv_hits = hits_per_gene(annotations_high_default, ANNOT_TOOL["DRAMV"], "DRAMV")
vibrant_hits = hits_per_gene(annotations_high_default, "VIBRANT")

In [39]:
checkamg_final = final_hits_per_gene(annotations_high_default, ANNOT_TOOL["CheckAMG"], "CheckAMG")
dramv_final = final_hits_per_gene(annotations_high_default, ANNOT_TOOL["DRAMV"], "DRAMV")
vibrant_final = final_hits_per_gene(annotations_high_default, ANNOT_TOOL["VIBRANT"], "VIBRANT")

In [40]:
checkamg_final

shape: (4_245, 7)
┌──────────────┬──────────────┬──────────────┬───────────┬─────────────┬─────────────┬─────────────┐
│ gene         ┆ source       ┆ sample       ┆ ecosystem ┆ CheckAMG_fi ┆ CheckAMG_fi ┆ CheckAMG_n_ │
│ ---          ┆ ---          ┆ ---          ┆ ---       ┆ nal_hit_ids ┆ nal_hit_dbs ┆ final_hits  │
│ str          ┆ str          ┆ str          ┆ str       ┆ ---         ┆ ---         ┆ ---         │
│              ┆              ┆              ┆           ┆ list[str]   ┆ list[str]   ┆ u64         │
╞══════════════╪══════════════╪══════════════╪═══════════╪═════════════╪═════════════╪═════════════╡
│ IMGVR_UViG_3 ┆ Viral        ┆ virus_genome ┆ Human gut ┆ ["PF08645", ┆ ["FOAM",    ┆ 2           │
│ 300045988_16 ┆ genomes      ┆ s_gut        ┆           ┆ "HMMsoil574 ┆ "Pfam"]     ┆             │
│ 6091_3300045 ┆              ┆              ┆           ┆ 11"]        ┆             ┆             │
│ 988_Ga049577 ┆              ┆              ┆           ┆             ┆             ┆             │
│ 6_005041_2   ┆              ┆              ┆           ┆             ┆             ┆             │
│ IMGVR_UViG_3 ┆ Viral        ┆ virus_genome ┆ Human gut ┆ ["PF01507", ┆ ["PHROG",   ┆ 5           │
│ 300045988_08 ┆ genomes      ┆ s_gut        ┆           ┆ "HMMsoil575 ┆ "KEGG", …   ┆             │
│ 5863_3300045 ┆              ┆              ┆           ┆ 93", … "phr ┆ "Pfam"]     ┆             │
│ 988_Ga049577 ┆              ┆              ┆           ┆ og_424"]    ┆             ┆             │
│ 6_142020_49  ┆              ┆              ┆           ┆             ┆             ┆             │
│ scaffold_55_ ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["phrog_363 ┆ ["KEGG",    ┆ 4           │
│ c1_63        ┆ metagenomes  ┆ 3_57         ┆           ┆ ",          ┆ "PHROG",    ┆             │
│              ┆              ┆              ┆           ┆ "K00558",   ┆ "Pfam"]     ┆             │
│              ┆              ┆              ┆           ┆ "PF00145"]  ┆             ┆             │
│ scaffold_101 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["phrog_219 ┆ ["KEGG",    ┆ 3           │
│ 5_c1_44      ┆ metagenomes  ┆ 2_56         ┆           ┆ 7",         ┆ "Pfam",     ┆             │
│              ┆              ┆              ┆           ┆ "PF01227",  ┆ "PHROG"]    ┆             │
│              ┆              ┆              ┆           ┆ "K01495"]   ┆             ┆             │
│ IMGVR_UViG_3 ┆ Viral        ┆ virus_genome ┆ Soil      ┆ ["PF13561"] ┆ ["Pfam"]    ┆ 1           │
│ 300048581_00 ┆ genomes      ┆ s_soil       ┆           ┆             ┆             ┆             │
│ 0026_3300048 ┆              ┆              ┆           ┆             ┆             ┆             │
│ 581_Ga049940 ┆              ┆              ┆           ┆             ┆             ┆             │
│ 4_0506_16    ┆              ┆              ┆           ┆             ┆             ┆             │
│ …            ┆ …            ┆ …            ┆ …         ┆ …           ┆ …           ┆ …           │
│ Ga0485175_00 ┆ Viromes      ┆ freshwater_G ┆ Aquatic   ┆ ["PF02543", ┆ ["PHROG",   ┆ 3           │
│ 00410_24     ┆              ┆ a0485175_con ┆           ┆ "K00612",   ┆ "KEGG",     ┆             │
│              ┆              ┆ tigs         ┆           ┆ "phrog_1601 ┆ "Pfam"]     ┆             │
│              ┆              ┆              ┆           ┆ "]          ┆             ┆             │
│ scaffold_858 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["PF03102"] ┆ ["Pfam"]    ┆ 1           │
│ _c1_24       ┆ metagenomes  ┆ 3_57         ┆           ┆             ┆             ┆             │
│ Ga0485173_00 ┆ Viromes      ┆ freshwater_G ┆ Aquatic   ┆ ["PF02666", ┆ ["Pfam",    ┆ 2           │
│ 00029_28     ┆              ┆ a0485173_con ┆           ┆ "phrog_1267 ┆ "PHROG"]    ┆             │
│              ┆              ┆ tigs         ┆           ┆ 0"]         ┆             ┆             │
│ Ga0485159_00 ┆ Mixed        ┆ freshwater_G ┆ Aquatic   ┆ ["K04756"]  ┆ ["KEGG"]    ┆ 1           │
│ 00724_17     ┆ metagenomes  ┆ a0485159_con ┆           ┆             ┆             ┆             │
│              ┆              ┆ tigs         ┆           ┆             ┆             ┆             │
│ scaffold_169 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["K01495",  ┆ ["Pfam",    ┆ 3           │
│ 3_c1_19      ┆ metagenomes  ┆ 2_56         ┆           ┆ "phrog_2197 ┆ "KEGG",     ┆             │
│              ┆              ┆              ┆           ┆ ",          ┆ "PHROG"]    ┆             │
│              ┆              ┆              ┆           ┆ "PF01227"]  ┆             ┆             │
└──────────────┴──────────────┴──────────────┴───────────┴─────────────┴─────────────┴─────────────┘

In [41]:
dramv_final

shape: (4_581, 7)
┌──────────────┬──────────────┬──────────────┬───────────┬─────────────┬─────────────┬─────────────┐
│ gene         ┆ source       ┆ sample       ┆ ecosystem ┆ DRAMV_final ┆ DRAMV_final ┆ DRAMV_n_fin │
│ ---          ┆ ---          ┆ ---          ┆ ---       ┆ _hit_ids    ┆ _hit_dbs    ┆ al_hits     │
│ str          ┆ str          ┆ str          ┆ str       ┆ ---         ┆ ---         ┆ ---         │
│              ┆              ┆              ┆           ┆ list[str]   ┆ list[str]   ┆ u64         │
╞══════════════╪══════════════╪══════════════╪═══════════╪═════════════╪═════════════╪═════════════╡
│ Ga0485175_00 ┆ Viromes      ┆ freshwater_G ┆ Aquatic   ┆ ["PF00109", ┆ ["Pfam"]    ┆ 6           │
│ 01214_31     ┆              ┆ a0485175_con ┆           ┆ "PF00676",  ┆             ┆             │
│              ┆              ┆ tigs         ┆           ┆ …           ┆             ┆             │
│              ┆              ┆              ┆           ┆ "PF00490"]  ┆             ┆             │
│ scaffold_358 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["PF03435", ┆ ["Pfam"]    ┆ 10          │
│ 2_c1_5       ┆ metagenomes  ┆ 3_57         ┆           ┆ "PF01370",  ┆             ┆             │
│              ┆              ┆              ┆           ┆ …           ┆             ┆             │
│              ┆              ┆              ┆           ┆ "PF02675"]  ┆             ┆             │
│ scaffold_291 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["PF02445", ┆ ["Pfam"]    ┆ 4           │
│ 2_c1_15      ┆ metagenomes  ┆ 1_55         ┆           ┆ "PF02350",  ┆             ┆             │
│              ┆              ┆              ┆           ┆ …           ┆             ┆             │
│              ┆              ┆              ┆           ┆ "PF01227"]  ┆             ┆             │
│ scaffold_896 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["PF03659", ┆ ["Pfam"]    ┆ 4           │
│ _c1_20       ┆ metagenomes  ┆ 2_56         ┆           ┆ "PF03171",  ┆             ┆             │
│              ┆              ┆              ┆           ┆ …           ┆             ┆             │
│              ┆              ┆              ┆           ┆ "PF01384"]  ┆             ┆             │
│ Ga0485173_00 ┆ Viromes      ┆ freshwater_G ┆ Aquatic   ┆ ["PF11775", ┆ ["Pfam"]    ┆ 7           │
│ 00271_47     ┆              ┆ a0485173_con ┆           ┆ "PF13640",  ┆             ┆             │
│              ┆              ┆ tigs         ┆           ┆ …           ┆             ┆             │
│              ┆              ┆              ┆           ┆ "PF01050"]  ┆             ┆             │
│ …            ┆ …            ┆ …            ┆ …         ┆ …           ┆ …           ┆ …           │
│ scaffold_703 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["PF02274", ┆ ["Pfam"]    ┆ 10          │
│ _c1_26       ┆ metagenomes  ┆ 2_56         ┆           ┆ "PF04896",  ┆             ┆             │
│              ┆              ┆              ┆           ┆ …           ┆             ┆             │
│              ┆              ┆              ┆           ┆ "PF10396"]  ┆             ┆             │
│ Ga0485174_00 ┆ Viromes      ┆ freshwater_G ┆ Aquatic   ┆ ["PF00120", ┆ ["Pfam"]    ┆ 6           │
│ 08544_6      ┆              ┆ a0485174_con ┆           ┆ "PF03951",  ┆             ┆             │
│              ┆              ┆ tigs         ┆           ┆ …           ┆             ┆             │
│              ┆              ┆              ┆           ┆ "PF01120"]  ┆             ┆             │
│ IMGVR_UViG_3 ┆ Viral        ┆ virus_genome ┆ Human gut ┆ ["PF01761", ┆ ["Pfam"]    ┆ 4           │
│ 300045988_11 ┆ genomes      ┆ s_gut        ┆           ┆ "PF01663",  ┆             ┆             │
│ 6494_3300045 ┆              ┆              ┆           ┆ …           ┆             ┆             │
│ 988_Ga049577 ┆              ┆              ┆           ┆ "PF04095"]  ┆             ┆             │
│ 6_122541_102 ┆              ┆              ┆           ┆             ┆             ┆             │
│ IMGVR_UViG_3 ┆ Viral        ┆ virus_genome ┆ Human gut ┆ ["PF03328", ┆ ["Pfam"]    ┆ 2           │
│ 300045988_02 ┆ genomes      ┆ s_gut        ┆           ┆ "PF14819"]  ┆             ┆             │
│ 6861_3300045 ┆              ┆              ┆           ┆             ┆             ┆             │
│ 988_Ga049577 ┆              ┆              ┆           ┆             ┆             ┆             │
│ 6_018363_44  ┆              ┆              ┆           ┆             ┆             ┆             │
│ IMGVR_UViG_3 ┆ Viral        ┆ virus_genome ┆ Aquatic   ┆ ["PF00361", ┆ ["Pfam",    ┆ 8           │
│ 300023215_00 ┆ genomes      ┆ s_marine     ┆           ┆ "PF01144",  ┆ "KEGG"]     ┆             │
│ 3041_3300023 ┆              ┆              ┆           ┆ …           ┆             ┆             │
│ 215_Ga025580 ┆              ┆              ┆           ┆ "PF00208"]  ┆             ┆             │
│ 6_1000144_15 ┆              ┆              ┆           ┆             ┆             ┆             │
│ 782-91745_50 ┆              ┆              ┆           ┆             ┆             ┆             │
└──────────────┴──────────────┴──────────────┴───────────┴─────────────┴─────────────┴─────────────┘

In [42]:
vibrant_final

shape: (2_328, 7)
┌──────────────┬──────────────┬──────────────┬───────────┬─────────────┬─────────────┬─────────────┐
│ gene         ┆ source       ┆ sample       ┆ ecosystem ┆ VIBRANT_fin ┆ VIBRANT_fin ┆ VIBRANT_n_f │
│ ---          ┆ ---          ┆ ---          ┆ ---       ┆ al_hit_ids  ┆ al_hit_dbs  ┆ inal_hits   │
│ str          ┆ str          ┆ str          ┆ str       ┆ ---         ┆ ---         ┆ ---         │
│              ┆              ┆              ┆           ┆ list[str]   ┆ list[str]   ┆ u64         │
╞══════════════╪══════════════╪══════════════╪═══════════╪═════════════╪═════════════╪═════════════╡
│ Ga0485173_00 ┆ Viromes      ┆ freshwater_G ┆ Aquatic   ┆ ["K12452",  ┆ ["Pfam",    ┆ 2           │
│ 00008_166    ┆              ┆ a0485173_con ┆           ┆ "PF01041"]  ┆ "KEGG"]     ┆             │
│              ┆              ┆ tigs         ┆           ┆             ┆             ┆             │
│ scaffold_141 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["K06720",  ┆ ["Pfam",    ┆ 2           │
│ 0_c1_46      ┆ metagenomes  ┆ 2_56         ┆           ┆ "PF06339"]  ┆ "KEGG"]     ┆             │
│ scaffold_514 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["K00059",  ┆ ["Pfam",    ┆ 2           │
│ _c1_37       ┆ metagenomes  ┆ 3_57         ┆           ┆ "PF00106"]  ┆ "KEGG"]     ┆             │
│ scaffold_304 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["PF03102", ┆ ["KEGG",    ┆ 2           │
│ _c1_11       ┆ metagenomes  ┆ 2_56         ┆           ┆ "K01654"]   ┆ "Pfam"]     ┆             │
│ IMGVR_UViG_3 ┆ Viral        ┆ virus_genome ┆ Soil      ┆ ["K00558",  ┆ ["KEGG",    ┆ 2           │
│ 300012862_00 ┆ genomes      ┆ s_soil       ┆           ┆ "PF00145"]  ┆ "Pfam"]     ┆             │
│ 0037_3300012 ┆              ┆              ┆           ┆             ┆             ┆             │
│ 862_Ga016048 ┆              ┆              ┆           ┆             ┆             ┆             │
│ 3_1000225_54 ┆              ┆              ┆           ┆             ┆             ┆             │
│ 20-48970_13  ┆              ┆              ┆           ┆             ┆             ┆             │
│ …            ┆ …            ┆ …            ┆ …         ┆ …           ┆ …           ┆ …           │
│ scaffold_216 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["PF03275", ┆ ["Pfam",    ┆ 2           │
│ _c1_43       ┆ metagenomes  ┆ 2_56         ┆           ┆ "K01854"]   ┆ "KEGG"]     ┆             │
│ scaffold_111 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["PF01227", ┆ ["KEGG",    ┆ 2           │
│ 8_c1_17      ┆ metagenomes  ┆ 3_57         ┆           ┆ "K01495"]   ┆ "Pfam"]     ┆             │
│ scaffold_398 ┆ Mixed        ┆ soil_T42_15_ ┆ Soil      ┆ ["PF01227", ┆ ["KEGG",    ┆ 2           │
│ _c1_38       ┆ metagenomes  ┆ 2_56         ┆           ┆ "K01495"]   ┆ "Pfam"]     ┆             │
│ Ga0485159_00 ┆ Mixed        ┆ freshwater_G ┆ Aquatic   ┆ ["K12452",  ┆ ["Pfam",    ┆ 2           │
│ 00012_142    ┆ metagenomes  ┆ a0485159_con ┆           ┆ "PF01041"]  ┆ "KEGG"]     ┆             │
│              ┆              ┆ tigs         ┆           ┆             ┆             ┆             │
│ Ga0485175_00 ┆ Viromes      ┆ freshwater_G ┆ Aquatic   ┆ ["PF01227", ┆ ["Pfam",    ┆ 2           │
│ 18443_5      ┆              ┆ a0485175_con ┆           ┆ "K01495"]   ┆ "KEGG"]     ┆             │
│              ┆              ┆ tigs         ┆           ┆             ┆             ┆             │
└──────────────┴──────────────┴──────────────┴───────────┴─────────────┴─────────────┴─────────────┘

## Why do other tools not call the same gene AMG?

For every gene called AMG at default / high by one tool, classify why each other tool did not agree. Each source tier produces two classifications (one per other tool), based on six mutually exclusive categories plus a "lacks viral evidence" flag and an "agrees at default / high" pass-through:

- **a.** Called at a different tier
- **b.** Lacks viral evidence
- **c.** Source tool's best-hit database not queried by the other tool
- **d.** Shared-database hit id between the two tools, but the other tool did not flag it as an AMG
- **e.** Other tool has a hit for the gene in a shared database but returned a different top hit
- **f.** Other tool produced no annotation at all

The source tool's set of `final_annot` hit ids is compared against the other tool's entire raw annotation set, so a tool that hit the gene in any shared database is credited. Database-overlap checks use the union of the source tool's final databases. Category `c` applies only when none of those databases is queried by the other tool.

In [43]:
SOURCE_TIERS = [
    ("CheckAMG_high", "CheckAMG"),
    ("DRAMV_default", "DRAMV"),
    ("VIBRANT_high",  "VIBRANT"),
]

OTHER_TIER_FLAGS = {
    "CheckAMG": [pl.col("CheckAMG_medium"), pl.col("CheckAMG_low")],
    "DRAMV":    [pl.col("DRAMV_allow_T"), pl.col("DRAMV_aux_4"), pl.col("DRAMV_aux_4_allow_T")],
    "VIBRANT":  [pl.col("VIBRANT_medium"), pl.col("VIBRANT_low")],
}

AGREE_FLAG = {
    "CheckAMG": pl.col("CheckAMG_high"),
    "DRAMV":    pl.col("DRAMV_default"),
    "VIBRANT":  pl.col("VIBRANT_high"),
}

In [44]:
members_annot = (
    members
    .join(checkamg_hits,  on=["gene", "sample", "source", "ecosystem"], how="left")
    .join(dramv_hits,     on=["gene", "sample", "source", "ecosystem"], how="left")
    .join(vibrant_hits,   on=["gene", "sample", "source", "ecosystem"], how="left")
    .join(checkamg_final, on=["gene", "sample", "source", "ecosystem"], how="left")
    .join(dramv_final,    on=["gene", "sample", "source", "ecosystem"], how="left")
    .join(vibrant_final,  on=["gene", "sample", "source", "ecosystem"], how="left")
    .with_columns([
        pl.col(c).fill_null(0).cast(pl.Int64)
        for c in [
            "CheckAMG_n_hits", "DRAMV_n_hits", "VIBRANT_n_hits",
            "CheckAMG_n_final_hits", "DRAMV_n_final_hits", "VIBRANT_n_final_hits",
        ]
    ])
    .with_columns(likely_false_positive_expr().alias("likely_false_positive"))
)

In [45]:
def classify_nonoverlap(m: pl.DataFrame, source_tiers=SOURCE_TIERS,
                        return_per_gene: bool = False) -> pl.DataFrame:
    rows = []
    per_gene = []
    for src_tier, src_tool in source_tiers:
        src_set = m.filter(pl.col(src_tier))
        n_total = src_set.height
        n_b = int(src_set.filter(pl.col("likely_false_positive")).height)

        for other_tool in ["CheckAMG", "DRAMV", "VIBRANT"]:
            if other_tool == src_tool:
                continue

            agree_default_high = AGREE_FLAG[other_tool]
            other_any_tier = pl.any_horizontal([AGREE_FLAG[other_tool]] + OTHER_TIER_FLAGS[other_tool])

            src_hit_ids = pl.col(f"{src_tool}_final_hit_ids")
            src_dbs     = pl.col(f"{src_tool}_final_hit_dbs")
            other_hits  = pl.col(f"{other_tool}_hit_ids")
            other_n     = pl.col(f"{other_tool}_n_hits")

            shared_hit = (
                pl.when(src_hit_ids.is_null() | other_hits.is_null())
                  .then(False)
                  .otherwise(src_hit_ids.list.set_intersection(other_hits).list.len() > 0)
            )
            src_db_supported = (
                pl.when(src_dbs.is_null())
                  .then(False)
                  .otherwise(src_dbs.list.eval(pl.element().is_in(list(DB_SUPPORT[other_tool]))).list.any())
            )
            has_any_hits = other_n > 0

            cat_expr = (
                pl.when(other_any_tier & ~agree_default_high)
                  .then(pl.lit("a. other tool called at different tier"))
                  .when(agree_default_high)
                  .then(pl.lit("agrees at default/high"))
                  .when(shared_hit)
                  .then(pl.lit("d. same db hit_id, not flagged AMG"))
                  .when(has_any_hits & ~src_db_supported)
                  .then(pl.lit("c. source tool's best-hit db not used by other tool"))
                  .when(has_any_hits)
                  .then(pl.lit("e. other tool annotated different hit in shared db"))
                  .otherwise(pl.lit("f. other tool produced no hits for this gene"))
            )
            classified = src_set.with_columns(cat_expr.alias("category"))
            per_gene.append(classified.select([
                "gene", "source", "sample", "ecosystem",
                pl.lit(src_tier).alias("source_tier"),
                pl.lit(other_tool).alias("other_tool"),
                "category", "likely_false_positive",
            ]))
            counts = (
                classified.group_by("category").agg(pl.len().alias("n"))
                          .with_columns([
                              pl.lit(src_tier).alias("source_tier"),
                              pl.lit(other_tool).alias("other_tool"),
                              pl.lit(n_total).alias("source_total"),
                          ])
            )
            rows.append(counts)

        rows.append(pl.DataFrame({
            "category": ["b. gene lacks any viral evidence"],
            "n": [n_b],
            "source_tier": [src_tier],
            "other_tool": [None],
            "source_total": [n_total],
        }).cast({"n": pl.UInt32}))

    if return_per_gene:
        return pl.concat(per_gene, how="vertical_relaxed")
    return (
        pl.concat(rows, how="diagonal_relaxed")
          .with_columns((pl.col("n") / pl.col("source_total") * 100).round(2).alias("pct"))
    )

In [46]:
overlap_classification = (
    classify_nonoverlap(members_annot)
    .sort(["source_tier", "other_tool", "n"], descending=[False, False, True])
)

In [47]:
with pl.Config(tbl_rows=100, tbl_width_chars=800):
    print(overlap_classification)

shape: (28, 6)
┌─────────────────────────────────────────────────────┬──────┬───────────────┬────────────┬──────────────┬───────┐
│ category                                            ┆ n    ┆ source_tier   ┆ other_tool ┆ source_total ┆ pct   │
│ ---                                                 ┆ ---  ┆ ---           ┆ ---        ┆ ---          ┆ ---   │
│ str                                                 ┆ u64  ┆ str           ┆ str        ┆ i64          ┆ f64   │
╞═════════════════════════════════════════════════════╪══════╪═══════════════╪════════════╪══════════════╪═══════╡
│ b. gene lacks any viral evidence                    ┆ 0    ┆ CheckAMG_high ┆ null       ┆ 3218         ┆ 0.0   │
│ a. other tool called at different tier              ┆ 2988 ┆ CheckAMG_high ┆ DRAMV      ┆ 3218         ┆ 92.85 │
│ d. same db hit_id, not flagged AMG                  ┆ 188  ┆ CheckAMG_high ┆ DRAMV      ┆ 3218         ┆ 5.84  │
│ e. other tool annotated different hit in shared db  ┆ 28   ┆ CheckAMG_high ┆ DRAMV      ┆ 3218         ┆ 0.87  │
│ c. source tool's best-hit db not used by other tool ┆ 14   ┆ CheckAMG_high ┆ DRAMV      ┆ 3218         ┆ 0.44  │
│ d. same db hit_id, not flagged AMG                  ┆ 1577 ┆ CheckAMG_high ┆ VIBRANT    ┆ 3218         ┆ 49.01 │
│ a. other tool called at different tier              ┆ 1053 ┆ CheckAMG_high ┆ VIBRANT    ┆ 3218         ┆ 32.72 │
│ agrees at default/high                              ┆ 221  ┆ CheckAMG_high ┆ VIBRANT    ┆ 3218         ┆ 6.87  │
│ e. other tool annotated different hit in shared db  ┆ 191  ┆ CheckAMG_high ┆ VIBRANT    ┆ 3218         ┆ 5.94  │
│ c. source tool's best-hit db not used by other tool ┆ 117  ┆ CheckAMG_high ┆ VIBRANT    ┆ 3218         ┆ 3.64  │
│ f. other tool produced no hits for this gene        ┆ 59   ┆ CheckAMG_high ┆ VIBRANT    ┆ 3218         ┆ 1.83  │
│ b. gene lacks any viral evidence                    ┆ 2    ┆ DRAMV_default ┆ null       ┆ 664          ┆ 0.3   │
│ f. other tool produced no hits for this gene        ┆ 354  ┆ DRAMV_default ┆ CheckAMG   ┆ 664          ┆ 53.31 │
│ e. other tool annotated different hit in shared db  ┆ 287  ┆ DRAMV_default ┆ CheckAMG   ┆ 664          ┆ 43.22 │
│ d. same db hit_id, not flagged AMG                  ┆ 18   ┆ DRAMV_default ┆ CheckAMG   ┆ 664          ┆ 2.71  │
│ a. other tool called at different tier              ┆ 5    ┆ DRAMV_default ┆ CheckAMG   ┆ 664          ┆ 0.75  │
│ f. other tool produced no hits for this gene        ┆ 433  ┆ DRAMV_default ┆ VIBRANT    ┆ 664          ┆ 65.21 │
│ e. other tool annotated different hit in shared db  ┆ 214  ┆ DRAMV_default ┆ VIBRANT    ┆ 664          ┆ 32.23 │
│ d. same db hit_id, not flagged AMG                  ┆ 12   ┆ DRAMV_default ┆ VIBRANT    ┆ 664          ┆ 1.81  │
│ a. other tool called at different tier              ┆ 5    ┆ DRAMV_default ┆ VIBRANT    ┆ 664          ┆ 0.75  │
│ b. gene lacks any viral evidence                    ┆ 0    ┆ VIBRANT_high  ┆ null       ┆ 1270         ┆ 0.0   │
│ d. same db hit_id, not flagged AMG                  ┆ 991  ┆ VIBRANT_high  ┆ CheckAMG   ┆ 1270         ┆ 78.03 │
│ agrees at default/high                              ┆ 221  ┆ VIBRANT_high  ┆ CheckAMG   ┆ 1270         ┆ 17.4  │
│ a. other tool called at different tier              ┆ 54   ┆ VIBRANT_high  ┆ CheckAMG   ┆ 1270         ┆ 4.25  │
│ e. other tool annotated different hit in shared db  ┆ 4    ┆ VIBRANT_high  ┆ CheckAMG   ┆ 1270         ┆ 0.31  │
│ a. other tool called at different tier              ┆ 1145 ┆ VIBRANT_high  ┆ DRAMV      ┆ 1270         ┆ 90.16 │
│ d. same db hit_id, not flagged AMG                  ┆ 111  ┆ VIBRANT_high  ┆ DRAMV      ┆ 1270         ┆ 8.74  │
│ e. other tool annotated different hit in shared db  ┆ 14   ┆ VIBRANT_high  ┆ DRAMV      ┆ 1270         ┆ 1.1   │
└─────────────────────────────────────────────────────┴──────┴───────────────┴────────────┴──────────────┴───────┘

## Which tier has more viral context when tools disagree?

For every gene called at default or high by one tool and at a different tier by another, compare genomic context: geNomad viral prediction, CheckAMG's strict viral region flag, flanking viral genes within 10 kb, and flanking MGE V-score (virus-like at V >= 10, host-like below).

In [48]:
VIRAL_VSCORE_MIN = 10
MAX_DIST = 10_000

In [49]:
def context_flags():
    near_viral_any = (
        (pl.col("viral_gene_left_dist").is_not_null() & (pl.col("viral_gene_left_dist") <= MAX_DIST))
        | (pl.col("viral_gene_right_dist").is_not_null() & (pl.col("viral_gene_right_dist") <= MAX_DIST))
    )
    near_viral_both = (
        pl.col("viral_gene_left_dist").is_not_null() & (pl.col("viral_gene_left_dist") <= MAX_DIST)
        & pl.col("viral_gene_right_dist").is_not_null() & (pl.col("viral_gene_right_dist") <= MAX_DIST)
    )
    near_mge_any = (
        (pl.col("MGE_gene_left_dist").is_not_null() & (pl.col("MGE_gene_left_dist") <= MAX_DIST))
        | (pl.col("MGE_gene_right_dist").is_not_null() & (pl.col("MGE_gene_right_dist") <= MAX_DIST))
    )
    # NaN V-scores are nulled first so an undefined V-score is not counted as virus-like
    _vl = pl.col("MGE_gene_left_V_score").fill_nan(None)
    _vr = pl.col("MGE_gene_right_V_score").fill_nan(None)
    near_virus_like_mge = (
        (_vl.is_not_null() & (_vl >= VIRAL_VSCORE_MIN))
        | (_vr.is_not_null() & (_vr >= VIRAL_VSCORE_MIN))
    )
    near_bact_like_mge = (
        (_vl.is_not_null() & (_vl < VIRAL_VSCORE_MIN))
        | (_vr.is_not_null() & (_vr < VIRAL_VSCORE_MIN))
    )
    return [
        near_viral_any.alias("near_viral_gene"),
        near_viral_both.alias("near_viral_gene_both_sides"),
        near_mge_any.alias("near_mge_gene"),
        near_virus_like_mge.alias("near_virus_like_mge"),
        near_bact_like_mge.alias("near_bact_like_mge"),
    ]

In [50]:
CONFLICT_SCENARIOS = [
    ("CheckAMG_high_vs_DRAMV_allow_T",
        pl.col("CheckAMG_high") & pl.col("DRAMV_allow_T") & ~pl.col("DRAMV_default")),
    ("CheckAMG_high_vs_DRAMV_aux_4",
        pl.col("CheckAMG_high") & pl.col("DRAMV_aux_4") & ~pl.col("DRAMV_default")),
    ("CheckAMG_high_vs_DRAMV_aux_4_allow_T",
        pl.col("CheckAMG_high") & pl.col("DRAMV_aux_4_allow_T")
        & ~pl.col("DRAMV_default") & ~pl.col("DRAMV_allow_T") & ~pl.col("DRAMV_aux_4")),
    ("VIBRANT_high_vs_DRAMV_allow_T",
        pl.col("VIBRANT_high") & pl.col("DRAMV_allow_T") & ~pl.col("DRAMV_default")),
    ("VIBRANT_high_vs_DRAMV_aux_4_allow_T",
        pl.col("VIBRANT_high") & pl.col("DRAMV_aux_4_allow_T")
        & ~pl.col("DRAMV_default") & ~pl.col("DRAMV_allow_T") & ~pl.col("DRAMV_aux_4")),
    ("DRAMV_default_vs_CheckAMG_low",
        pl.col("DRAMV_default") & pl.col("CheckAMG_low")),
    ("DRAMV_default_vs_VIBRANT_low",
        pl.col("DRAMV_default") & pl.col("VIBRANT_low")),
    ("CheckAMG_high_vs_VIBRANT_low",
        pl.col("CheckAMG_high") & pl.col("VIBRANT_low") & ~pl.col("VIBRANT_high")),
    ("VIBRANT_high_vs_CheckAMG_low",
        pl.col("VIBRANT_high") & pl.col("CheckAMG_low") & ~pl.col("CheckAMG_high")),
]

In [51]:
members_ctx = members_annot.with_columns(context_flags())

rows = []
for label, expr in CONFLICT_SCENARIOS:
    sub = members_ctx.filter(expr)
    n = sub.height
    if n == 0:
        rows.append({"scenario": label, "n_genes": 0})
        continue
    def ct(e):
        return int(sub.filter(e).height)
    rows.append({
        "scenario": label,
        "n_genes": n,
        "n_genomad_viral":         ct(pl.col("genomad_viral")),
        "n_strict_viral_region":   ct(pl.col("in_strict_viral_region")),
        "n_near_viral_gene":       ct(pl.col("near_viral_gene")),
        "n_near_viral_both_sides": ct(pl.col("near_viral_gene_both_sides")),
        "n_near_virus_like_mge":   ct(pl.col("near_virus_like_mge")),
        "n_near_bact_like_mge":    ct(pl.col("near_bact_like_mge")),
        "n_no_viral_evidence":     ct(~(pl.col("genomad_viral") | pl.col("in_strict_viral_region") | pl.col("near_viral_gene"))),
    })

amg_tier_conflict_df = pl.DataFrame(rows).with_columns([
    (pl.col("n_genomad_viral")         / pl.col("n_genes") * 100).round(1).alias("pct_genomad_viral"),
    (pl.col("n_strict_viral_region")   / pl.col("n_genes") * 100).round(1).alias("pct_strict_viral_region"),
    (pl.col("n_near_viral_gene")       / pl.col("n_genes") * 100).round(1).alias("pct_near_viral_gene"),
    (pl.col("n_near_viral_both_sides") / pl.col("n_genes") * 100).round(1).alias("pct_near_viral_both_sides"),
    (pl.col("n_near_virus_like_mge")   / pl.col("n_genes") * 100).round(1).alias("pct_near_virus_like_mge"),
    (pl.col("n_near_bact_like_mge")    / pl.col("n_genes") * 100).round(1).alias("pct_near_bact_like_mge"),
    (pl.col("n_no_viral_evidence")     / pl.col("n_genes") * 100).round(1).alias("pct_no_viral_evidence"),
])

In [52]:
amg_tier_conflict_df

shape: (9, 16)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ scenario   ┆ n_genes ┆ n_genomad ┆ n_strict_ ┆ … ┆ pct_near_ ┆ pct_near_ ┆ pct_near_ ┆ pct_no_vi │
│ ---        ┆ ---     ┆ _viral    ┆ viral_reg ┆   ┆ viral_bot ┆ virus_lik ┆ bact_like ┆ ral_evide │
│ str        ┆ i64     ┆ ---       ┆ ion       ┆   ┆ h_sides   ┆ e_mge     ┆ _mge      ┆ nce       │
│            ┆         ┆ i64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆           ┆ i64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CheckAMG_h ┆ 21      ┆ 21        ┆ 19        ┆ … ┆ 76.2      ┆ 23.8      ┆ 0.0       ┆ 0.0       │
│ igh_vs_DRA ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ MV_allow_T ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ CheckAMG_h ┆ 118     ┆ 111       ┆ 89        ┆ … ┆ 61.0      ┆ 5.1       ┆ 0.0       ┆ 0.0       │
│ igh_vs_DRA ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ MV_aux_4   ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ CheckAMG_h ┆ 2849    ┆ 2800      ┆ 2610      ┆ … ┆ 77.9      ┆ 35.3      ┆ 1.1       ┆ 0.0       │
│ igh_vs_DRA ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ MV_aux_4_a ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ llow_T     ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ VIBRANT_hi ┆ 8       ┆ 8         ┆ 8         ┆ … ┆ 87.5      ┆ 62.5      ┆ 0.0       ┆ 0.0       │
│ gh_vs_DRAM ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ V_allow_T  ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ VIBRANT_hi ┆ 1135    ┆ 1128      ┆ 1086      ┆ … ┆ 89.4      ┆ 68.8      ┆ 1.3       ┆ 0.0       │
│ gh_vs_DRAM ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ V_aux_4_al ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ low_T      ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ DRAMV_defa ┆ 5       ┆ 3         ┆ 2         ┆ … ┆ 40.0      ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ ult_vs_Che ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ ckAMG_low  ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ DRAMV_defa ┆ 5       ┆ 5         ┆ 4         ┆ … ┆ 60.0      ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ ult_vs_VIB ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ RANT_low   ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ CheckAMG_h ┆ 1053    ┆ 1050      ┆ 958       ┆ … ┆ 74.3      ┆ 29.7      ┆ 0.9       ┆ 0.0       │
│ igh_vs_VIB ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ RANT_low   ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ VIBRANT_hi ┆ 54      ┆ 51        ┆ 30        ┆ … ┆ 55.6      ┆ 55.6      ┆ 0.0       ┆ 0.0       │
│ gh_vs_Chec ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ kAMG_low   ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [53]:
rows = []
for label in ALL_TIERS:
    sub = members_ctx.filter(pl.col(label))
    tool = label.split("_")[0] if not label.startswith("DRAMV") else "DRAM-V"
    n = sub.height
    if n == 0:
        rows.append({"tool": tool, "tier": label, "n_genes": 0})
        continue
    def ct(e):
        return int(sub.filter(e).height)
    rows.append({
        "tool": tool,
        "tier": label,
        "n_genes": n,
        "n_genomad_viral":         ct(pl.col("genomad_viral")),
        "n_strict_viral_region":   ct(pl.col("in_strict_viral_region")),
        "n_near_viral_gene":       ct(pl.col("near_viral_gene")),
        "n_near_viral_both_sides": ct(pl.col("near_viral_gene_both_sides")),
        "n_near_virus_like_mge":   ct(pl.col("near_virus_like_mge")),
        "n_near_bact_like_mge":    ct(pl.col("near_bact_like_mge")),
        "n_no_viral_evidence":     ct(~(pl.col("genomad_viral") | pl.col("in_strict_viral_region") | pl.col("near_viral_gene"))),
    })

amg_all_tier_df = pl.DataFrame(rows).with_columns([
    (pl.col("n_genomad_viral")         / pl.col("n_genes") * 100).round(1).alias("pct_genomad_viral"),
    (pl.col("n_strict_viral_region")   / pl.col("n_genes") * 100).round(1).alias("pct_strict_viral_region"),
    (pl.col("n_near_viral_gene")       / pl.col("n_genes") * 100).round(1).alias("pct_near_viral_gene"),
    (pl.col("n_near_viral_both_sides") / pl.col("n_genes") * 100).round(1).alias("pct_near_viral_both_sides"),
    (pl.col("n_near_virus_like_mge")   / pl.col("n_genes") * 100).round(1).alias("pct_near_virus_like_mge"),
    (pl.col("n_near_bact_like_mge")    / pl.col("n_genes") * 100).round(1).alias("pct_near_bact_like_mge"),
    (pl.col("n_no_viral_evidence")     / pl.col("n_genes") * 100).round(1).alias("pct_no_viral_evidence"),
])

In [54]:
amg_all_tier_df

shape: (10, 17)
┌──────────┬────────────┬─────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ tool     ┆ tier       ┆ n_genes ┆ n_genomad_ ┆ … ┆ pct_near_ ┆ pct_near_ ┆ pct_near_ ┆ pct_no_vi │
│ ---      ┆ ---        ┆ ---     ┆ viral      ┆   ┆ viral_bot ┆ virus_lik ┆ bact_like ┆ ral_evide │
│ str      ┆ str        ┆ i64     ┆ ---        ┆   ┆ h_sides   ┆ e_mge     ┆ _mge      ┆ nce       │
│          ┆            ┆         ┆ i64        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆            ┆         ┆            ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪════════════╪═════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ CheckAMG ┆ CheckAMG_h ┆ 3218    ┆ 3151       ┆ … ┆ 73.2      ┆ 33.5      ┆ 1.0       ┆ 0.0       │
│          ┆ igh        ┆         ┆            ┆   ┆           ┆           ┆           ┆           │
│ CheckAMG ┆ CheckAMG_m ┆ 3261    ┆ 3193       ┆ … ┆ 73.0      ┆ 33.7      ┆ 1.0       ┆ 0.0       │
│          ┆ edium      ┆         ┆            ┆   ┆           ┆           ┆           ┆           │
│ CheckAMG ┆ CheckAMG_l ┆ 3277    ┆ 3205       ┆ … ┆ 72.8      ┆ 33.8      ┆ 1.0       ┆ 0.0       │
│          ┆ ow         ┆         ┆            ┆   ┆           ┆           ┆           ┆           │
│ DRAM-V   ┆ DRAMV_defa ┆ 664     ┆ 621        ┆ … ┆ 27.6      ┆ 5.0       ┆ 0.3       ┆ 0.3       │
│          ┆ ult        ┆         ┆            ┆   ┆           ┆           ┆           ┆           │
│ DRAM-V   ┆ DRAMV_allo ┆ 690     ┆ 647        ┆ … ┆ 29.6      ┆ 6.1       ┆ 0.3       ┆ 0.3       │
│          ┆ w_T        ┆         ┆            ┆   ┆           ┆           ┆           ┆           │
│ DRAM-V   ┆ DRAMV_aux_ ┆ 783     ┆ 733        ┆ … ┆ 32.6      ┆ 5.0       ┆ 0.3       ┆ 0.3       │
│          ┆ 4          ┆         ┆            ┆   ┆           ┆           ┆           ┆           │
│ DRAM-V   ┆ DRAMV_aux_ ┆ 4583    ┆ 4477       ┆ … ┆ 72.5      ┆ 36.9      ┆ 1.0       ┆ 0.0       │
│          ┆ 4_allow_T  ┆         ┆            ┆   ┆           ┆           ┆           ┆           │
│ VIBRANT  ┆ VIBRANT_hi ┆ 1270    ┆ 1263       ┆ … ┆ 86.0      ┆ 68.7      ┆ 1.3       ┆ 0.0       │
│          ┆ gh         ┆         ┆            ┆   ┆           ┆           ┆           ┆           │
│ VIBRANT  ┆ VIBRANT_me ┆ 1574    ┆ 1567       ┆ … ┆ 85.8      ┆ 64.4      ┆ 1.4       ┆ 0.0       │
│          ┆ dium       ┆         ┆            ┆   ┆           ┆           ┆           ┆           │
│ VIBRANT  ┆ VIBRANT_lo ┆ 2328    ┆ 2318       ┆ … ┆ 80.6      ┆ 50.9      ┆ 1.1       ┆ 0.0       │
│          ┆ w          ┆         ┆            ┆   ┆           ┆           ┆           ┆           │
└──────────┴────────────┴─────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Functional annotation agreement

Within each default / high tier-set (all three tools agreeing, pairwise, or tool-alone), do the tools that annotated the gene agree on function? Per-(tool, gene, database) we take the set of `final_annot` hit ids and call agreement when two tools' sets intersect in KEGG KOs, Pfams, or any shared database.

In [55]:
def final_hit_set_by_db(frame: pl.DataFrame, tool: str, db: str, prefix: str) -> pl.DataFrame:
    return (
        frame.filter((pl.col("tool") == tool) & (pl.col("database") == db) & pl.col("final_annot"))
             .group_by("gene", "source", "sample", "ecosystem")
             .agg([
                 pl.col("hit_id").unique().alias(f"{prefix}_{db}_ids"),
                 pl.col("hit_desc").first().alias(f"{prefix}_{db}_desc"),
             ])
    )

SHARED_DBS = ["KEGG", "Pfam"]
TOOLS_NAMES = [("CheckAMG", "CheckAMG"), ("DRAM-V", "DRAMV"), ("VIBRANT", "VIBRANT")]

In [56]:
agree_frame = members
for annot_tool, prefix in TOOLS_NAMES:
    for db in SHARED_DBS:
        agree_frame = agree_frame.join(
            final_hit_set_by_db(annotations_high_default, annot_tool, db, prefix),
            on=["gene", "sample", "source", "ecosystem"], how="left",
        )
    agree_frame = agree_frame.join(
        final_hits_per_gene(annotations_high_default, annot_tool, prefix),
        on=["gene", "sample", "source", "ecosystem"], how="left",
    )

In [57]:
TIER_SETS_DH = {
    "All tools":        pl.col("CheckAMG_high") & pl.col("DRAMV_default") & pl.col("VIBRANT_high"),
    "CheckAMG & VIBRANT": pl.col("CheckAMG_high") & pl.col("VIBRANT_high") & ~pl.col("DRAMV_default"),
    "CheckAMG & DRAM-V":   pl.col("CheckAMG_high") & pl.col("DRAMV_default") & ~pl.col("VIBRANT_high"),
    "DRAM-V & VIBRANT":    pl.col("VIBRANT_high") & pl.col("DRAMV_default") & ~pl.col("CheckAMG_high"),
    "CheckAMG only":    pl.col("CheckAMG_high") & ~pl.col("DRAMV_default") & ~pl.col("VIBRANT_high"),
    "DRAM-V only":       pl.col("DRAMV_default") & ~pl.col("CheckAMG_high") & ~pl.col("VIBRANT_high"),
    "VIBRANT only":     pl.col("VIBRANT_high") & ~pl.col("CheckAMG_high") & ~pl.col("DRAMV_default"),
}

def any_list_overlap(a: str, b: str) -> pl.Expr:
    return (
        pl.when(pl.col(a).is_null() | pl.col(b).is_null())
          .then(False)
          .otherwise(pl.col(a).list.set_intersection(pl.col(b)).list.len() > 0)
    )

def agreement_counts(frame: pl.DataFrame, tier_sets: dict) -> pl.DataFrame:
    kegg_pairs = [("CheckAMG_KEGG_ids", "DRAMV_KEGG_ids"),
                  ("CheckAMG_KEGG_ids", "VIBRANT_KEGG_ids"),
                  ("DRAMV_KEGG_ids",    "VIBRANT_KEGG_ids")]
    pfam_pairs = [("CheckAMG_Pfam_ids", "DRAMV_Pfam_ids"),
                  ("CheckAMG_Pfam_ids", "VIBRANT_Pfam_ids"),
                  ("DRAMV_Pfam_ids",    "VIBRANT_Pfam_ids")]
    any_pairs = [("CheckAMG_final_hit_ids", "DRAMV_final_hit_ids"),
                 ("CheckAMG_final_hit_ids", "VIBRANT_final_hit_ids"),
                 ("DRAMV_final_hit_ids",    "VIBRANT_final_hit_ids")]
    rows = []
    for name, expr in tier_sets.items():
        sub = frame.filter(expr)
        n = sub.height
        if n == 0:
            rows.append({"set": name, "n_genes": 0,
                         "n_any_KEGG_agree": 0, "n_any_Pfam_agree": 0, "n_any_hit_agree": 0,
                         "pct_any_KEGG_agree": 0.0, "pct_any_Pfam_agree": 0.0, "pct_any_hit_agree": 0.0})
            continue
        n_kegg = int(sub.filter(pl.any_horizontal([any_list_overlap(a, b) for a, b in kegg_pairs])).height)
        n_pfam = int(sub.filter(pl.any_horizontal([any_list_overlap(a, b) for a, b in pfam_pairs])).height)
        n_any  = int(sub.filter(pl.any_horizontal([any_list_overlap(a, b) for a, b in any_pairs])).height)
        rows.append({
            "set": name, "n_genes": n,
            "n_any_KEGG_agree": n_kegg, "n_any_Pfam_agree": n_pfam, "n_any_hit_agree": n_any,
            "pct_any_KEGG_agree": round(100 * n_kegg / n, 2),
            "pct_any_Pfam_agree": round(100 * n_pfam / n, 2),
            "pct_any_hit_agree":  round(100 * n_any  / n, 2),
        })
    return pl.DataFrame(rows)

In [58]:
agreement_df = agreement_counts(agree_frame, TIER_SETS_DH)

In [59]:
agreement_df

shape: (7, 8)
┌────────────┬─────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ set        ┆ n_genes ┆ n_any_KEGG ┆ n_any_Pfam ┆ n_any_hit_ ┆ pct_any_KE ┆ pct_any_P ┆ pct_any_h │
│ ---        ┆ ---     ┆ _agree     ┆ _agree     ┆ agree      ┆ GG_agree   ┆ fam_agree ┆ it_agree  │
│ str        ┆ i64     ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│            ┆         ┆ i64        ┆ i64        ┆ i64        ┆ f64        ┆ f64       ┆ f64       │
╞════════════╪═════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ All tools  ┆ 0       ┆ 0          ┆ 0          ┆ 0          ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ CheckAMG & ┆ 221     ┆ 175        ┆ 173        ┆ 216        ┆ 79.19      ┆ 78.28     ┆ 97.74     │
│ VIBRANT    ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│ CheckAMG & ┆ 0       ┆ 0          ┆ 0          ┆ 0          ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ DRAM-V     ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│ DRAM-V &   ┆ 0       ┆ 0          ┆ 0          ┆ 0          ┆ 0.0        ┆ 0.0       ┆ 0.0       │
│ VIBRANT    ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│ CheckAMG   ┆ 2997    ┆ 813        ┆ 1121       ┆ 1347       ┆ 27.13      ┆ 37.4      ┆ 44.94     │
│ only       ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│ DRAM-V     ┆ 664     ┆ 6          ┆ 5          ┆ 8          ┆ 0.9        ┆ 0.75      ┆ 1.2       │
│ only       ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│ VIBRANT    ┆ 1049    ┆ 458        ┆ 561        ┆ 659        ┆ 43.66      ┆ 53.48     ┆ 62.82     │
│ only       ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
└────────────┴─────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘

## Reference-database heterogeneity

Each tool calls AMGs only from its own curated list of gene identifiers. CheckAMG requires an AMG weight of at least 0.6 by default. The weight reflects the share of metabolic pathways an HMM is associated with and its VL-score, so it can also be matched to many of the other tools' AMG identifiers.

In [60]:
CHECKAMG_DEFAULT_WEIGHT = 0.6

def strip_pfam_version(expr: pl.Expr) -> pl.Expr:
    return expr.cast(pl.Utf8).str.split(".").list.first()

In [61]:
amgs = pl.read_csv("../CheckAMG/files/AMGs.tsv", separator="\t")
amg_filters = pl.read_csv("../CheckAMG/files/AMG_filters.tsv", separator="\t")
amg_database = pl.read_csv("./data/amg_database.tsv", separator="\t")
vibrant_amgs = (
    pl.read_csv("./data/VIBRANT_AMGs.tsv", separator="\t", has_header=False, new_columns=["ko"])
      .filter(pl.col("ko") != "KO").unique()
)

In [62]:
print(f"AMGs.tsv: {amgs.height:,}")
print(f"AMG_filters.tsv: {amg_filters.height:,}")
print(f"amg_database.tsv (DRAM-V): {amg_database.height:,}")
print(f"VIBRANT_AMGs.tsv: {vibrant_amgs.height:,}")

AMGs.tsv: 60,770
AMG_filters.tsv: 38,768
amg_database.tsv (DRAM-V): 279
VIBRANT_AMGs.tsv: 2,826

In [63]:
dramv_ko = amg_database.filter(pl.col("KO").is_not_null()).select(pl.col("KO").alias("ko")).unique()
dramv_pfam = (
    amg_database.filter(pl.col("PFAM").is_not_null())
                .select(pl.col("PFAM").str.split("; ").alias("pfam_list"))
                .explode("pfam_list")
                .with_columns(strip_pfam_version(pl.col("pfam_list")).alias("pfam"))
                .filter(pl.col("pfam").str.starts_with("PF"))
                .select("pfam").unique()
)

# Sorted because unique() does not preserve order, which reordered the appended database columns on every run
checkamg_dbs = sorted(amgs.select(pl.col("db")).filter(pl.col("db").is_not_null()).unique()["db"].to_list())
amg_super = (
    pl.concat([
        dramv_pfam.rename({"pfam": "HMM"}),
        dramv_ko.rename({"ko": "HMM"}),
        vibrant_amgs.rename({"ko": "HMM"}),
        (
            amgs
            .select("id")
            .with_columns(strip_pfam_version(pl.col("id")).alias("id"))
            .rename({"id": "HMM"})
        )
    ])
    .with_columns([
        pl.when(
            pl.col("HMM")
            .is_in(
                amgs
                .filter(pl.col("db")==db)
                .select("id")
                .with_columns(strip_pfam_version(pl.col("id")).alias("id"))
                ["id"].to_list()
            )
        )
        .then(pl.lit(True))
        .otherwise(pl.lit(False))
        .alias(db)
        for db in checkamg_dbs
    ])
    .with_columns([
        pl.when(pl.col("HMM").is_in(dramv_pfam["pfam"].to_list()))
        .then(pl.lit(True))
        .otherwise(pl.col("Pfam"))
        .alias("Pfam"),
        pl.when((pl.col("HMM").is_in(dramv_ko["ko"].to_list())) | (pl.col("HMM").is_in(vibrant_amgs["ko"].to_list())))
        .then(pl.lit(True))
        .otherwise(pl.col("KEGG"))
        .alias("KEGG"),
    ])
    .filter(pl.col("HMM").is_not_null())
    .unique()
    .sort("HMM")
)
amg_super

shape: (60_855, 7)
┌────────────────────────────────────┬────────┬───────┬───────┬───────────┬───────┬───────┐
│ HMM                                ┆ CAMPER ┆ FOAM  ┆ KEGG  ┆ METABOLIC ┆ Pfam  ┆ dbCAN │
│ ---                                ┆ ---    ┆ ---   ┆ ---   ┆ ---       ┆ ---   ┆ ---   │
│ str                                ┆ bool   ┆ bool  ┆ bool  ┆ bool      ┆ bool  ┆ bool  │
╞════════════════════════════════════╪════════╪═══════╪═══════╪═══════════╪═══════╪═══════╡
│ AA1                                ┆ true   ┆ false ┆ false ┆ false     ┆ false ┆ true  │
│ AA10                               ┆ false  ┆ false ┆ false ┆ false     ┆ false ┆ true  │
│ AA13                               ┆ false  ┆ false ┆ false ┆ false     ┆ false ┆ true  │
│ AA14                               ┆ false  ┆ false ┆ false ┆ false     ┆ false ┆ true  │
│ AA15                               ┆ false  ┆ false ┆ false ┆ false     ┆ false ┆ true  │
│ …                                  ┆ …      ┆ …     ┆ …     ┆ …         ┆ …     ┆ …     │
│ soxZ                               ┆ false  ┆ false ┆ false ┆ true      ┆ false ┆ false │
│ sulfide_quinone_oxidoreductase_sqr ┆ false  ┆ false ┆ false ┆ true      ┆ false ┆ false │
│ sulfocyanin                        ┆ false  ┆ false ┆ false ┆ true      ┆ false ┆ false │
│ sulfur_dioxygenase_sdo             ┆ false  ┆ false ┆ false ┆ true      ┆ false ┆ false │
│ thiosulfate_reductase_phsA         ┆ false  ┆ false ┆ false ┆ true      ┆ false ┆ false │
└────────────────────────────────────┴────────┴───────┴───────┴───────────┴───────┴───────┘

In [64]:
upset_amg_ref_combined = (
    amg_super
    .with_columns([
        pl.when(
            pl.col("HMM").is_in(
                amgs
                .filter(pl.col("AMG_weight")>=CHECKAMG_DEFAULT_WEIGHT)
                .with_columns(strip_pfam_version(pl.col("id")).alias("id"))["id"].to_list()
            )
        )
        .then(pl.lit(True))
        .otherwise(pl.lit(False))
        .alias(f"CheckAMG (AMG weight >= {CHECKAMG_DEFAULT_WEIGHT})"),

        pl.when(
            pl.col("HMM").is_in(
                amgs
                .with_columns(strip_pfam_version(pl.col("id")).alias("id"))["id"].to_list()
            )
        )
        .then(pl.lit(True))
        .otherwise(pl.lit(False))
        .alias("CheckAMG (all)"),

        pl.when((pl.col("HMM").is_in(dramv_pfam["pfam"].to_list())) | (pl.col("HMM").is_in(dramv_ko["ko"].to_list())))
        .then(pl.lit(True))
        .otherwise(pl.lit(False))
        .alias("DRAMV"),

        pl.when(pl.col("HMM").is_in(vibrant_amgs["ko"].to_list()))
        .then(pl.lit(True))
        .otherwise(pl.lit(False))
        .alias("VIBRANT")
    ])
)
upset_amg_ref_combined

shape: (60_855, 11)
┌─────────────────┬────────┬───────┬───────┬───┬────────────────┬────────────────┬───────┬─────────┐
│ HMM             ┆ CAMPER ┆ FOAM  ┆ KEGG  ┆ … ┆ CheckAMG (AMG  ┆ CheckAMG (all) ┆ DRAMV ┆ VIBRANT │
│ ---             ┆ ---    ┆ ---   ┆ ---   ┆   ┆ weight >= 0.6) ┆ ---            ┆ ---   ┆ ---     │
│ str             ┆ bool   ┆ bool  ┆ bool  ┆   ┆ ---            ┆ bool           ┆ bool  ┆ bool    │
│                 ┆        ┆       ┆       ┆   ┆ bool           ┆                ┆       ┆         │
╞═════════════════╪════════╪═══════╪═══════╪═══╪════════════════╪════════════════╪═══════╪═════════╡
│ AA1             ┆ true   ┆ false ┆ false ┆ … ┆ true           ┆ true           ┆ false ┆ false   │
│ AA10            ┆ false  ┆ false ┆ false ┆ … ┆ true           ┆ true           ┆ false ┆ false   │
│ AA13            ┆ false  ┆ false ┆ false ┆ … ┆ true           ┆ true           ┆ false ┆ false   │
│ AA14            ┆ false  ┆ false ┆ false ┆ … ┆ true           ┆ true           ┆ false ┆ false   │
│ AA15            ┆ false  ┆ false ┆ false ┆ … ┆ true           ┆ true           ┆ false ┆ false   │
│ …               ┆ …      ┆ …     ┆ …     ┆ … ┆ …              ┆ …              ┆ …     ┆ …       │
│ soxZ            ┆ false  ┆ false ┆ false ┆ … ┆ true           ┆ true           ┆ false ┆ false   │
│ sulfide_quinone ┆ false  ┆ false ┆ false ┆ … ┆ true           ┆ true           ┆ false ┆ false   │
│ _oxidoreductase ┆        ┆       ┆       ┆   ┆                ┆                ┆       ┆         │
│ _sqr            ┆        ┆       ┆       ┆   ┆                ┆                ┆       ┆         │
│ sulfocyanin     ┆ false  ┆ false ┆ false ┆ … ┆ true           ┆ true           ┆ false ┆ false   │
│ sulfur_dioxygen ┆ false  ┆ false ┆ false ┆ … ┆ true           ┆ true           ┆ false ┆ false   │
│ ase_sdo         ┆        ┆       ┆       ┆   ┆                ┆                ┆       ┆         │
│ thiosulfate_red ┆ false  ┆ false ┆ false ┆ … ┆ true           ┆ true           ┆ false ┆ false   │
│ uctase_phsA     ┆        ┆       ┆       ┆   ┆                ┆                ┆       ┆         │
└─────────────────┴────────┴───────┴───────┴───┴────────────────┴────────────────┴───────┴─────────┘

In [65]:
ref_summary = pl.DataFrame([
    {"tool": "CheckAMG", "space": "KO",   "level": "any AMG weight",   "n": upset_amg_ref_combined.filter((pl.col("CheckAMG (all)")) & (pl.col("KEGG"))).height},
    {"tool": "CheckAMG", "space": "KO",   "level": f"AMG weight >= {CHECKAMG_DEFAULT_WEIGHT}", "n": upset_amg_ref_combined.filter((pl.col(f"CheckAMG (AMG weight >= {CHECKAMG_DEFAULT_WEIGHT})")) & (pl.col("KEGG"))).height},
    {"tool": "CheckAMG", "space": "Pfam", "level": "any AMG weight",   "n": upset_amg_ref_combined.filter((pl.col("CheckAMG (all)")) & (pl.col("Pfam"))).height},
    {"tool": "CheckAMG", "space": "Pfam", "level": f"AMG weight >= {CHECKAMG_DEFAULT_WEIGHT}", "n": upset_amg_ref_combined.filter((pl.col(f"CheckAMG (AMG weight >= {CHECKAMG_DEFAULT_WEIGHT})")) & (pl.col("Pfam"))).height},
    {"tool": "CheckAMG", "space": "all",  "level": "any AMG weight",   "n": upset_amg_ref_combined.filter((pl.col("CheckAMG (all)"))).height},
    {"tool": "CheckAMG", "space": "all",  "level": f"AMG weight >= {CHECKAMG_DEFAULT_WEIGHT}", "n": int(upset_amg_ref_combined.filter(pl.col(f"CheckAMG (AMG weight >= {CHECKAMG_DEFAULT_WEIGHT})")).height)},
    {"tool": "DRAMV",    "space": "KO",   "level": "curated",          "n": upset_amg_ref_combined.filter((pl.col("DRAMV")) & (pl.col("KEGG"))).height},
    {"tool": "DRAMV",    "space": "Pfam", "level": "curated",          "n": upset_amg_ref_combined.filter((pl.col("DRAMV")) & (pl.col("Pfam"))).height},
    {"tool": "VIBRANT",  "space": "KO",   "level": "curated",          "n": upset_amg_ref_combined.filter((pl.col("VIBRANT")) & (pl.col("KEGG"))).height},
])

In [66]:
ref_summary

shape: (9, 4)
┌──────────┬───────┬───────────────────┬───────┐
│ tool     ┆ space ┆ level             ┆ n     │
│ ---      ┆ ---   ┆ ---               ┆ ---   │
│ str      ┆ str   ┆ str               ┆ i64   │
╞══════════╪═══════╪═══════════════════╪═══════╡
│ CheckAMG ┆ KO    ┆ any AMG weight    ┆ 10055 │
│ CheckAMG ┆ KO    ┆ AMG weight >= 0.6 ┆ 8633  │
│ CheckAMG ┆ Pfam  ┆ any AMG weight    ┆ 1611  │
│ CheckAMG ┆ Pfam  ┆ AMG weight >= 0.6 ┆ 1069  │
│ CheckAMG ┆ all   ┆ any AMG weight    ┆ 60311 │
│ CheckAMG ┆ all   ┆ AMG weight >= 0.6 ┆ 55999 │
│ DRAMV    ┆ KO    ┆ curated           ┆ 34    │
│ DRAMV    ┆ Pfam  ┆ curated           ┆ 251   │
│ VIBRANT  ┆ KO    ┆ curated           ┆ 2826  │
└──────────┴───────┴───────────────────┴───────┘

Some HMMs occur in multiple databases (e.g., CAZymes and KOs in both dbCAN and CAMPER, Pfams in both Pfam and METABOLIC, etc.), which means that they sometimes appear in CheckAMG's database more than once. This is why the number of *unique* HMMs in the entire CheckAMG AMG reference is less than the number of HMMs (rows) in the CheckAMG reference AMG table.

In [67]:
upset_amg_ref_combined.write_csv(OUTPUT_TABLES_DIR.joinpath("AMG_reference_overlap_combined.tsv"), separator="\t")

### CheckAMG AMG weight distribution per database

In [68]:
checkamg_amg_weights_by_db = (
    amgs.with_columns(
        pl.when(pl.col("AMG_weight") >= 0.8).then(pl.lit("very_high"))
          .when(pl.col("AMG_weight") >= 0.6).then(pl.lit("high"))
          .when(pl.col("AMG_weight") >= 0.4).then(pl.lit("medium"))
          .when(pl.col("AMG_weight") >= 0.2).then(pl.lit("low"))
          .otherwise(pl.lit("very_low"))
          .alias("bin")
    )
    .group_by(["db", "bin"]).agg(pl.len().alias("n"))
    .sort(["db", "bin"])
)

In [69]:
with pl.Config(tbl_rows=100, tbl_width_chars=500):
    print(checkamg_amg_weights_by_db)

shape: (29, 3)
┌───────────┬───────────┬───────┐
│ db        ┆ bin       ┆ n     │
│ ---       ┆ ---       ┆ ---   │
│ str       ┆ str       ┆ u64   │
╞═══════════╪═══════════╪═══════╡
│ null      ┆ medium    ┆ 1     │
│ null      ┆ very_high ┆ 56    │
│ CAMPER    ┆ high      ┆ 51    │
│ CAMPER    ┆ medium    ┆ 1     │
│ CAMPER    ┆ very_high ┆ 227   │
│ FOAM      ┆ high      ┆ 21099 │
│ FOAM      ┆ low       ┆ 116   │
│ FOAM      ┆ medium    ┆ 1939  │
│ FOAM      ┆ very_high ┆ 24957 │
│ FOAM      ┆ very_low  ┆ 13    │
│ KEGG      ┆ high      ┆ 1759  │
│ KEGG      ┆ low       ┆ 445   │
│ KEGG      ┆ medium    ┆ 906   │
│ KEGG      ┆ very_high ┆ 6874  │
│ KEGG      ┆ very_low  ┆ 71    │
│ METABOLIC ┆ high      ┆ 44    │
│ METABOLIC ┆ low       ┆ 3     │
│ METABOLIC ┆ medium    ┆ 20    │
│ METABOLIC ┆ very_high ┆ 230   │
│ METABOLIC ┆ very_low  ┆ 1     │
│ Pfam      ┆ high      ┆ 154   │
│ Pfam      ┆ low       ┆ 138   │
│ Pfam      ┆ medium    ┆ 404   │
│ Pfam      ┆ very_high ┆ 915   │
│ dbCAN     ┆ high      ┆ 3     │
│ dbCAN     ┆ low       ┆ 211   │
│ dbCAN     ┆ medium    ┆ 16    │
│ dbCAN     ┆ very_high ┆ 71    │
│ dbCAN     ┆ very_low  ┆ 45    │
└───────────┴───────────┴───────┘

## Likely AMG vs weak AMG per call

For every AMG-called gene, look up each tool's own `final_annot` hit ids in CheckAMG's `AMGs.tsv` reference and use the associated `AMG_weight` as a continuous, tool-agnostic rubric. The per-gene best weight is the MAX `AMG_weight` across the tool's final hits. The CheckAMG `AMG_filters.tsv` categories (essential / glucan / lipid / methyl / nucleotide) are also OR-aggregated across the tool's final hits and reported separately. They are reported rather than used as a filter, because nucleotide-metabolism genes with `AMG_weight >= 0.8`, for example, are still likely AMGs.

In [70]:
FILTER_CATEGORIES = ["filter_essential", "filter_glucan", "filter_lipid", "filter_methyl", "filter_nucleotide"]
CHECKAMG_HIGH_WEIGHT = 0.8
CHECKAMG_LOW_WEIGHT  = 0.4

WEIGHT_BIN_ORDER = [
    "weight_ge_0.8", "weight_0.6_0.8", "weight_0.4_0.6", "weight_lt_0.4",
    "no_reference", "no_annotation", "not_called",
]
CATEGORY_ORDER = ["methyl", "nucleotide", "glucan", "lipid", "essential", "none"]

Reference tables reduced to (db, id_key) lookups, with Pfam versions stripped.

In [71]:
amgs_slim = (
    amgs.with_columns(
        pl.when(pl.col("db") == "Pfam")
          .then(pl.col("id").str.split(".").list.first())
          .otherwise(pl.col("id"))
          .alias("id_key")
    )
    .group_by(["db", "id_key"])
    .agg([pl.col("AMG_weight").max().alias("AMG_weight"), pl.col("amg_level").first().alias("amg_level")])
)
filters_slim = (
    amg_filters.with_columns(
        pl.when(pl.col("db") == "Pfam")
          .then(pl.col("id").str.split(".").list.first())
          .otherwise(pl.col("id"))
          .alias("id_key")
    )
    .group_by(["db", "id_key"])
    .agg([pl.col(c).any().alias(c) for c in FILTER_CATEGORIES])
)

Attach the reference weight and filter flags to every final annotation, then collapse to one row per tool and gene, taking the maximum weight and OR-ing the filter flags.

In [72]:
final_annots = (
    annotations_high_default.filter(pl.col("final_annot"))
    .with_columns(
        pl.when(pl.col("database") == "Pfam")
          .then(pl.col("hit_id").str.split(".").list.first())
          .otherwise(pl.col("hit_id"))
          .alias("id_key"),
    )
    .join(amgs_slim, left_on=["database", "id_key"], right_on=["db", "id_key"], how="left")
    .join(filters_slim, left_on=["database", "id_key"], right_on=["db", "id_key"], how="left")
    .with_columns([pl.col(c).fill_null(False) for c in FILTER_CATEGORIES])
)

per_tool_gene = (
    final_annots.group_by(["sample", "source", "ecosystem", "tool", "gene"])
    .agg([
        pl.col("AMG_weight").max().alias("best_AMG_weight"),
        pl.col("AMG_weight").is_not_null().any().alias("in_amg_ref"),
        pl.col("hit_id").is_not_null().any().alias("has_hit"),
    ] + [pl.col(c).any().alias(c) for c in FILTER_CATEGORIES])
    .with_columns([
        pl.when(~pl.col("has_hit"))
          .then(pl.lit("no_annotation"))
          .when(~pl.col("in_amg_ref"))
          .then(pl.lit("no_reference"))
          .when(pl.col("best_AMG_weight") >= CHECKAMG_HIGH_WEIGHT).then(pl.lit("weight_ge_0.8"))
          .when(pl.col("best_AMG_weight") >= CHECKAMG_DEFAULT_WEIGHT).then(pl.lit("weight_0.6_0.8"))
          .when(pl.col("best_AMG_weight") >= CHECKAMG_LOW_WEIGHT).then(pl.lit("weight_0.4_0.6"))
          .otherwise(pl.lit("weight_lt_0.4"))
          .alias("weight_bin"),
        pl.when(pl.col("filter_essential")).then(pl.lit("essential"))
          .when(pl.col("filter_nucleotide")).then(pl.lit("nucleotide"))
          .when(pl.col("filter_glucan")).then(pl.lit("glucan"))
          .when(pl.col("filter_lipid")).then(pl.lit("lipid"))
          .when(pl.col("filter_methyl")).then(pl.lit("methyl"))
          .otherwise(pl.lit("none"))
          .alias("dominant_category"),
    ])
)

In [73]:
per_tool_gene

shape: (11_154, 15)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ sample    ┆ source    ┆ ecosystem ┆ tool     ┆ … ┆ filter_me ┆ filter_nu ┆ weight_bi ┆ dominant_ │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ thyl      ┆ cleotide  ┆ n         ┆ category  │
│ str       ┆ str       ┆ str       ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆           ┆           ┆          ┆   ┆ bool      ┆ bool      ┆ str       ┆ str       │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ soil_T42_ ┆ Mixed met ┆ Soil      ┆ CheckAMG ┆ … ┆ true      ┆ false     ┆ weight_0. ┆ methyl    │
│ 15_2_56   ┆ agenomes  ┆           ┆          ┆   ┆           ┆           ┆ 6_0.8     ┆           │
│ soil_T42_ ┆ Mixed met ┆ Soil      ┆ CheckAMG ┆ … ┆ true      ┆ false     ┆ weight_0. ┆ methyl    │
│ 15_3_57   ┆ agenomes  ┆           ┆          ┆   ┆           ┆           ┆ 6_0.8     ┆           │
│ virus_gen ┆ Viral     ┆ Human gut ┆ CheckAMG ┆ … ┆ false     ┆ false     ┆ no_refere ┆ essential │
│ omes_gut  ┆ genomes   ┆           ┆          ┆   ┆           ┆           ┆ nce       ┆           │
│ soil_T42_ ┆ Mixed met ┆ Soil      ┆ CheckAMG ┆ … ┆ false     ┆ false     ┆ weight_ge ┆ none      │
│ 15_3_57   ┆ agenomes  ┆           ┆          ┆   ┆           ┆           ┆ _0.8      ┆           │
│ freshwate ┆ Mixed met ┆ Aquatic   ┆ CheckAMG ┆ … ┆ false     ┆ true      ┆ no_refere ┆ nucleotid │
│ r_Ga04851 ┆ agenomes  ┆           ┆          ┆   ┆           ┆           ┆ nce       ┆ e         │
│ 59_contig ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ s         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ virus_gen ┆ Viral     ┆ Soil      ┆ CheckAMG ┆ … ┆ true      ┆ true      ┆ weight_0. ┆ essential │
│ omes_soil ┆ genomes   ┆           ┆          ┆   ┆           ┆           ┆ 4_0.6     ┆           │
│ freshwate ┆ Viromes   ┆ Aquatic   ┆ DRAM-V   ┆ … ┆ false     ┆ false     ┆ weight_0. ┆ none      │
│ r_Ga04851 ┆           ┆           ┆          ┆   ┆           ┆           ┆ 4_0.6     ┆           │
│ 75_contig ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ s         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ freshwate ┆ Viromes   ┆ Aquatic   ┆ VIBRANT  ┆ … ┆ false     ┆ true      ┆ weight_0. ┆ nucleotid │
│ r_Ga04851 ┆           ┆           ┆          ┆   ┆           ┆           ┆ 4_0.6     ┆ e         │
│ 74_contig ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ s         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ human_gut ┆ Viromes   ┆ Human gut ┆ DRAM-V   ┆ … ┆ false     ┆ true      ┆ no_refere ┆ nucleotid │
│ _SRR91615 ┆           ┆           ┆          ┆   ┆           ┆           ┆ nce       ┆ e         │
│ 09_contig ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ s         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ freshwate ┆ Viromes   ┆ Aquatic   ┆ CheckAMG ┆ … ┆ true      ┆ true      ┆ weight_0. ┆ nucleotid │
│ r_Ga04851 ┆           ┆           ┆          ┆   ┆           ┆           ┆ 6_0.8     ┆ e         │
│ 74_contig ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ s         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

Pivot to one row per gene, with weight bin, dominant category, and filter flags for each tool.

In [74]:
tool_keys = [("CheckAMG", "CheckAMG"), ("DRAM-V", "DRAMV"), ("VIBRANT", "VIBRANT")]
members_weights = members_annot
for annot_tool, prefix in tool_keys:
    tf = (
        per_tool_gene.filter(pl.col("tool") == annot_tool).drop("tool")
                     .rename({c: f"{prefix}_{c}" for c in per_tool_gene.columns if c not in ("tool", "gene", "source", "sample", "ecosystem")})
    )
    members_weights = members_weights.join(tf, on=["gene", "sample", "source", "ecosystem"], how="left")

for _, prefix in tool_keys:
    members_weights = members_weights.with_columns([
        pl.col(f"{prefix}_weight_bin").fill_null("not_called"),
        pl.col(f"{prefix}_dominant_category").fill_null("none"),
    ] + [pl.col(f"{prefix}_{c}").fill_null(False) for c in FILTER_CATEGORIES])

AMG weights and categories for each gene, annotation, and tool.

In [75]:
amg_predictions_categorized = (
    per_tool_gene
    .select([
        "gene", "source", "sample", "ecosystem", "tool",
    ])
    .join(
        annotations,
        on=["source", "sample", "ecosystem", "gene", "tool"],
        how="left"
    )
    .filter(pl.col("final_annot")) # restrict to final annotations reported by each tool
    .join(
        amgs_slim,
        left_on=["database", "hit_id"],
        right_on=["db", "id_key"],
        how="left",
    )
    .join(
        filters_slim,
        left_on=["database", "hit_id"],
        right_on=["db", "id_key"],
        how="left",
    )
    .join(
        members,
        on=["source", "sample", "ecosystem", "gene"],
        how="left",
    )
    .with_columns(
        pl.any_horizontal(
            pl.col("filter_essential").is_not_null(),
            pl.col("filter_glucan").is_not_null(),
            pl.col("filter_lipid").is_not_null(),
            pl.col("filter_methyl").is_not_null(),
            pl.col("filter_nucleotide").is_not_null(),
        ).alias("has_filter")
    )
    .sort(
        ["tool",  "gene", "has_filter"],
        descending=[False, False, True],
    )
    .drop("has_filter")
)

In [76]:
amg_predictions_categorized

shape: (37_247, 45)
┌──────────────┬─────────────┬─────────────┬───────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ gene         ┆ source      ┆ sample      ┆ ecosystem ┆ … ┆ DRAMV_A ┆ DRAMV_P ┆ DRAMV_B ┆ DRAMV_F │
│ ---          ┆ ---         ┆ ---         ┆ ---       ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ str          ┆ str         ┆ str         ┆ str       ┆   ┆ bool    ┆ bool    ┆ bool    ┆ bool    │
╞══════════════╪═════════════╪═════════════╪═══════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ Ga0485157_00 ┆ Mixed       ┆ freshwater_ ┆ Aquatic   ┆ … ┆ false   ┆ false   ┆ false   ┆ false   │
│ 00020_8      ┆ metagenomes ┆ Ga0485157_c ┆           ┆   ┆         ┆         ┆         ┆         │
│              ┆             ┆ ontigs      ┆           ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_00 ┆ Mixed       ┆ freshwater_ ┆ Aquatic   ┆ … ┆ false   ┆ false   ┆ false   ┆ false   │
│ 00020_8      ┆ metagenomes ┆ Ga0485157_c ┆           ┆   ┆         ┆         ┆         ┆         │
│              ┆             ┆ ontigs      ┆           ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_00 ┆ Mixed       ┆ freshwater_ ┆ Aquatic   ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 00095_62     ┆ metagenomes ┆ Ga0485157_c ┆           ┆   ┆         ┆         ┆         ┆         │
│              ┆             ┆ ontigs      ┆           ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_00 ┆ Mixed       ┆ freshwater_ ┆ Aquatic   ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 00095_62     ┆ metagenomes ┆ Ga0485157_c ┆           ┆   ┆         ┆         ┆         ┆         │
│              ┆             ┆ ontigs      ┆           ┆   ┆         ┆         ┆         ┆         │
│ Ga0485157_00 ┆ Mixed       ┆ freshwater_ ┆ Aquatic   ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 00095_62     ┆ metagenomes ┆ Ga0485157_c ┆           ┆   ┆         ┆         ┆         ┆         │
│              ┆             ┆ ontigs      ┆           ┆   ┆         ┆         ┆         ┆         │
│ …            ┆ …           ┆ …           ┆ …         ┆ … ┆ …       ┆ …       ┆ …       ┆ …       │
│ scaffold_9_c ┆ Mixed       ┆ soil_T42_15 ┆ Soil      ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 1_92         ┆ metagenomes ┆ _3_57       ┆           ┆   ┆         ┆         ┆         ┆         │
│ scaffold_9_c ┆ Mixed       ┆ soil_T42_15 ┆ Soil      ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 1_92         ┆ metagenomes ┆ _3_57       ┆           ┆   ┆         ┆         ┆         ┆         │
│ scaffold_9_c ┆ Mixed       ┆ soil_T42_15 ┆ Soil      ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 1_98         ┆ metagenomes ┆ _2_56       ┆           ┆   ┆         ┆         ┆         ┆         │
│ scaffold_9_c ┆ Mixed       ┆ soil_T42_15 ┆ Soil      ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 1_98         ┆ metagenomes ┆ _2_56       ┆           ┆   ┆         ┆         ┆         ┆         │
│ scaffold_9_c ┆ Mixed       ┆ soil_T42_15 ┆ Soil      ┆ … ┆ false   ┆ false   ┆ true    ┆ false   │
│ 1_99         ┆ metagenomes ┆ _3_57       ┆           ┆   ┆         ┆         ┆         ┆         │
└──────────────┴─────────────┴─────────────┴───────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [77]:
amg_predictions_categorized.write_csv(OUTPUT_TABLES_DIR.joinpath("AMG_annotations_categorized.tsv"), separator="\t")

### Top functions per tier-set

In [78]:
GENE_KEY_TF = ["gene", "sample", "source", "ecosystem"]


def _normalize_tool(name: str) -> str:
    return name.strip().replace("-", "").upper()

_TOOL_NORM_MAP = {
    _normalize_tool("CheckAMG"): "CheckAMG",
    _normalize_tool("DRAMV"):    "DRAM-V",
    _normalize_tool("VIBRANT"):  "VIBRANT",
}

def _tools_from_label(set_label: str) -> list[str]:
    """
    Extract normalized tool column values from a set label.
    'CheckAMG only'        -> ['CheckAMG']
    'CheckAMG & VIBRANT'   -> ['CheckAMG', 'VIBRANT']
    'DRAM-V & VIBRANT'     -> ['DRAMV', 'VIBRANT']
    'All tools'            -> []  (no tool filter)
    """
    label = set_label.replace(" only", "")
    if "&" in label:
        parts = [t.strip() for t in label.split("&")]
    elif label.strip() == "All tools":
        return []
    else:
        parts = [label.strip()]
    return [_TOOL_NORM_MAP[_normalize_tool(p)] for p in parts if _normalize_tool(p) in _TOOL_NORM_MAP]

def _best_hit_per_gene(
    sub: pl.DataFrame,
    tool_values: list[str],
) -> pl.DataFrame:
    valid = sub.filter(
        pl.col("hit_desc").is_not_null()
        & (pl.col("hit_desc").str.strip_chars() != "")
    )

    def _pick_best(df: pl.DataFrame) -> pl.DataFrame:
        # Best hit: highest AMG_weight, then bitscore and e-value, with hit_id and the longer description as reproducible tie-breaks
        # Tool is not a sort key because alphabetical order would resolve every tie in CheckAMG's favor
        # The key is the four gene-identifying columns, since a gene name repeats across samples.
        df = df.with_columns(pl.col("hit_desc").str.len_chars().alias("_desc_len"))
        has_weight = df.filter(pl.col("AMG_weight").is_not_null())
        genes_with_weight = has_weight.select(GENE_KEY_TF).unique()
        without_weight = df.join(genes_with_weight, on=GENE_KEY_TF, how="anti")
        return pl.concat([
            has_weight.sort(["AMG_weight", "bitscore", "evalue", "hit_id", "_desc_len", "hit_desc"],
                            descending=[True, True, False, False, True, False], maintain_order=True)
                    .unique(subset=GENE_KEY_TF, keep="first", maintain_order=True),
            without_weight.sort(["bitscore", "evalue", "hit_id", "_desc_len", "hit_desc"],
                                descending=[True, False, False, True, False], maintain_order=True)
                        .unique(subset=GENE_KEY_TF, keep="first", maintain_order=True),
        ]).select(GENE_KEY_TF + ["hit_id", "hit_desc", "bitscore", "evalue"])

    if len(tool_values) < 2:
        pool = valid.filter(pl.col("tool").is_in(tool_values)) if tool_values else valid
        return _pick_best(pool)

    per_tool_hits = [
        valid.filter(pl.col("tool") == tv).select(GENE_KEY_TF + ["hit_id"]).unique()
        for tv in tool_values
    ]
    shared = per_tool_hits[0]
    for other in per_tool_hits[1:]:
        shared = shared.join(other, on=GENE_KEY_TF + ["hit_id"], how="inner")

    if shared.height > 0:
        shared_rows = _pick_best(valid.join(shared, on=GENE_KEY_TF + ["hit_id"], how="inner"))
    else:
        shared_rows = pl.DataFrame(
            {c: [] for c in GENE_KEY_TF + ["hit_id", "hit_desc", "bitscore", "evalue"]},
            schema={
                **{c: pl.Utf8 for c in GENE_KEY_TF},
                "hit_id": pl.Utf8,
                "hit_desc": pl.Utf8,
                "bitscore": pl.Float64,
                "evalue": pl.Float64,
            }
        )

    fallback_rows = _pick_best(
        valid
        .filter(pl.col("tool").is_in(tool_values))
        .join(shared_rows.select(GENE_KEY_TF), on=GENE_KEY_TF, how="anti")
    )

    return pl.concat([shared_rows, fallback_rows])

def hit_set_composition(
    amg_predictions_categorizes: pl.DataFrame,
    tier_sets: dict[str, pl.Expr],
) -> pl.DataFrame:
    dfs = []
    for set_label, set_expr in tier_sets.items():
        label_tools = _tools_from_label(set_label)
        tool_values = [_TOOL_NORM_MAP[_normalize_tool(t)] for t in label_tools
                       if _normalize_tool(t) in _TOOL_NORM_MAP]

        sub = amg_predictions_categorizes.filter(set_expr)
        best_per_gene = _best_hit_per_gene(sub, tool_values)

        if best_per_gene.height == 0:
            continue

        agg = (
            best_per_gene
            .group_by("hit_id")
            .agg([
                pl.concat_str(GENE_KEY_TF, separator="\x1f").n_unique().alias("n"),
                # The representative description follows the same rule as the row selection
                pl.col("hit_desc").sort_by([pl.col("hit_desc").str.len_chars(), pl.col("hit_desc")],
                                           descending=[True, False]).first().alias("hit_desc"),
                pl.col("bitscore").median().alias("median_bitscore"),
                pl.col("evalue").median().alias("median_evalue"),
            ])
            .with_columns(pl.lit(set_label).alias("set"))
        )
        dfs.append(agg)

    return (
        pl.concat(dfs)
        .select(["hit_id", "hit_desc", "n", "median_bitscore", "median_evalue", "set"])
        .sort(["n", "set", "hit_id"], descending=[True, False, False])
    )

In [79]:
hits_set_comp = hit_set_composition(amg_predictions_categorized, TIER_SETS_DH)

In [80]:
with pl.Config(tbl_rows=100, tbl_width_chars=500):
    print(hits_set_comp)

shape: (694, 6)
┌───────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────┬─────┬─────────────────┬───────────────┬────────────────────┐
│ hit_id        ┆ hit_desc                                                                                              ┆ n   ┆ median_bitscore ┆ median_evalue ┆ set                │
│ ---           ┆ ---                                                                                                   ┆ --- ┆ ---             ┆ ---           ┆ ---                │
│ str           ┆ str                                                                                                   ┆ u64 ┆ f64             ┆ f64           ┆ str                │
╞═══════════════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════╪═════╪═════════════════╪═══════════════╪════════════════════╡
│ K07336        ┆ K07336; PKHD-type hydroxylase [EC:1.14.11.-]                                                          ┆ 281 ┆ 108.500824      ┆ 8.1426e-30    ┆ CheckAMG only      │
│ PF00145       ┆ C-5 cytosine-specific DNA methylase                                                                   ┆ 238 ┆ 110.25          ┆ 4.1000e-32    ┆ VIBRANT only       │
│ K01495        ┆ GCH1, folE; GTP cyclohydrolase IA [EC:3.5.4.16]                                                       ┆ 229 ┆ 197.067993      ┆ 6.1251e-57    ┆ CheckAMG only      │
│ K09882        ┆ cobS; cobaltochelatase CobS [EC:6.6.1.2]                                                              ┆ 165 ┆ 151.968246      ┆ 4.1330e-43    ┆ CheckAMG only      │
│ PF01327       ┆ Polypeptide deformylase                                                                               ┆ 114 ┆ 126.708649      ┆ 9.1309e-36    ┆ CheckAMG only      │
│ HMMsoil8469   ┆ gmd, GMDS; GDPmannose 4,6-dehydratase [EC:4.2.1.47]                                                   ┆ 105 ┆ 270.806458      ┆ 1.5877e-79    ┆ CheckAMG only      │
│ K21402        ┆ noeI; 2-O-methyltransferase [EC:2.1.1.-]                                                              ┆ 105 ┆ 80.326729       ┆ 2.8105e-21    ┆ CheckAMG only      │
│ PF03102       ┆ NeuB family                                                                                           ┆ 95  ┆ 217.386032      ┆ 4.2301e-63    ┆ CheckAMG only      │
│ K24288        ┆ meT1; MMP 1-O-methyltransferase [EC:2.1.1.365]                                                        ┆ 89  ┆ 70.002731       ┆ 3.4824e-18    ┆ CheckAMG only      │
│ PF01757       ┆ Acyltransferase domain                                                                                ┆ 79  ┆ 94.380157       ┆ 2.4803e-26    ┆ CheckAMG only      │
│ K00390        ┆ cysH; phosphoadenosine phosphosulfate reductase [EC:1.8.4.8 1.8.4.10]                                 ┆ 78  ┆ 58.5            ┆ 4.3000e-16    ┆ VIBRANT only       │
│ K04748        ┆ norQ; nitric oxide reductase NorQ protein                                                             ┆ 64  ┆ 134.507545      ┆ 1.2848e-37    ┆ CheckAMG only      │
│ HMMsoil462    ┆ gmd, GMDS; GDPmannose 4,6-dehydratase [EC:4.2.1.47]                                                   ┆ 62  ┆ 112.304817      ┆ 3.1596e-31    ┆ CheckAMG only      │
│ PF01050       ┆ Mannose-6-phosphate isomerase C-terminal                                                              ┆ 60  ┆ 74.350384       ┆ 1.5229e-19    ┆ CheckAMG only      │
│ K04068        ┆ nrdG; anaerobic ribonucleoside-triphosphate reductase activating protein [EC:1.97.1.4]                ┆ 49  ┆ 172.299576      ┆ 5.4681e-50    ┆ CheckAMG only      │
│ K01495        ┆ GCH1, folE; GTP cyclohydrolase IA [EC:3.5.4.16]                                                       ┆ 43  ┆ 218.610352      ┆ 5.2967e-64    ┆ CheckAMG & VIBRANT │
│ K06167        ┆ phnP; phosphoribosyl 1,2-cyclic phosphate phosphodiesterase [EC:3.1.4.55]                             ┆ 42  ┆ 61.1            ┆ 3.5000e-17    ┆ VIBRANT only       │
│ HMMsoil90718  ┆ speD, AMD1; S-adenosylmethionine decarboxylase [EC:4.1.1.50]                                          ┆ 41  ┆ 118.280304      ┆ 2.6867e-33    ┆ CheckAMG only      │
│ K10026        ┆ queE; 7-carboxy-7-deazaguanine synthase [EC:4.3.99.3]                                                 ┆ 41  ┆ 143.1           ┆ 1.9000e-41    ┆ VIBRANT only       │
│ K21140        ┆ mec; [CysO sulfur-carrier protein]-S-L-cysteine hydrolase [EC:3.13.1.6]                               ┆ 41  ┆ 60.3            ┆ 3.2000e-17    ┆ VIBRANT only       │
│ K15962        ┆ mtmC; D-mycarose 3-C-methyltransferase                                                                ┆ 40  ┆ 180.530487      ┆ 1.0136e-51    ┆ CheckAMG only      │
│ K00558        ┆ DNMT1, dcm; DNA (cytosine-5)-methyltransferase 1 [EC:2.1.1.37]                                        ┆ 40  ┆ 55.2            ┆ 2.7500e-15    ┆ VIBRANT only       │
│ K01737        ┆ queD, ptpS, PTS; 6-pyruvoyltetrahydropterin/6-carboxytetrahydropterin synthase [EC:4.2.3.12 4.1.2.50… ┆ 40  ┆ 59.1            ┆ 6.7000e-16    ┆ VIBRANT only       │
│ K09882        ┆ cobS; cobaltochelatase CobS [EC:6.6.1.2]                                                              ┆ 39  ┆ 227.2           ┆ 9.5000e-68    ┆ CheckAMG & VIBRANT │
│ K06920        ┆ queC; 7-cyano-7-deazaguanine synthase [EC:6.3.4.20]                                                   ┆ 36  ┆ 218.9           ┆ 1.6500e-64    ┆ VIBRANT only       │
│ K01784        ┆ galE, GALE; UDP-glucose 4-epimerase [EC:5.1.3.2]                                                      ┆ 32  ┆ 156.9           ┆ 6.2350e-45    ┆ VIBRANT only       │
│ K00612        ┆ nodU; carbamoyltransferase [EC:2.1.3.-]                                                               ┆ 30  ┆ 468.386261      ┆ 9.6797e-139   ┆ CheckAMG only      │
│ HMMsoil73877  ┆ aroK, aroL; shikimate kinase [EC:2.7.1.71]                                                            ┆ 29  ┆ 67.511406       ┆ 8.9253e-18    ┆ CheckAMG only      │
│ PF01764       ┆ Lipase (class 3)                                                                                      ┆ 29  ┆ 84.023788       ┆ 1.9525e-22    ┆ CheckAMG only      │
│ K03924        ┆ moxR; MoxR-like ATPase [EC:3.6.3.-]                                                                   ┆ 27  ┆ 173.649872      ┆ 1.3706e-49    ┆ CheckAMG only      │
│ K00682        ┆ GGCT; gamma-glutamylcyclotransferase [EC:4.3.2.9]                                                     ┆ 25  ┆ 66.729256       ┆ 2.5226e-17    ┆ CheckAMG only      │
│ K09883        ┆ cobT; cobaltochelatase CobT [EC:6.6.1.2]                                                              ┆ 25  ┆ 119.439583      ┆ 2.5198e-33    ┆ CheckAMG only      │
│ K06217        ┆ phoH, phoL; phosphate starvation-inducible protein PhoH and related proteins                          ┆ 24  ┆ 237.66893       ┆ 7.6878e-69    ┆ CheckAMG only      │
│ PF04777       ┆ Erv1 / Alr family                                                                                     ┆ 24  ┆ 66.507778       ┆ 4.1719e-17    ┆ CheckAMG only      │
│ K24204        ┆ hxpB; mannitol-1-/sugar-/sorbitol-6-/2-deoxyglucose-6-phosphatase [EC:3.1.3.22 3.1.3.23 3.1.3.50 3.1… ┆ 23  ┆ 103.985001      ┆ 1.9276e-28    ┆ CheckAMG only      │
│ PF03275       ┆ UDP-galactopyranose mutase                                                                            ┆ 23  ┆ 244.009155      ┆ 2.4940e-71    ┆ CheckAMG only      │
│ K02217        ┆ ftnA, ftn; ferritin [EC:1.16.3.2]                                                                     ┆ 22  ┆ 103.939236      ┆ 3.9578e-29    ┆ CheckAMG only      │
│ PF04820       ┆ Tryptophan halogenase                                                                                 ┆ 21  ┆ 329.872406      ┆ 5.7790e-97    ┆ CheckAMG only      │
│ PF01116       ┆ Fructose-bisphosphate aldolase class-II                                                               ┆ 21  ┆ 986.0           ┆ 0.0           ┆ DRAM-V only        │
│ PF01474       ┆ Class-II DAHP synthetase family                                                                       ┆ 20  ┆ 1009.0          ┆ 0.0           ┆ DRAM-V only        │
│ K09883        ┆ cobT; cobaltochelatase CobT [EC:6.6.1.2]                                                              ┆ 19  ┆ 210.401321      ┆ 9.0364e-61    ┆ CheckAMG & VIBRANT │
│ HMMsoil130803 ┆ speD, AMD1; S-adenosylmethionine decarboxylase [EC:4.1.1.50]                                          ┆ 19  ┆ 68.002922       ┆ 1.7356e-17    ┆ CheckAMG only      │
│ HMMsoil90144  ┆ UGDH, ugd; UDPglucose 6-dehydrogenase [EC:1.1.1.22]                                                   ┆ 19  ┆ 119.090416      ┆ 4.5971e-33    ┆ CheckAMG only      │
│ K07175        ┆ phoH2; PhoH-like ATPase                                                                               ┆ 19  ┆ 237.478226      ┆ 2.7281e-69    ┆ CheckAMG only      │
│ PF03331       ┆ UDP-3-O-acyl N-acetylglycosamine deacetylase                                                          ┆ 19  ┆ 1445.0          ┆ 0.0           ┆ DRAM-V only        │
│ K00568        ┆ ubiG; 2-polyprenyl-6-hydroxyphenyl methylase / 3-demethylubiquinone-9 3-methyltransferase [EC:2.1.1.… ┆ 19  ┆ 56.7            ┆ 3.9000e-15    ┆ VIBRANT only       │
│ HMMsoil3470   ┆ UGDH, ugd; UDPglucose 6-dehydrogenase [EC:1.1.1.22]                                                   ┆ 18  ┆ 64.623302       ┆ 8.4277e-17    ┆ CheckAMG only      │
│ K07218        ┆ nosD; nitrous oxidase accessory protein                                                               ┆ 18  ┆ 86.155594       ┆ 2.7135e-23    ┆ CheckAMG only      │
│ K21328        ┆ calS13, atmS13; dTDP-4-amino-4,6-dideoxy-D-glucose/dTDP-4-amino-2,4-dideoxy-beta-L-xylose transamina… ┆ 18  ┆ 338.688629      ┆ 6.4505e-98    ┆ CheckAMG only      │
│ PF01592       ┆ NifU-like N terminal domain                                                                           ┆ 18  ┆ 178.149994      ┆ 1.6072e-51    ┆ CheckAMG only      │
│ …             ┆ …                                                                                                     ┆ …   ┆ …               ┆ …             ┆ …                  │
│ K02110        ┆ ATPF0C, atpE; F-type H+-transporting ATPase subunit c                                                 ┆ 1   ┆ 45.1            ┆ 1.8000e-12    ┆ VIBRANT only       │
│ K02230        ┆ cobN; cobaltochelatase CobN [EC:6.6.1.2]                                                              ┆ 1   ┆ 1583.8          ┆ 0.0           ┆ VIBRANT only       │
│ K02706        ┆ psbD; photosystem II P680 reaction center D2 protein [EC:1.10.3.9]                                    ┆ 1   ┆ 114.8           ┆ 6.3000e-33    ┆ VIBRANT only       │
│ K02778        ┆ PTS-Glc-EIIB, ptsG; PTS system, glucose-specific IIB component [EC:2.7.1.199]                         ┆ 1   ┆ 729.8           ┆ 5.3000e-220   ┆ VIBRANT only       │
│ K02849        ┆ waaQ, rfaQ; heptosyltransferase III [EC:2.4.-.-]                                                      ┆ 1   ┆ 44.1            ┆ 2.0000e-11    ┆ VIBRANT only       │
│ K03517        ┆ nadA; quinolinate synthase [EC:2.5.1.72]                                                              ┆ 1   ┆ 448.2           ┆ 5.3000e-135   ┆ VIBRANT only       │
│ K03644        ┆ lipA; lipoyl synthase [EC:2.8.1.8]                                                                    ┆ 1   ┆ 493.9           ┆ 7.1000e-148   ┆ VIBRANT only       │
│ K03737        ┆ por, nifJ; pyruvate-ferredoxin/flavodoxin oxidoreductase [EC:1.2.7.1 1.2.7.-]                         ┆ 1   ┆ 1660.1          ┆ 0.0           ┆ VIBRANT only       │
│ K03801        ┆ lipB; lipoyl(octanoyl) transferase [EC:2.3.1.181]                                                     ┆ 1   ┆ 66.1            ┆ 1.1000e-18    ┆ VIBRANT only       │
│ K05286        ┆ PIGB; GPI mannosyltransferase 3 [EC:2.4.1.-]                                                          ┆ 1   ┆ 131.6           ┆ 5.3000e-38    ┆ VIBRANT only       │
│ K05383        ┆ cpeT; CpeT protein                                                                                    ┆ 1   ┆ 40.2            ┆ 5.6000e-11    ┆ VIBRANT only       │
│ K06041        ┆ kdsD, kpsF; arabinose-5-phosphate isomerase [EC:5.3.1.13]                                             ┆ 1   ┆ 87.8            ┆ 4.3000e-25    ┆ VIBRANT only       │
│ K07535        ┆ badH; 2-hydroxycyclohexanecarboxyl-CoA dehydrogenase [EC:1.1.1.-]                                     ┆ 1   ┆ 98.4            ┆ 1.1000e-28    ┆ VIBRANT only       │
│ K08678        ┆ UXS1, uxs; UDP-glucuronate decarboxylase [EC:4.1.1.35]                                                ┆ 1   ┆ 480.2           ┆ 3.1000e-144   ┆ VIBRANT only       │
│ K09457        ┆ queF; 7-cyano-7-deazaguanine reductase [EC:1.7.1.13]                                                  ┆ 1   ┆ 100.9           ┆ 1.6000e-29    ┆ VIBRANT only       │
│ K09458        ┆ fabF, OXSM, CEM1; 3-oxoacyl-[acyl-carrier-protein] synthase II [EC:2.3.1.179]                         ┆ 1   ┆ 362.4           ┆ 6.6000e-108   ┆ VIBRANT only       │
│ K09699        ┆ DBT, bkdB; 2-oxoisovalerate dehydrogenase E2 component (dihydrolipoyl transacylase) [EC:2.3.1.168]    ┆ 1   ┆ 45.4            ┆ 1.1000e-12    ┆ VIBRANT only       │
│ K11175        ┆ purN; phosphoribosylglycinamide formyltransferase 1 [EC:2.1.2.2]                                      ┆ 1   ┆ 48.5            ┆ 9.8000e-13    ┆ VIBRANT only       │
│ K12450        ┆ RHM; UDP-glucose 4,6-dehydratase [EC:4.2.1.76]                                                        ┆ 1   ┆ 115.5           ┆ 5.5000e-34    ┆ VIBRANT only       │
│ K13017        ┆ wbpE, wlbC; UDP-2-acetamido-2-deoxy-ribo-hexuluronate aminotransferase [EC:2.6.1.98]                  ┆ 1   ┆ 252.4           ┆ 1.1000e-74    ┆ VIBRANT only       │
│ K13038        ┆ coaBC, dfp; phosphopantothenoylcysteine decarboxylase / phosphopantothenate---cysteine ligase [EC:4.… ┆ 1   ┆ 48.0            ┆ 1.8000e-13    ┆ VIBRANT only       │
│ K13273        ┆ PMVK; phosphomevalonate kinase [EC:2.7.4.2]                                                           ┆ 1   ┆ 45.2            ┆ 8.7000e-12    ┆ VIBRANT only       │
│ K13566        ┆ NIT2, yafV; omega-amidase [EC:3.5.1.3]                                                                ┆ 1   ┆ 50.9            ┆ 2.7000e-14    ┆ VIBRANT only       │
│ K15971        ┆ tcmP, elmP; O-methyltransferase [EC:2.1.1.-]                                                          ┆ 1   ┆ 74.7            ┆ 1.6000e-21    ┆ VIBRANT only       │
│ K17716        ┆ capD; UDP-glucose 4-epimerase [EC:5.1.3.2]                                                            ┆ 1   ┆ 173.2           ┆ 9.6000e-51    ┆ VIBRANT only       │
│ K19002        ┆ mgs, bgsB; 1,2-diacylglycerol 3-alpha-glucosyltransferase [EC:2.4.1.337]                              ┆ 1   ┆ 68.4            ┆ 7.0000e-19    ┆ VIBRANT only       │
│ K22226        ┆ ahbC; Fe-coproporphyrin III synthase                                                                  ┆ 1   ┆ 57.9            ┆ 9.9000e-16    ┆ VIBRANT only       │
│ PF00108       ┆ Thiolase, N-terminal domain                                                                           ┆ 1   ┆ 350.0           ┆ 1.6000e-105   ┆ VIBRANT only       │
│ PF00124       ┆ Photosynthetic reaction centre protein                                                                ┆ 1   ┆ 317.9           ┆ 4.0000e-95    ┆ VIBRANT only       │
│ PF00141       ┆ Peroxidase                                                                                            ┆ 1   ┆ 297.3           ┆ 1.9000e-89    ┆ VIBRANT only       │
│ PF00149       ┆ Calcineurin-like phosphoesterase                                                                      ┆ 1   ┆ 49.3            ┆ 8.0000e-13    ┆ VIBRANT only       │
│ PF00293       ┆ NUDIX domain                                                                                          ┆ 1   ┆ 53.2            ┆ 1.5000e-14    ┆ VIBRANT only       │
│ PF00393       ┆ 6-phosphogluconate dehydrogenase, C-terminal domain                                                   ┆ 1   ┆ 80.3            ┆ 1.5000e-22    ┆ VIBRANT only       │
│ PF00487       ┆ Fatty acid desaturase                                                                                 ┆ 1   ┆ 40.6            ┆ 2.6000e-10    ┆ VIBRANT only       │
│ PF00535       ┆ Glycosyl transferase family 2                                                                         ┆ 1   ┆ 61.3            ┆ 1.4000e-16    ┆ VIBRANT only       │
│ PF00762       ┆ Ferrochelatase                                                                                        ┆ 1   ┆ 330.8           ┆ 1.8000e-99    ┆ VIBRANT only       │
│ PF00908       ┆ dTDP-4-dehydrorhamnose 3,5-epimerase                                                                  ┆ 1   ┆ 110.4           ┆ 3.5000e-32    ┆ VIBRANT only       │
│ PF00923       ┆ Transaldolase/Fructose-6-phosphate aldolase                                                           ┆ 1   ┆ 115.5           ┆ 2.6000e-33    ┆ VIBRANT only       │
│ PF00977       ┆ Histidine biosynthesis protein                                                                        ┆ 1   ┆ 203.5           ┆ 4.5000e-60    ┆ VIBRANT only       │
│ PF00984       ┆ UDP-glucose/GDP-mannose dehydrogenase family, central domain                                          ┆ 1   ┆ 76.7            ┆ 2.3000e-21    ┆ VIBRANT only       │
│ PF01050       ┆ Mannose-6-phosphate isomerase                                                                         ┆ 1   ┆ 51.2            ┆ 2.4000e-14    ┆ VIBRANT only       │
│ PF01380       ┆ SIS domain                                                                                            ┆ 1   ┆ 194.3           ┆ 1.2000e-58    ┆ VIBRANT only       │
│ PF02310       ┆ B12 binding domain                                                                                    ┆ 1   ┆ 41.0            ┆ 1.7000e-10    ┆ VIBRANT only       │
│ PF02773       ┆ S-adenosylmethionine synthetase, C-terminal domain                                                    ┆ 1   ┆ 187.4           ┆ 2.0000e-56    ┆ VIBRANT only       │
│ PF02878       ┆ Phosphoglucomutase/phosphomannomutase, alpha/beta/alpha domain I                                      ┆ 1   ┆ 117.6           ┆ 6.1000e-35    ┆ VIBRANT only       │
│ PF02882       ┆ Tetrahydrofolate dehydrogenase/cyclohydrolase, NAD(P)-binding domain                                  ┆ 1   ┆ 150.7           ┆ 5.4000e-45    ┆ VIBRANT only       │
│ PF03102       ┆ NeuB family                                                                                           ┆ 1   ┆ 258.6           ┆ 7.3000e-77    ┆ VIBRANT only       │
│ PF03721       ┆ UDP-glucose/GDP-mannose dehydrogenase family, NAD binding domain                                      ┆ 1   ┆ 77.8            ┆ 3.8000e-22    ┆ VIBRANT only       │
│ PF08013       ┆ Tagatose 6 phosphate kinase                                                                           ┆ 1   ┆ 52.0            ┆ 2.1000e-14    ┆ VIBRANT only       │
│ PF13091       ┆ PLD-like domain                                                                                       ┆ 1   ┆ 61.3            ┆ 2.2000e-17    ┆ VIBRANT only       │
└───────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────┴─────┴─────────────────┴───────────────┴────────────────────┘

### Weight composition at default / high

In [81]:
def _assign_none_categories(df: pl.DataFrame, prefix: str) -> pl.DataFrame:
    cat_col = f"{prefix}_dominant_category"
    w_col = f"{prefix}_best_AMG_weight"

    return df.with_columns(
        pl.when(
            pl.col(cat_col).is_null() |
            (pl.col(cat_col) == "none")
        )
        .then(
            pl.when(pl.col(w_col).is_null()).then(pl.lit("none_no_weight"))
            .when(pl.col(w_col) >= 0.6).then(pl.lit("none_likely"))
            .otherwise(pl.lit("none_unlikely"))
        )
        .otherwise(pl.col(cat_col))
        .alias(cat_col)
    )

def weight_composition(m: pl.DataFrame, tier_cols: list[tuple[str, str]]) -> pl.DataFrame:
    rows = []
    for tier, prefix in tier_cols:
        sub = m.filter(pl.col(tier))
        n_tier = sub.height
        for b in WEIGHT_BIN_ORDER:
            n = int(sub.filter(pl.col(f"{prefix}_weight_bin") == b).height)
            rows.append({"tier": tier, "tool": prefix, "weight_bin": b,
                         "n": n, "n_tier": n_tier,
                         "pct": round(100 * n / n_tier, 2) if n_tier else 0.0})
    return pl.DataFrame(rows).filter(pl.col("weight_bin") != "none")

def category_composition(m: pl.DataFrame, tier_cols: list[tuple[str, str]]) -> pl.DataFrame:
    rows = []

    for tier, prefix in tier_cols:
        sub = m.filter(pl.col(tier))
        sub = _assign_none_categories(sub, prefix)

        n_tier = sub.height

        categories = CATEGORY_ORDER + ["none_likely", "none_unlikely", "none_no_weight"]

        for c in categories:
            n = int(sub.filter(pl.col(f"{prefix}_dominant_category") == c).height)
            rows.append({
                "tier": tier,
                "tool": prefix,
                "category": c,
                "n": n,
                "n_tier": n_tier,
                "pct": round(100 * n / n_tier, 2) if n_tier else 0.0
            })

    return pl.DataFrame(rows).filter(pl.col("category") != "none")

def category_weight_composition(m: pl.DataFrame, tier_cols: list[tuple[str, str]]) -> pl.DataFrame:
    dfs = []

    categories = CATEGORY_ORDER + ["none_likely", "none_unlikely", "none_no_weight"]

    full_grid = (
        pl.DataFrame({"category": categories})
        .join(pl.DataFrame({"weight_bin": WEIGHT_BIN_ORDER}), how="cross")
    )

    for tier, prefix in tier_cols:
        sub = m.filter(pl.col(tier))
        sub = _assign_none_categories(sub, prefix)

        n_tier = sub.height
        if n_tier == 0:
            continue

        counts = (
            sub
            .group_by([f"{prefix}_dominant_category", f"{prefix}_weight_bin"])
            .agg(pl.len().alias("n"))
            .rename({
                f"{prefix}_dominant_category": "category",
                f"{prefix}_weight_bin": "weight_bin"
            })
        )

        out = (
            full_grid
            .join(counts, on=["category", "weight_bin"], how="left")
            .with_columns([
                pl.col("n").fill_null(0),
                pl.lit(tier).alias("tier"),
                pl.lit(prefix).alias("tool"),
                pl.lit(n_tier).alias("n_tier")
            ])
            .with_columns(
                (100 * pl.col("n") / pl.col("n_tier")).round(2).alias("pct")
            )
        )

        dfs.append(out)

    return (
        pl.concat(dfs)
        .select(["tier", "tool", "category", "weight_bin", "n", "n_tier", "pct"])
        .sort(["tier", "tool", "category", "weight_bin"], descending=[False, False, False, True])
        .filter(pl.col("weight_bin") != "none")
        .filter(pl.col("category") != "none")
    )

def source_db_composition(
    m: pl.DataFrame,
    tier_cols: list[tuple[str, str]]
) -> pl.DataFrame:
    rows = []

    for tier_col, tool in tier_cols:
        if tool == "DRAMV":
            tool = "DRAM-V"
        sub = m.filter(
            (pl.col("tool") == tool) &
            pl.col(tier_col)
        )

        for db in checkamg_dbs:
            n = sub.filter(pl.col("database") == db).height
            rows.append({
                "tier": tier_col,
                "tool": tool,
                "database": db,
                "n": n
            })

    result = pl.DataFrame(rows)

    return (
        result
        .with_columns(
            pl.col("n")
            .sum()
            .over(["tier", "tool"])
            .alias("n_tier")
        )
        .with_columns(
            (100 * pl.col("n") / pl.col("n_tier"))
            .round(2)
            .alias("pct")
        )
    )

In [82]:
DEFAULT_HIGH_WITH_PREFIX = [
    ("CheckAMG_high", "CheckAMG"),
    ("DRAMV_default", "DRAMV"),
    ("VIBRANT_high",  "VIBRANT"),
]

weight_default_high = weight_composition(members_weights, DEFAULT_HIGH_WITH_PREFIX).sort(["tier", "weight_bin"])

In [83]:
with pl.Config(tbl_rows=100, tbl_width_chars=500):
    print(weight_default_high)

shape: (21, 6)
┌───────────────┬──────────┬────────────────┬──────┬────────┬───────┐
│ tier          ┆ tool     ┆ weight_bin     ┆ n    ┆ n_tier ┆ pct   │
│ ---           ┆ ---      ┆ ---            ┆ ---  ┆ ---    ┆ ---   │
│ str           ┆ str      ┆ str            ┆ i64  ┆ i64    ┆ f64   │
╞═══════════════╪══════════╪════════════════╪══════╪════════╪═══════╡
│ CheckAMG_high ┆ CheckAMG ┆ no_annotation  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ no_reference   ┆ 9    ┆ 3218   ┆ 0.28  │
│ CheckAMG_high ┆ CheckAMG ┆ not_called     ┆ 33   ┆ 3218   ┆ 1.03  │
│ CheckAMG_high ┆ CheckAMG ┆ weight_0.4_0.6 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ weight_0.6_0.8 ┆ 2926 ┆ 3218   ┆ 90.93 │
│ CheckAMG_high ┆ CheckAMG ┆ weight_ge_0.8  ┆ 250  ┆ 3218   ┆ 7.77  │
│ CheckAMG_high ┆ CheckAMG ┆ weight_lt_0.4  ┆ 0    ┆ 3218   ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ no_annotation  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ no_reference   ┆ 91   ┆ 664    ┆ 13.7  │
│ DRAMV_default ┆ DRAMV    ┆ not_called     ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ weight_0.4_0.6 ┆ 38   ┆ 664    ┆ 5.72  │
│ DRAMV_default ┆ DRAMV    ┆ weight_0.6_0.8 ┆ 97   ┆ 664    ┆ 14.61 │
│ DRAMV_default ┆ DRAMV    ┆ weight_ge_0.8  ┆ 427  ┆ 664    ┆ 64.31 │
│ DRAMV_default ┆ DRAMV    ┆ weight_lt_0.4  ┆ 11   ┆ 664    ┆ 1.66  │
│ VIBRANT_high  ┆ VIBRANT  ┆ no_annotation  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ no_reference   ┆ 149  ┆ 1270   ┆ 11.73 │
│ VIBRANT_high  ┆ VIBRANT  ┆ not_called     ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ weight_0.4_0.6 ┆ 621  ┆ 1270   ┆ 48.9  │
│ VIBRANT_high  ┆ VIBRANT  ┆ weight_0.6_0.8 ┆ 394  ┆ 1270   ┆ 31.02 │
│ VIBRANT_high  ┆ VIBRANT  ┆ weight_ge_0.8  ┆ 56   ┆ 1270   ┆ 4.41  │
│ VIBRANT_high  ┆ VIBRANT  ┆ weight_lt_0.4  ┆ 50   ┆ 1270   ┆ 3.94  │
└───────────────┴──────────┴────────────────┴──────┴────────┴───────┘

In [84]:
category_default_high = category_composition(members_weights, DEFAULT_HIGH_WITH_PREFIX).sort(["tier", "pct"], descending=[False, True])

In [85]:
with pl.Config(tbl_rows=100, tbl_width_chars=500):
    print(category_default_high)

shape: (24, 6)
┌───────────────┬──────────┬────────────────┬──────┬────────┬───────┐
│ tier          ┆ tool     ┆ category       ┆ n    ┆ n_tier ┆ pct   │
│ ---           ┆ ---      ┆ ---            ┆ ---  ┆ ---    ┆ ---   │
│ str           ┆ str      ┆ str            ┆ i64  ┆ i64    ┆ f64   │
╞═══════════════╪══════════╪════════════════╪══════╪════════╪═══════╡
│ CheckAMG_high ┆ CheckAMG ┆ none_likely    ┆ 1601 ┆ 3218   ┆ 49.75 │
│ CheckAMG_high ┆ CheckAMG ┆ nucleotide     ┆ 1050 ┆ 3218   ┆ 32.63 │
│ CheckAMG_high ┆ CheckAMG ┆ methyl         ┆ 347  ┆ 3218   ┆ 10.78 │
│ CheckAMG_high ┆ CheckAMG ┆ glucan         ┆ 127  ┆ 3218   ┆ 3.95  │
│ CheckAMG_high ┆ CheckAMG ┆ lipid          ┆ 52   ┆ 3218   ┆ 1.62  │
│ CheckAMG_high ┆ CheckAMG ┆ none_no_weight ┆ 41   ┆ 3218   ┆ 1.27  │
│ CheckAMG_high ┆ CheckAMG ┆ essential      ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_unlikely  ┆ 0    ┆ 3218   ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_likely    ┆ 195  ┆ 664    ┆ 29.37 │
│ DRAMV_default ┆ DRAMV    ┆ nucleotide     ┆ 188  ┆ 664    ┆ 28.31 │
│ DRAMV_default ┆ DRAMV    ┆ essential      ┆ 170  ┆ 664    ┆ 25.6  │
│ DRAMV_default ┆ DRAMV    ┆ none_no_weight ┆ 44   ┆ 664    ┆ 6.63  │
│ DRAMV_default ┆ DRAMV    ┆ methyl         ┆ 25   ┆ 664    ┆ 3.77  │
│ DRAMV_default ┆ DRAMV    ┆ none_unlikely  ┆ 19   ┆ 664    ┆ 2.86  │
│ DRAMV_default ┆ DRAMV    ┆ glucan         ┆ 16   ┆ 664    ┆ 2.41  │
│ DRAMV_default ┆ DRAMV    ┆ lipid          ┆ 7    ┆ 664    ┆ 1.05  │
│ VIBRANT_high  ┆ VIBRANT  ┆ nucleotide     ┆ 561  ┆ 1270   ┆ 44.17 │
│ VIBRANT_high  ┆ VIBRANT  ┆ essential      ┆ 428  ┆ 1270   ┆ 33.7  │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_likely    ┆ 191  ┆ 1270   ┆ 15.04 │
│ VIBRANT_high  ┆ VIBRANT  ┆ methyl         ┆ 35   ┆ 1270   ┆ 2.76  │
│ VIBRANT_high  ┆ VIBRANT  ┆ lipid          ┆ 23   ┆ 1270   ┆ 1.81  │
│ VIBRANT_high  ┆ VIBRANT  ┆ glucan         ┆ 16   ┆ 1270   ┆ 1.26  │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_unlikely  ┆ 11   ┆ 1270   ┆ 0.87  │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_no_weight ┆ 5    ┆ 1270   ┆ 0.39  │
└───────────────┴──────────┴────────────────┴──────┴────────┴───────┘

In [86]:
category_weight_default_high = (
    category_weight_composition(members_weights, DEFAULT_HIGH_WITH_PREFIX)
    .sort(["tier", "category", "weight_bin"])
)

In [87]:
with pl.Config(tbl_rows=200, tbl_width_chars=500):
    print(category_weight_default_high)

shape: (168, 7)
┌───────────────┬──────────┬────────────────┬────────────────┬──────┬────────┬───────┐
│ tier          ┆ tool     ┆ category       ┆ weight_bin     ┆ n    ┆ n_tier ┆ pct   │
│ ---           ┆ ---      ┆ ---            ┆ ---            ┆ ---  ┆ ---    ┆ ---   │
│ str           ┆ str      ┆ str            ┆ str            ┆ u64  ┆ i32    ┆ f64   │
╞═══════════════╪══════════╪════════════════╪════════════════╪══════╪════════╪═══════╡
│ CheckAMG_high ┆ CheckAMG ┆ essential      ┆ no_annotation  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ essential      ┆ no_reference   ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ essential      ┆ not_called     ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ essential      ┆ weight_0.4_0.6 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ essential      ┆ weight_0.6_0.8 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ essential      ┆ weight_ge_0.8  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ essential      ┆ weight_lt_0.4  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ glucan         ┆ no_annotation  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ glucan         ┆ no_reference   ┆ 1    ┆ 3218   ┆ 0.03  │
│ CheckAMG_high ┆ CheckAMG ┆ glucan         ┆ not_called     ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ glucan         ┆ weight_0.4_0.6 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ glucan         ┆ weight_0.6_0.8 ┆ 100  ┆ 3218   ┆ 3.11  │
│ CheckAMG_high ┆ CheckAMG ┆ glucan         ┆ weight_ge_0.8  ┆ 26   ┆ 3218   ┆ 0.81  │
│ CheckAMG_high ┆ CheckAMG ┆ glucan         ┆ weight_lt_0.4  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ lipid          ┆ no_annotation  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ lipid          ┆ no_reference   ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ lipid          ┆ not_called     ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ lipid          ┆ weight_0.4_0.6 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ lipid          ┆ weight_0.6_0.8 ┆ 38   ┆ 3218   ┆ 1.18  │
│ CheckAMG_high ┆ CheckAMG ┆ lipid          ┆ weight_ge_0.8  ┆ 14   ┆ 3218   ┆ 0.44  │
│ CheckAMG_high ┆ CheckAMG ┆ lipid          ┆ weight_lt_0.4  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ methyl         ┆ no_annotation  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ methyl         ┆ no_reference   ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ methyl         ┆ not_called     ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ methyl         ┆ weight_0.4_0.6 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ methyl         ┆ weight_0.6_0.8 ┆ 346  ┆ 3218   ┆ 10.75 │
│ CheckAMG_high ┆ CheckAMG ┆ methyl         ┆ weight_ge_0.8  ┆ 1    ┆ 3218   ┆ 0.03  │
│ CheckAMG_high ┆ CheckAMG ┆ methyl         ┆ weight_lt_0.4  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_likely    ┆ no_annotation  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_likely    ┆ no_reference   ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_likely    ┆ not_called     ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_likely    ┆ weight_0.4_0.6 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_likely    ┆ weight_0.6_0.8 ┆ 1462 ┆ 3218   ┆ 45.43 │
│ CheckAMG_high ┆ CheckAMG ┆ none_likely    ┆ weight_ge_0.8  ┆ 139  ┆ 3218   ┆ 4.32  │
│ CheckAMG_high ┆ CheckAMG ┆ none_likely    ┆ weight_lt_0.4  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_no_weight ┆ no_annotation  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_no_weight ┆ no_reference   ┆ 8    ┆ 3218   ┆ 0.25  │
│ CheckAMG_high ┆ CheckAMG ┆ none_no_weight ┆ not_called     ┆ 33   ┆ 3218   ┆ 1.03  │
│ CheckAMG_high ┆ CheckAMG ┆ none_no_weight ┆ weight_0.4_0.6 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_no_weight ┆ weight_0.6_0.8 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_no_weight ┆ weight_ge_0.8  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_no_weight ┆ weight_lt_0.4  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_unlikely  ┆ no_annotation  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_unlikely  ┆ no_reference   ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_unlikely  ┆ not_called     ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_unlikely  ┆ weight_0.4_0.6 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_unlikely  ┆ weight_0.6_0.8 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_unlikely  ┆ weight_ge_0.8  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ none_unlikely  ┆ weight_lt_0.4  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ nucleotide     ┆ no_annotation  ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ nucleotide     ┆ no_reference   ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ nucleotide     ┆ not_called     ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ nucleotide     ┆ weight_0.4_0.6 ┆ 0    ┆ 3218   ┆ 0.0   │
│ CheckAMG_high ┆ CheckAMG ┆ nucleotide     ┆ weight_0.6_0.8 ┆ 980  ┆ 3218   ┆ 30.45 │
│ CheckAMG_high ┆ CheckAMG ┆ nucleotide     ┆ weight_ge_0.8  ┆ 70   ┆ 3218   ┆ 2.18  │
│ CheckAMG_high ┆ CheckAMG ┆ nucleotide     ┆ weight_lt_0.4  ┆ 0    ┆ 3218   ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ essential      ┆ no_annotation  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ essential      ┆ no_reference   ┆ 23   ┆ 664    ┆ 3.46  │
│ DRAMV_default ┆ DRAMV    ┆ essential      ┆ not_called     ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ essential      ┆ weight_0.4_0.6 ┆ 15   ┆ 664    ┆ 2.26  │
│ DRAMV_default ┆ DRAMV    ┆ essential      ┆ weight_0.6_0.8 ┆ 16   ┆ 664    ┆ 2.41  │
│ DRAMV_default ┆ DRAMV    ┆ essential      ┆ weight_ge_0.8  ┆ 115  ┆ 664    ┆ 17.32 │
│ DRAMV_default ┆ DRAMV    ┆ essential      ┆ weight_lt_0.4  ┆ 1    ┆ 664    ┆ 0.15  │
│ DRAMV_default ┆ DRAMV    ┆ glucan         ┆ no_annotation  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ glucan         ┆ no_reference   ┆ 5    ┆ 664    ┆ 0.75  │
│ DRAMV_default ┆ DRAMV    ┆ glucan         ┆ not_called     ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ glucan         ┆ weight_0.4_0.6 ┆ 3    ┆ 664    ┆ 0.45  │
│ DRAMV_default ┆ DRAMV    ┆ glucan         ┆ weight_0.6_0.8 ┆ 4    ┆ 664    ┆ 0.6   │
│ DRAMV_default ┆ DRAMV    ┆ glucan         ┆ weight_ge_0.8  ┆ 4    ┆ 664    ┆ 0.6   │
│ DRAMV_default ┆ DRAMV    ┆ glucan         ┆ weight_lt_0.4  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ lipid          ┆ no_annotation  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ lipid          ┆ no_reference   ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ lipid          ┆ not_called     ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ lipid          ┆ weight_0.4_0.6 ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ lipid          ┆ weight_0.6_0.8 ┆ 2    ┆ 664    ┆ 0.3   │
│ DRAMV_default ┆ DRAMV    ┆ lipid          ┆ weight_ge_0.8  ┆ 5    ┆ 664    ┆ 0.75  │
│ DRAMV_default ┆ DRAMV    ┆ lipid          ┆ weight_lt_0.4  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ methyl         ┆ no_annotation  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ methyl         ┆ no_reference   ┆ 2    ┆ 664    ┆ 0.3   │
│ DRAMV_default ┆ DRAMV    ┆ methyl         ┆ not_called     ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ methyl         ┆ weight_0.4_0.6 ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ methyl         ┆ weight_0.6_0.8 ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ methyl         ┆ weight_ge_0.8  ┆ 23   ┆ 664    ┆ 3.46  │
│ DRAMV_default ┆ DRAMV    ┆ methyl         ┆ weight_lt_0.4  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_likely    ┆ no_annotation  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_likely    ┆ no_reference   ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_likely    ┆ not_called     ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_likely    ┆ weight_0.4_0.6 ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_likely    ┆ weight_0.6_0.8 ┆ 51   ┆ 664    ┆ 7.68  │
│ DRAMV_default ┆ DRAMV    ┆ none_likely    ┆ weight_ge_0.8  ┆ 144  ┆ 664    ┆ 21.69 │
│ DRAMV_default ┆ DRAMV    ┆ none_likely    ┆ weight_lt_0.4  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_no_weight ┆ no_annotation  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_no_weight ┆ no_reference   ┆ 44   ┆ 664    ┆ 6.63  │
│ DRAMV_default ┆ DRAMV    ┆ none_no_weight ┆ not_called     ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_no_weight ┆ weight_0.4_0.6 ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_no_weight ┆ weight_0.6_0.8 ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_no_weight ┆ weight_ge_0.8  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_no_weight ┆ weight_lt_0.4  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_unlikely  ┆ no_annotation  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_unlikely  ┆ no_reference   ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_unlikely  ┆ not_called     ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_unlikely  ┆ weight_0.4_0.6 ┆ 17   ┆ 664    ┆ 2.56  │
│ DRAMV_default ┆ DRAMV    ┆ none_unlikely  ┆ weight_0.6_0.8 ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_unlikely  ┆ weight_ge_0.8  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ none_unlikely  ┆ weight_lt_0.4  ┆ 2    ┆ 664    ┆ 0.3   │
│ DRAMV_default ┆ DRAMV    ┆ nucleotide     ┆ no_annotation  ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ nucleotide     ┆ no_reference   ┆ 17   ┆ 664    ┆ 2.56  │
│ DRAMV_default ┆ DRAMV    ┆ nucleotide     ┆ not_called     ┆ 0    ┆ 664    ┆ 0.0   │
│ DRAMV_default ┆ DRAMV    ┆ nucleotide     ┆ weight_0.4_0.6 ┆ 3    ┆ 664    ┆ 0.45  │
│ DRAMV_default ┆ DRAMV    ┆ nucleotide     ┆ weight_0.6_0.8 ┆ 24   ┆ 664    ┆ 3.61  │
│ DRAMV_default ┆ DRAMV    ┆ nucleotide     ┆ weight_ge_0.8  ┆ 136  ┆ 664    ┆ 20.48 │
│ DRAMV_default ┆ DRAMV    ┆ nucleotide     ┆ weight_lt_0.4  ┆ 8    ┆ 664    ┆ 1.2   │
│ VIBRANT_high  ┆ VIBRANT  ┆ essential      ┆ no_annotation  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ essential      ┆ no_reference   ┆ 37   ┆ 1270   ┆ 2.91  │
│ VIBRANT_high  ┆ VIBRANT  ┆ essential      ┆ not_called     ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ essential      ┆ weight_0.4_0.6 ┆ 339  ┆ 1270   ┆ 26.69 │
│ VIBRANT_high  ┆ VIBRANT  ┆ essential      ┆ weight_0.6_0.8 ┆ 3    ┆ 1270   ┆ 0.24  │
│ VIBRANT_high  ┆ VIBRANT  ┆ essential      ┆ weight_ge_0.8  ┆ 2    ┆ 1270   ┆ 0.16  │
│ VIBRANT_high  ┆ VIBRANT  ┆ essential      ┆ weight_lt_0.4  ┆ 47   ┆ 1270   ┆ 3.7   │
│ VIBRANT_high  ┆ VIBRANT  ┆ glucan         ┆ no_annotation  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ glucan         ┆ no_reference   ┆ 15   ┆ 1270   ┆ 1.18  │
│ VIBRANT_high  ┆ VIBRANT  ┆ glucan         ┆ not_called     ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ glucan         ┆ weight_0.4_0.6 ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ glucan         ┆ weight_0.6_0.8 ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ glucan         ┆ weight_ge_0.8  ┆ 1    ┆ 1270   ┆ 0.08  │
│ VIBRANT_high  ┆ VIBRANT  ┆ glucan         ┆ weight_lt_0.4  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ lipid          ┆ no_annotation  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ lipid          ┆ no_reference   ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ lipid          ┆ not_called     ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ lipid          ┆ weight_0.4_0.6 ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ lipid          ┆ weight_0.6_0.8 ┆ 18   ┆ 1270   ┆ 1.42  │
│ VIBRANT_high  ┆ VIBRANT  ┆ lipid          ┆ weight_ge_0.8  ┆ 5    ┆ 1270   ┆ 0.39  │
│ VIBRANT_high  ┆ VIBRANT  ┆ lipid          ┆ weight_lt_0.4  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ methyl         ┆ no_annotation  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ methyl         ┆ no_reference   ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ methyl         ┆ not_called     ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ methyl         ┆ weight_0.4_0.6 ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ methyl         ┆ weight_0.6_0.8 ┆ 34   ┆ 1270   ┆ 2.68  │
│ VIBRANT_high  ┆ VIBRANT  ┆ methyl         ┆ weight_ge_0.8  ┆ 1    ┆ 1270   ┆ 0.08  │
│ VIBRANT_high  ┆ VIBRANT  ┆ methyl         ┆ weight_lt_0.4  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_likely    ┆ no_annotation  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_likely    ┆ no_reference   ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_likely    ┆ not_called     ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_likely    ┆ weight_0.4_0.6 ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_likely    ┆ weight_0.6_0.8 ┆ 159  ┆ 1270   ┆ 12.52 │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_likely    ┆ weight_ge_0.8  ┆ 32   ┆ 1270   ┆ 2.52  │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_likely    ┆ weight_lt_0.4  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_no_weight ┆ no_annotation  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_no_weight ┆ no_reference   ┆ 5    ┆ 1270   ┆ 0.39  │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_no_weight ┆ not_called     ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_no_weight ┆ weight_0.4_0.6 ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_no_weight ┆ weight_0.6_0.8 ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_no_weight ┆ weight_ge_0.8  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_no_weight ┆ weight_lt_0.4  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_unlikely  ┆ no_annotation  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_unlikely  ┆ no_reference   ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_unlikely  ┆ not_called     ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_unlikely  ┆ weight_0.4_0.6 ┆ 11   ┆ 1270   ┆ 0.87  │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_unlikely  ┆ weight_0.6_0.8 ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_unlikely  ┆ weight_ge_0.8  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ none_unlikely  ┆ weight_lt_0.4  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ nucleotide     ┆ no_annotation  ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ nucleotide     ┆ no_reference   ┆ 92   ┆ 1270   ┆ 7.24  │
│ VIBRANT_high  ┆ VIBRANT  ┆ nucleotide     ┆ not_called     ┆ 0    ┆ 1270   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ nucleotide     ┆ weight_0.4_0.6 ┆ 271  ┆ 1270   ┆ 21.34 │
│ VIBRANT_high  ┆ VIBRANT  ┆ nucleotide     ┆ weight_0.6_0.8 ┆ 180  ┆ 1270   ┆ 14.17 │
│ VIBRANT_high  ┆ VIBRANT  ┆ nucleotide     ┆ weight_ge_0.8  ┆ 15   ┆ 1270   ┆ 1.18  │
│ VIBRANT_high  ┆ VIBRANT  ┆ nucleotide     ┆ weight_lt_0.4  ┆ 3    ┆ 1270   ┆ 0.24  │
└───────────────┴──────────┴────────────────┴────────────────┴──────┴────────┴───────┘

In [88]:
source_db_default_high = source_db_composition(
    amg_predictions_categorized,
    DEFAULT_HIGH_WITH_PREFIX
).sort(["tier", "database"])

In [89]:
with pl.Config(tbl_rows=200, tbl_width_chars=500):
    print(source_db_default_high)

shape: (18, 6)
┌───────────────┬──────────┬───────────┬──────┬────────┬───────┐
│ tier          ┆ tool     ┆ database  ┆ n    ┆ n_tier ┆ pct   │
│ ---           ┆ ---      ┆ ---       ┆ ---  ┆ ---    ┆ ---   │
│ str           ┆ str      ┆ str       ┆ i64  ┆ i64    ┆ f64   │
╞═══════════════╪══════════╪═══════════╪══════╪════════╪═══════╡
│ CheckAMG_high ┆ CheckAMG ┆ CAMPER    ┆ 32   ┆ 5520   ┆ 0.58  │
│ CheckAMG_high ┆ CheckAMG ┆ FOAM      ┆ 815  ┆ 5520   ┆ 14.76 │
│ CheckAMG_high ┆ CheckAMG ┆ KEGG      ┆ 2581 ┆ 5520   ┆ 46.76 │
│ CheckAMG_high ┆ CheckAMG ┆ METABOLIC ┆ 9    ┆ 5520   ┆ 0.16  │
│ CheckAMG_high ┆ CheckAMG ┆ Pfam      ┆ 2083 ┆ 5520   ┆ 37.74 │
│ CheckAMG_high ┆ CheckAMG ┆ dbCAN     ┆ 0    ┆ 5520   ┆ 0.0   │
│ DRAMV_default ┆ DRAM-V   ┆ CAMPER    ┆ 0    ┆ 2397   ┆ 0.0   │
│ DRAMV_default ┆ DRAM-V   ┆ FOAM      ┆ 0    ┆ 2397   ┆ 0.0   │
│ DRAMV_default ┆ DRAM-V   ┆ KEGG      ┆ 4    ┆ 2397   ┆ 0.17  │
│ DRAMV_default ┆ DRAM-V   ┆ METABOLIC ┆ 0    ┆ 2397   ┆ 0.0   │
│ DRAMV_default ┆ DRAM-V   ┆ Pfam      ┆ 2393 ┆ 2397   ┆ 99.83 │
│ DRAMV_default ┆ DRAM-V   ┆ dbCAN     ┆ 0    ┆ 2397   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ CAMPER    ┆ 0    ┆ 2328   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ FOAM      ┆ 0    ┆ 2328   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ KEGG      ┆ 1270 ┆ 2328   ┆ 54.55 │
│ VIBRANT_high  ┆ VIBRANT  ┆ METABOLIC ┆ 0    ┆ 2328   ┆ 0.0   │
│ VIBRANT_high  ┆ VIBRANT  ┆ Pfam      ┆ 1058 ┆ 2328   ┆ 45.45 │
│ VIBRANT_high  ┆ VIBRANT  ┆ dbCAN     ┆ 0    ┆ 2328   ┆ 0.0   │
└───────────────┴──────────┴───────────┴──────┴────────┴───────┘

### Members at any tier

Genes called at any tier by any tool.

In [90]:
all_tier_cols = list(ALL_TIERS)
any_tier = pl.any_horizontal([pl.col(c) for c in all_tier_cols])
members_all = (
    amg_predictions.filter(any_tier)
        .select(
            "gene", "scaffold", "source", "sample", "ecosystem",
            "genomad_viral", "in_strict_viral_region",
            "viral_gene_left_dist", "viral_gene_right_dist",
            "MGE_gene_left_dist", "MGE_gene_right_dist",
            "MGE_gene_left_V_score", "MGE_gene_right_V_score",
            *all_tier_cols,
            "DRAMV_auxiliary_score",
            "DRAMV_M", "DRAMV_T", "DRAMV_V", "DRAMV_A", "DRAMV_P", "DRAMV_B", "DRAMV_F",
        )
)

### Annotation database per gene across all tiers

For every gene called AMG at any tier, pool the `final_annot` hits from each tool that called it (at any tier), restricted to databases in CheckAMG's AMG reference. A gene is labeled with that database if only one is present, "Multiple DBs" if more than one, and "None" if none. Counts are aggregated per tier-membership pattern for the all-tier UpSet plot.

In [91]:
TOOL_TIER_COLS = {
    "CheckAMG": ["CheckAMG_high", "CheckAMG_medium", "CheckAMG_low"],
    "DRAM-V": ["DRAMV_default", "DRAMV_allow_T", "DRAMV_aux_4", "DRAMV_aux_4_allow_T"],
    "VIBRANT": ["VIBRANT_high", "VIBRANT_medium", "VIBRANT_low"],
}
GENE_KEYS = ["gene", "source", "sample", "ecosystem"]

calling_tools = (
    members_all.lazy()
    .select(*GENE_KEYS, *[pl.any_horizontal(cols).alias(tool) for tool, cols in TOOL_TIER_COLS.items()])
    .unpivot(index=GENE_KEYS, variable_name="tool", value_name="called")
    .filter(pl.col("called"))
    .drop("called")
)

gene_db_source = (
    calling_tools
    .join(
        annotations.lazy()
        .filter(pl.col("final_annot") & pl.col("database").is_in(checkamg_dbs))
        .select(*GENE_KEYS, "tool", "database")
        .unique(),
        on=[*GENE_KEYS, "tool"],
        how="left",
    )
    .group_by(GENE_KEYS)
    .agg(pl.col("database").drop_nulls().unique().alias("dbs"))
    .with_columns(
        pl.when(pl.col("dbs").list.len() == 0).then(pl.lit("None"))
          .when(pl.col("dbs").list.len() > 1).then(pl.lit("Multiple DBs"))
          .otherwise(pl.col("dbs").list.first())
          .alias("db_source")
    )
    .drop("dbs")
)

upset_db_all_tiers = (
    members_all.lazy()
    .select(*GENE_KEYS, *all_tier_cols)
    .join(gene_db_source, on=GENE_KEYS, how="left")
    .group_by([*all_tier_cols, "db_source"])
    .agg(pl.len().alias("n"))
    .sort("n", descending=True)
    .collect()
)

assert upset_db_all_tiers["n"].sum() == members_all.height

In [92]:
with pl.Config(tbl_rows=30, tbl_width_chars=500):
    print(upset_db_all_tiers.group_by("db_source").agg(pl.col("n").sum()).sort("n", descending=True))

shape: (8, 2)
┌──────────────┬─────────┐
│ db_source    ┆ n       │
│ ---          ┆ ---     │
│ str          ┆ u64     │
╞══════════════╪═════════╡
│ Pfam         ┆ 1765972 │
│ Multiple DBs ┆ 200096  │
│ KEGG         ┆ 8995    │
│ FOAM         ┆ 1699    │
│ None         ┆ 983     │
│ METABOLIC    ┆ 80      │
│ CAMPER       ┆ 41      │
│ dbCAN        ┆ 4       │
└──────────────┴─────────┘

### Likely-AMG restricted overlap

A tool's default or high call is a likely AMG if its own best annotation carries `AMG_weight >= 0.6`. The three-way overlap is recomputed with the same tier columns, restricted to likely calls.

These counts differ from those in amg_benchmark_figures.Rmd, which gives 3,176 of 3,218 CheckAMG (high), 524 of 664 DRAM-V (default), and 398 of 1,270 VIBRANT (high) calls as likely AMGs. The two agree for CheckAMG and DRAM-V and give 450 against 398 for VIBRANT.

In [93]:
def passes_weight(prefix: str) -> pl.Expr:
    return pl.col(f"{prefix}_weight_bin").is_in(["weight_ge_0.8", "weight_0.6_0.8"])

members_likely = members_weights.with_columns([
    (pl.col("CheckAMG_high") & passes_weight("CheckAMG")).alias("CheckAMG_high_likely"),
    (pl.col("DRAMV_default") & passes_weight("DRAMV")  ).alias("DRAMV_default_likely"),
    (pl.col("VIBRANT_high")  & passes_weight("VIBRANT") ).alias("VIBRANT_high_likely"),
])

likely_venn_rows = []
for c in [False, True]:
    for d in [False, True]:
        for v in [False, True]:
            if not (c or d or v):
                continue
            expr = (
                (pl.col("CheckAMG_high_likely") == c)
                & (pl.col("DRAMV_default_likely") == d)
                & (pl.col("VIBRANT_high_likely") == v)
            )
            name = " & ".join([t for t, flag in zip(["CheckAMG", "DRAMV", "VIBRANT"], [c, d, v]) if flag])
            likely_venn_rows.append({"set": name, "CheckAMG": c, "DRAMV": d, "VIBRANT": v,
                                     "n": int(members_likely.filter(expr).height)})
members_likely_venn = pl.DataFrame(likely_venn_rows).sort("n", descending=True)

In [94]:
members_likely_venn

shape: (7, 5)
┌────────────────────────────┬──────────┬───────┬─────────┬──────┐
│ set                        ┆ CheckAMG ┆ DRAMV ┆ VIBRANT ┆ n    │
│ ---                        ┆ ---      ┆ ---   ┆ ---     ┆ ---  │
│ str                        ┆ bool     ┆ bool  ┆ bool    ┆ i64  │
╞════════════════════════════╪══════════╪═══════╪═════════╪══════╡
│ CheckAMG                   ┆ true     ┆ false ┆ false   ┆ 2997 │
│ DRAMV                      ┆ false    ┆ true  ┆ false   ┆ 524  │
│ VIBRANT                    ┆ false    ┆ false ┆ true    ┆ 271  │
│ CheckAMG & VIBRANT         ┆ true     ┆ false ┆ true    ┆ 179  │
│ DRAMV & VIBRANT            ┆ false    ┆ true  ┆ true    ┆ 0    │
│ CheckAMG & DRAMV           ┆ true     ┆ true  ┆ false   ┆ 0    │
│ CheckAMG & DRAMV & VIBRANT ┆ true     ┆ true  ┆ true    ┆ 0    │
└────────────────────────────┴──────────┴───────┴─────────┴──────┘

In [95]:
members_likely_totals = pl.DataFrame([
    {"tier": "CheckAMG_high",
     "n_all":        int(members_likely.filter(pl.col("CheckAMG_high")).height),
     "n_likely_amg": int(members_likely.filter(pl.col("CheckAMG_high") & pl.col("CheckAMG_high_likely")).height)},
    {"tier": "DRAMV_default",
     "n_all":        int(members_likely.filter(pl.col("DRAMV_default")).height),
     "n_likely_amg": int(members_likely.filter(pl.col("DRAMV_default") & pl.col("DRAMV_default_likely")).height)},
    {"tier": "VIBRANT_high",
     "n_all":        int(members_likely.filter(pl.col("VIBRANT_high")).height),
     "n_likely_amg": int(members_likely.filter(pl.col("VIBRANT_high") & pl.col("VIBRANT_high_likely")).height)},
]).with_columns(
    (pl.col("n_likely_amg") / pl.col("n_all") * 100).round(2).alias("pct_likely_amg")
)

In [96]:
members_likely_totals

shape: (3, 4)
┌───────────────┬───────┬──────────────┬────────────────┐
│ tier          ┆ n_all ┆ n_likely_amg ┆ pct_likely_amg │
│ ---           ┆ ---   ┆ ---          ┆ ---            │
│ str           ┆ i64   ┆ i64          ┆ f64            │
╞═══════════════╪═══════╪══════════════╪════════════════╡
│ CheckAMG_high ┆ 3218  ┆ 3176         ┆ 98.69          │
│ DRAMV_default ┆ 664   ┆ 524          ┆ 78.92          │
│ VIBRANT_high  ┆ 1270  ┆ 450          ┆ 35.43          │
└───────────────┴───────┴──────────────┴────────────────┘

## Database sources of AMG predictions from each tool

In [97]:
checkamg_results_raw = pl.read_parquet(AMG_TABLES_DIR.joinpath("checkamg_results_raw.parquet"))
dramv_results_raw = pl.read_parquet(AMG_TABLES_DIR.joinpath("dramv_results_raw.parquet"))
vibrant_results_raw = pl.read_parquet(AMG_TABLES_DIR.joinpath("vibrant_results_raw.parquet"))

In [98]:
amg_database_kegg = set(amg_database.filter(pl.col("KO").is_not_null())["KO"].to_list())
amg_database_pfam = set(
    amg_database.filter(pl.col("PFAM").is_not_null())["PFAM"]
    .str.strip_chars()  # handles leading spaces seen in data
    .to_list()
)

amgs_filtered = amgs.filter(pl.col("metabolic_ratio") >= 0.6)
amgs_kegg = set(amgs_filtered.filter(pl.col("db") == "KEGG")["id"].to_list())
amgs_pfam = set(amgs_filtered.filter(pl.col("db") == "Pfam")["id"].to_list())

vibrant_ko_set = set(vibrant_amgs["ko"].to_list())

In [99]:
DBS = ["KEGG", "Pfam"]

In [100]:
def get_genes_with_db(tool: str, tier_col: str, db: str, amg_predictions: pl.DataFrame) -> pl.Series:
    tier_genes = (
        amg_predictions
        .filter(pl.col(tier_col))
        ["gene"]
        .to_list()
    )

    if tool == "DRAMV":
        prefix = "K" if db == "KEGG" else "PF"
        matched = (
            dramv_results_raw
            .filter(pl.col("gene").is_in(tier_genes))
            .filter(pl.col("gene_id").str.starts_with(prefix))
            ["gene"]
            .unique()
        )
    elif tool == "CheckAMG":
        col = "KEGG KO" if db == "KEGG" else "Pfam Accession"
        matched = (
            checkamg_results_raw
            .filter(pl.col("gene").is_in(tier_genes))
            .filter(pl.col(col).is_not_null())
            ["gene"]
            .unique()
        )
    elif tool == "VIBRANT":
        col = "AMG KO" if db == "KEGG" else "Pfam"
        matched = (
            vibrant_results_raw
            .filter(pl.col("gene").is_in(tier_genes))
            .filter(pl.col(col).is_not_null())
            ["gene"]
            .unique()
        )

    return matched

def get_genes_with_db_validated(tool: str, tier_col: str, db: str, amg_predictions: pl.DataFrame) -> pl.Series:
    tier_genes = (
        amg_predictions
        .filter(pl.col(tier_col))
        ["gene"]
        .to_list()
    )

    if tool == "DRAMV":
        prefix = "K" if db == "KEGG" else "PF"
        valid_ids = amg_database_kegg if db == "KEGG" else amg_database_pfam
        matched = (
            dramv_results_raw
            .filter(pl.col("gene").is_in(tier_genes))
            .filter(pl.col("gene_id").str.starts_with(prefix))
            .filter(pl.col("gene_id").is_in(valid_ids))
            ["gene"]
            .unique()
        )
    elif tool == "CheckAMG":
        col = "KEGG KO" if db == "KEGG" else "Pfam Accession"
        valid_ids = amgs_kegg if db == "KEGG" else amgs_pfam
        matched = (
            checkamg_results_raw
            .filter(pl.col("gene").is_in(tier_genes))
            .filter(pl.col(col).is_not_null())
            .filter(pl.col(col).is_in(valid_ids))
            ["gene"]
            .unique()
        )
    elif tool == "VIBRANT":
        if db == "KEGG":
            matched = (
                vibrant_results_raw
                .filter(pl.col("gene").is_in(tier_genes))
                .filter(pl.col("AMG KO").is_not_null())
                .filter(pl.col("AMG KO").is_in(vibrant_ko_set))
                ["gene"]
                .unique()
            )
        else:  # Pfam has no VIBRANT validation list
            matched = pl.Series("gene", [], dtype=pl.String)

    return matched

In [101]:
for tier_col, tool in SOURCE_TIERS:
    for db in DBS:
        tier_total = amg_predictions.filter(pl.col(tier_col))["gene"].n_unique()

        primary_genes = get_genes_with_db(tool, tier_col, db, amg_predictions)
        primary_in_ref = get_genes_with_db_validated(tool, tier_col, db, amg_predictions)

        print(f"{tool} [{tier_col}] | {db}: "
              f"{len(primary_genes)} / {tier_total} unique genes "
              f"({len(primary_genes)/tier_total*100:.2f}%)")
        print(f"  - {tool} AMG ref: "
              f"{len(primary_in_ref)} / {tier_total} unique genes "
              f"({len(primary_in_ref)/tier_total*100:.2f}%)")

        for other_col in OTHER_TIER_FLAGS[tool]:
            other_col_name = other_col.meta.output_name()
            other_total = amg_predictions.filter(other_col)["gene"].n_unique()

            other_genes = get_genes_with_db(tool, other_col_name, db, amg_predictions)
            other_in_ref = get_genes_with_db_validated(tool, other_col_name, db, amg_predictions)

            print(f"  {tool} [{other_col_name}] | {db}: "
                  f"{len(other_genes)} / {other_total} genes "
                  f"({len(other_genes)/other_total*100:.2f}%)")
            print(f"    - in {tool} AMG ref: "
                  f"{len(other_in_ref)} / {other_total} genes "
                  f"({len(other_in_ref)/other_total*100:.2f}%)")

CheckAMG [CheckAMG_high] | KEGG: 2611 / 3217 unique genes (81.16%)
  - CheckAMG AMG ref: 2085 / 3217 unique genes (64.81%)
  CheckAMG [CheckAMG_medium] | KEGG: 5426 / 6699 genes (81.00%)
    - in CheckAMG AMG ref: 4151 / 6699 genes (61.96%)

  CheckAMG [CheckAMG_low] | KEGG: 151497 / 167995 genes (90.18%)
    - in CheckAMG AMG ref: 122800 / 167995 genes (73.10%)
CheckAMG [CheckAMG_high] | Pfam: 2197 / 3217 unique genes (68.29%)
  - CheckAMG AMG ref: 957 / 3217 unique genes (29.75%)
  CheckAMG [CheckAMG_medium] | Pfam: 4697 / 6699 genes (70.11%)
    - in CheckAMG AMG ref: 2134 / 6699 genes (31.86%)

  CheckAMG [CheckAMG_low] | Pfam: 135573 / 167995 genes (80.70%)
    - in CheckAMG AMG ref: 59576 / 167995 genes (35.46%)
DRAMV [DRAMV_default] | KEGG: 10 / 664 unique genes (1.51%)
  - DRAMV AMG ref: 1 / 664 unique genes (0.15%)
  DRAMV [DRAMV_allow_T] | KEGG: 220 / 10729 genes (2.05%)
    - in DRAMV AMG ref: 20 / 10729 genes (0.19%)

  DRAMV [DRAMV_aux_4] | KEGG: 9533 / 114024 genes (8.36%)
    - in DRAMV AMG ref: 397 / 114024 genes (0.35%)

  DRAMV [DRAMV_aux_4_allow_T] | KEGG: 98774 / 1590821 genes (6.21%)
    - in DRAMV AMG ref: 4000 / 1590821 genes (0.25%)
DRAMV [DRAMV_default] | Pfam: 664 / 664 unique genes (100.00%)
  - DRAMV AMG ref: 663 / 664 unique genes (99.85%)
  DRAMV [DRAMV_allow_T] | Pfam: 10725 / 10729 genes (99.96%)
    - in DRAMV AMG ref: 10674 / 10729 genes (99.49%)

  DRAMV [DRAMV_aux_4] | Pfam: 113916 / 114024 genes (99.91%)
    - in DRAMV AMG ref: 113602 / 114024 genes (99.63%)

  DRAMV [DRAMV_aux_4_allow_T] | Pfam: 1589349 / 1590821 genes (99.91%)
    - in DRAMV AMG ref: 1583876 / 1590821 genes (99.56%)
VIBRANT [VIBRANT_high] | KEGG: 1270 / 1270 unique genes (100.00%)
  - VIBRANT AMG ref: 1270 / 1270 unique genes (100.00%)
  VIBRANT [VIBRANT_medium] | KEGG: 3715 / 3715 genes (100.00%)
    - in VIBRANT AMG ref: 3715 / 3715 genes (100.00%)
  VIBRANT [VIBRANT_low] | KEGG: 12623 / 12623 genes (100.00%)
    - in VIBRANT AMG ref: 12623 / 12623 genes (100.00%)
VIBRANT [VIBRANT_high] | Pfam: 1079 / 1270 unique genes (84.96%)
  - VIBRANT AMG ref: 0 / 1270 unique genes (0.00%)
  VIBRANT [VIBRANT_medium] | Pfam: 3078 / 3715 genes (82.85%)
    - in VIBRANT AMG ref: 0 / 3715 genes (0.00%)
  VIBRANT [VIBRANT_low] | Pfam: 10235 / 12623 genes (81.08%)
    - in VIBRANT AMG ref: 0 / 12623 genes (0.00%)

## Additional numbers

Assembled from the tables above for easy reporting.

The VIBRANT (high) likely-AMG count printed below (450) follows the definition in the likely-AMG section above and differs from the 398 in amg_benchmark_figures.Rmd (see the likely-AMG section).

In [102]:
def _first(df, col_name, col_val, target):
    return df.filter(pl.col(col_name) == col_val)[target][0]

stats = {
    "CheckAMG (high) total calls":             int(_first(counts_tier, "tier", "CheckAMG_high", "n_amg")),
    "CheckAMG (high) weight >= 0.6 (likely)":   int(_first(members_likely_totals, "tier", "CheckAMG_high", "n_likely_amg")),
    "CheckAMG (high) percent likely":          float(_first(members_likely_totals, "tier", "CheckAMG_high", "pct_likely_amg")),
    "DRAM-V (default) total calls":            int(_first(counts_tier, "tier", "DRAMV_default", "n_amg")),
    "DRAM-V (default) weight >= 0.6 (likely)":  int(_first(members_likely_totals, "tier", "DRAMV_default", "n_likely_amg")),
    "DRAM-V (default) percent likely":         float(_first(members_likely_totals, "tier", "DRAMV_default", "pct_likely_amg")),
    "VIBRANT (high) total calls":              int(_first(counts_tier, "tier", "VIBRANT_high", "n_amg")),
    "VIBRANT (high) weight >= 0.6 (likely)":    int(_first(members_likely_totals, "tier", "VIBRANT_high", "n_likely_amg")),
    "VIBRANT (high) percent likely":           float(_first(members_likely_totals, "tier", "VIBRANT_high", "pct_likely_amg")),
}
stats["CheckAMG / VIBRANT ratio (likely counts)"] = round(
    stats["CheckAMG (high) weight >= 0.6 (likely)"] / max(stats["VIBRANT (high) weight >= 0.6 (likely)"], 1), 2)
stats["CheckAMG / DRAM-V ratio (likely counts)"]  = round(
    stats["CheckAMG (high) weight >= 0.6 (likely)"] / max(stats["DRAM-V (default) weight >= 0.6 (likely)"], 1), 2)

In [103]:
for k, v in stats.items():
    print(f"{k:<45} {v}")

CheckAMG (high) total calls                   3218
CheckAMG (high) weight >= 0.6 (likely)        3176
CheckAMG (high) percent likely                98.69
DRAM-V (default) total calls                  664
DRAM-V (default) weight >= 0.6 (likely)       524
DRAM-V (default) percent likely               78.92
VIBRANT (high) total calls                    1270
VIBRANT (high) weight >= 0.6 (likely)         450
VIBRANT (high) percent likely                 35.43
CheckAMG / VIBRANT ratio (likely counts)      7.06
CheckAMG / DRAM-V ratio (likely counts)       6.06

## All-tier gene-level exports

`per_tool_gene` covers only default and high tier members. The cells below rebuild the per-gene tables over every gene called at any tier and write them for amg_benchmark_figures.Rmd, which computes all percentages. The annotation table is filtered to final annotations before the join, which keeps the intermediate at about ten million rows.

In [104]:
GENE_KEY = ["gene", "source", "sample", "ecosystem"]

assert members_all.select(GENE_KEY).unique().height == members_all.height, "gene key is not unique in members_all"

members_all.write_parquet(OUTPUT_TABLES_DIR.joinpath("AMG_predictions_gene_level.parquet"))
print(f"AMG_predictions_gene_level.parquet: {members_all.height:,} rows, {members_all.width} columns")
print(f"  default/high member gene keys for comparison: {members.select(GENE_KEY).unique().height:,}")

AMG_predictions_gene_level.parquet: 1,977,870 rows, 31 columns
  default/high member gene keys for comparison: 4,931

In [105]:
final_annotations_all_tiers = (
    annotations.filter(pl.col("final_annot"))
    .join(members_all.select(GENE_KEY), on=GENE_KEY, how="inner")
    .with_columns(
        pl.when(pl.col("database") == "Pfam")
          .then(pl.col("hit_id").str.split(".").list.first())
          .otherwise(pl.col("hit_id"))
          .alias("id_key"),
    )
    .join(amgs_slim, left_on=["database", "id_key"], right_on=["db", "id_key"], how="left")
    .join(filters_slim, left_on=["database", "id_key"], right_on=["db", "id_key"], how="left")
    .with_columns([pl.col(c).fill_null(False) for c in FILTER_CATEGORIES])
    .select(["gene", "sample", "source", "ecosystem", "tool", "database", "hit_id", "AMG_weight"]
            + FILTER_CATEGORIES)
)

print(f"final annotations at all tiers: {final_annotations_all_tiers.height:,} rows, "
      f"{final_annotations_all_tiers.width} columns")
print(f"  columns: {final_annotations_all_tiers.columns}")
print(f"  for comparison, the default/high basis: {final_annots.height:,} rows")
print(final_annotations_all_tiers.group_by("tool").agg(pl.len().alias("n_rows")).sort("tool"))
print(final_annotations_all_tiers.group_by("database").agg(pl.len().alias("n_rows"))
      .sort("n_rows", descending=True))

final annotations at all tiers: 9,491,928 rows, 13 columns
  columns: ['gene', 'sample', 'source', 'ecosystem', 'tool', 'database', 'hit_id', 'AMG_weight', 'filter_essential', 'filter_glucan', 'filter_lipid', 'filter_methyl', 'filter_nucleotide']
  for comparison, the default/high basis: 37,247 rows
shape: (3, 2)
┌──────────┬─────────┐
│ tool     ┆ n_rows  │
│ ---      ┆ ---     │
│ str      ┆ u64     │
╞══════════╪═════════╡
│ CheckAMG ┆ 1752214 │
│ DRAM-V   ┆ 7717042 │
│ VIBRANT  ┆ 22672   │
└──────────┴─────────┘
shape: (7, 2)
┌───────────┬─────────┐
│ database  ┆ n_rows  │
│ ---       ┆ ---     │
│ str       ┆ u64     │
╞═══════════╪═════════╡
│ Pfam      ┆ 8190802 │
│ KEGG      ┆ 586763  │
│ PHROG     ┆ 434198  │
│ FOAM      ┆ 222874  │
│ CAMPER    ┆ 46251   │
│ METABOLIC ┆ 9904    │
│ dbCAN     ┆ 1136    │
└───────────┴─────────┘

In [106]:
nonoverlap_per_gene = classify_nonoverlap(members_annot, return_per_gene=True)
nonoverlap_per_gene.write_parquet(OUTPUT_TABLES_DIR.joinpath("AMG_nonoverlap_per_gene.parquet"))
print(f"AMG_nonoverlap_per_gene.parquet: {nonoverlap_per_gene.height:,} rows, "
      f"{nonoverlap_per_gene['source_tier'].n_unique()} source tiers, "
      f"{nonoverlap_per_gene['other_tool'].n_unique()} other tools")
print(nonoverlap_per_gene.head(4))

AMG_nonoverlap_per_gene.parquet: 10,304 rows, 3 source tiers, 3 other tools
shape: (4, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ gene       ┆ source     ┆ sample     ┆ ecosystem ┆ source_ti ┆ other_too ┆ category  ┆ likely_fa │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ er        ┆ l         ┆ ---       ┆ lse_posit │
│ str        ┆ str        ┆ str        ┆ str       ┆ ---       ┆ ---       ┆ str       ┆ ive       │
│            ┆            ┆            ┆           ┆ str       ┆ str       ┆           ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ bool      │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Ga0485157_ ┆ Mixed meta ┆ freshwater ┆ Aquatic   ┆ CheckAMG_ ┆ DRAMV     ┆ d. same   ┆ false     │
│ 0000020_8  ┆ genomes    ┆ _Ga0485157 ┆           ┆ high      ┆           ┆ db        ┆           │
│            ┆            ┆ _contigs   ┆           ┆           ┆           ┆ hit_id,   ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ not       ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ flagged   ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ AMG       ┆           │
│ Ga0485157_ ┆ Mixed meta ┆ freshwater ┆ Aquatic   ┆ CheckAMG_ ┆ DRAMV     ┆ a. other  ┆ false     │
│ 0000095_62 ┆ genomes    ┆ _Ga0485157 ┆           ┆ high      ┆           ┆ tool      ┆           │
│            ┆            ┆ _contigs   ┆           ┆           ┆           ┆ called at ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ different ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ tier      ┆           │
│ Ga0485157_ ┆ Mixed meta ┆ freshwater ┆ Aquatic   ┆ CheckAMG_ ┆ DRAMV     ┆ a. other  ┆ false     │
│ 0000095_70 ┆ genomes    ┆ _Ga0485157 ┆           ┆ high      ┆           ┆ tool      ┆           │
│            ┆            ┆ _contigs   ┆           ┆           ┆           ┆ called at ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ different ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ tier      ┆           │
│ Ga0485157_ ┆ Mixed meta ┆ freshwater ┆ Aquatic   ┆ CheckAMG_ ┆ DRAMV     ┆ a. other  ┆ false     │
│ 0000095_73 ┆ genomes    ┆ _Ga0485157 ┆           ┆ high      ┆           ┆ tool      ┆           │
│            ┆            ┆ _contigs   ┆           ┆           ┆           ┆ called at ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ different ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ tier      ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

### Curated bitscore thresholds for the all-tier annotation export

Each annotation row is judged against the curated threshold of the database the tool searched, so that a call can be scored on whether its supporting annotation clears the threshold its own reference publishes. KEGG rows use the KOfam `ko_list` threshold. Pfam rows use the gathering cutoff embedded in the profile, taken from the Pfam build the tool actually searched, which for VIBRANT is Pfam-A v32. FOAM, METABOLIC and CAMPER use the cutoff tables `hmm_annotate.py` loads, full cutoff preferred and domain cutoff as fallback. DRAM-V Pfam rows carry the hmmscan `--cut_ga` verdict from the re-run rather than a comparison against DRAM-V's own MMseqs2 score, and `threshold_basis` records that. PHROG and dbCAN publish no curated bitscore threshold, so all three threshold columns are null for those rows.

In [107]:
import csv as _csv

_DB = OUTPUT_TABLES_DIR.parent.parent / "CheckAMG_annotate_db_v1.1_20260316"
_KO_V91 = "/storage2/scratch/kosmopoulos/projects/checkAMG/benchmarks/metabolism_benchmark/refs/kofam_v91_2019-08-10_ko_list.tsv"
_CK_KEGG = _DB / "KEGG_cutoffs.tsv"
_DRAM_KO = "/storage2/databases/dram-latest/v1.5.0/kofam_ko_list.tsv"
_VIB_PFAM = "/storage2/databases/VIBRANT/databases/Pfam-A_v32.HMM"
_PF_CUR = _DB / "Pfam-A.hmm"
_KEY = ["gene", "source", "sample", "ecosystem"]


def _read_kofam(path):
    ids, thr, styp = [], [], []
    with open(path, encoding="utf-8", errors="replace") as fh:
        for row in _csv.DictReader(fh, delimiter="\t"):
            t = (row.get("threshold") or "").strip()
            if t and t != "-":
                ids.append(row["knum"].strip())
                thr.append(float(t))
                styp.append((row.get("score_type") or "").strip())
    return pl.DataFrame({"hit_id": ids, "thr": thr, "score_type": styp})


def _read_ga(path):
    accs, gas = [], []
    acc = None
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            if line.startswith("ACC "):
                acc = line.split(None, 1)[1].strip()
            elif line.startswith("GA "):
                accs.append(acc)
                gas.append(float(line.split()[1]))
    return (pl.DataFrame({"acc_base": accs, "thr": gas})
              .with_columns(pl.col("acc_base").str.replace(r"\.\d+$", ""))
              .unique(subset=["acc_base"]))


def _effective(path):
    t = pl.read_csv(path, separator="\t", infer_schema_length=20000)
    return t.select(pl.col("id").alias("hit_id"),
                    pl.coalesce([pl.col("cutoff_full"), pl.col("cutoff_domain")]).alias("thr"))


_ex = final_annotations_all_tiers
_cols13 = _ex.columns
_n0 = _ex.height

_src = (pl.scan_parquet(AMG_TABLES_DIR.joinpath("amg_all_annotations.parquet"))
          .filter(pl.col("final_annot"))
          .group_by(_KEY + ["tool", "database", "hit_id"])
          .agg(pl.col("bitscore").max().alias("bitscore"),
               pl.col("evalue").min().alias("evalue"))
          .collect())
_ex = _ex.join(_src, on=_KEY + ["tool", "database", "hit_id"], how="left")
assert _ex.height == _n0, "bitscore join changed the row count"

# Each tool is judged against the KEGG thresholds shipped with the release it searched
_v91_full = _read_kofam(_KO_V91)
_dram_ko_full = _read_kofam(_DRAM_KO)
_ck_kegg = (pl.read_csv(_CK_KEGG, separator="\t", infer_schema_length=20000)
              .select(pl.col("id").alias("hit_id"), pl.col("threshold").alias("thr")))
# One full-sequence score per row, so score_type is recorded where a domain-type KO is judged on it
_v91 = _v91_full.drop("score_type")
_dram_ko = _dram_ko_full.drop("score_type")
_pf_cur = _read_ga(_PF_CUR)
_pf_v32 = _read_ga(_VIB_PFAM)
_foam = _effective(_DB / "FOAM_cutoffs.tsv")
_metab = _effective(_DB / "METABOLIC_cutoffs.tsv")
_camper = _effective(_DB / "CAMPER_cutoffs.tsv")

_ex = _ex.with_columns(pl.col("hit_id").str.replace(r"\.\d+$", "").alias("acc_base"))
_T, _D = pl.col("tool"), pl.col("database")
_RULES = [
    ((_T == "CheckAMG") & (_D == "KEGG"), _ck_kegg, "hit_id", "checkamg_kegg_cutoffs_v1.1"),
    ((_T == "CheckAMG") & (_D == "FOAM"), _foam, "hit_id", "foam"),
    ((_T == "CheckAMG") & (_D == "METABOLIC"), _metab, "hit_id", "metabolic"),
    ((_T == "CheckAMG") & (_D == "CAMPER"), _camper, "hit_id", "camper"),
    ((_T == "CheckAMG") & (_D == "Pfam"), _pf_cur, "acc_base", "pfam_ga"),
    ((_T == "DRAM-V") & (_D == "KEGG"), _dram_ko, "hit_id", "kofam"),
    ((_T == "DRAM-V") & (_D == "Pfam"), _pf_cur, "acc_base", "dramv_hmmscan_cut_ga"),
    ((_T == "VIBRANT") & (_D == "KEGG"), _v91, "hit_id", "kofam_v91"),
    ((_T == "VIBRANT") & (_D == "Pfam"), _pf_v32, "acc_base", "pfam_ga"),
]
_parts, _cov = [], None
for _mask, _tbl, _on, _basis in _RULES:
    _p = _ex.filter(_mask).join(_tbl, on=_on, how="left")
    _parts.append(_p.with_columns(pl.when(pl.col("thr").is_not_null()).then(pl.lit(_basis))
                                    .otherwise(pl.lit(None, dtype=pl.Utf8)).alias("threshold_basis")))
    _cov = _mask if _cov is None else (_cov | _mask)
_rest = _ex.filter(~_cov).with_columns(pl.lit(None, dtype=pl.Float64).alias("thr"),
                                       pl.lit(None, dtype=pl.Utf8).alias("threshold_basis"))
_out = pl.concat(_parts + [_rest], how="vertical_relaxed")
assert _out.height == _n0, "threshold partition lost rows"

_out = _out.rename({"thr": "db_threshold"}).with_columns(
    pl.when(pl.col("db_threshold").is_null() | pl.col("bitscore").is_null())
      .then(pl.lit(None, dtype=pl.Boolean))
      .otherwise(pl.col("bitscore") >= pl.col("db_threshold")).alias("passes_db_threshold"))

_dv = (pl.read_parquet(OUTPUT_TABLES_DIR.parent.joinpath("DRAMV_pfam", "dramv_pfam_amg_calls.parquet"),
                       columns=["new_gene", "sample", "pfam_acc", "support_class"])
         .with_columns((pl.col("support_class") == "hmmer_supported").alias("dv_pass"))
         .group_by(["new_gene", "sample", "pfam_acc"]).agg(pl.col("dv_pass").max().alias("dv_pass"))
         .rename({"new_gene": "gene", "pfam_acc": "acc_base"}))
_out = _out.join(_dv, on=["gene", "sample", "acc_base"], how="left")
assert _out.height == _n0, "DRAM-V Pfam join changed the row count"
_dvmask = (pl.col("tool") == "DRAM-V") & (pl.col("database") == "Pfam")
_out = _out.with_columns(
    pl.when(_dvmask).then(pl.col("dv_pass").fill_null(False))
      .otherwise(pl.col("passes_db_threshold")).alias("passes_db_threshold")).drop(["dv_pass", "acc_base"])

_final = _cols13 + ["bitscore", "evalue", "db_threshold", "passes_db_threshold", "threshold_basis"]
_out = _out.select(_final)
assert _out.columns == _final and _out.height == _n0
# Written in parts so each file stays under GitHub's 100 MB limit
EXPORT_PARTS = 3
rows_per_part = -(-_out.height // EXPORT_PARTS)
for part_number, part in enumerate(_out.iter_slices(n_rows=rows_per_part), start=1):
    part.write_parquet(OUTPUT_TABLES_DIR.joinpath(f"AMG_final_annotations_all_tiers_part{part_number}.parquet"))
print(f"AMG_final_annotations_all_tiers_part1-{EXPORT_PARTS}.parquet: {_out.height:,} rows, {_out.width} columns")

_tab = (_out.group_by(["tool", "database"])
            .agg(pl.len().alias("rows"),
                 pl.col("passes_db_threshold").sum().alias("true"),
                 (pl.col("passes_db_threshold") == False).sum().alias("false"),
                 pl.col("passes_db_threshold").null_count().alias("null"),
                 pl.col("threshold_basis").drop_nulls().first().alias("basis"))
            .sort(["tool", "database"]))
print(_tab)
assert _out.filter((pl.col("tool") == "CheckAMG") & (pl.col("database") == "Pfam")
                   & (pl.col("passes_db_threshold") == False)).height == 0, \
    "CheckAMG enforces Pfam GA, so no row should fail it"
assert _out.filter(pl.col("database").is_in(["PHROG", "dbCAN"])
                   & pl.col("db_threshold").is_not_null()).height == 0, \
    "PHROG and dbCAN publish no curated threshold"
_styp = pl.concat([_v91_full.select("hit_id", "score_type"),
                   _dram_ko_full.select("hit_id", "score_type")]).unique(subset=["hit_id"])
_dom = (_out.filter((pl.col("database") == "KEGG") & pl.col("db_threshold").is_not_null())
            .join(_styp, on="hit_id", how="left")
            .group_by(["tool", "score_type"]).agg(pl.len().alias("rows")).sort(["tool", "score_type"]))
print("KEGG rows by KOfam score_type, domain-type rows judged on the full-sequence score:")
print(_dom)
print("threshold column guards passed")

AMG_final_annotations_all_tiers_part1-3.parquet: 9,491,928 rows, 18 columns

shape: (11, 7)
┌──────────┬───────────┬─────────┬────────┬─────────┬────────┬────────────────────────────┐
│ tool     ┆ database  ┆ rows    ┆ true   ┆ false   ┆ null   ┆ basis                      │
│ ---      ┆ ---       ┆ ---     ┆ ---    ┆ ---     ┆ ---    ┆ ---                        │
│ str      ┆ str       ┆ u64     ┆ u64    ┆ u64     ┆ u64    ┆ str                        │
╞══════════╪═══════════╪═════════╪════════╪═════════╪════════╪════════════════════════════╡
│ CheckAMG ┆ CAMPER    ┆ 46251   ┆ 8865   ┆ 37386   ┆ 0      ┆ camper                     │
│ CheckAMG ┆ FOAM      ┆ 222874  ┆ 162490 ┆ 60384   ┆ 0      ┆ foam                       │
│ CheckAMG ┆ KEGG      ┆ 524859  ┆ 362287 ┆ 158259  ┆ 4313   ┆ checkamg_kegg_cutoffs_v1.1 │
│ CheckAMG ┆ METABOLIC ┆ 9904    ┆ 5915   ┆ 3396    ┆ 593    ┆ metabolic                  │
│ CheckAMG ┆ PHROG     ┆ 434198  ┆ 0      ┆ 0       ┆ 434198 ┆ null                       │
│ …        ┆ …         ┆ …       ┆ …      ┆ …       ┆ …      ┆ …                          │
│ DRAM-V   ┆ KEGG      ┆ 49263   ┆ 49263  ┆ 0       ┆ 0      ┆ kofam                      │
│ DRAM-V   ┆ Pfam      ┆ 7666643 ┆ 117202 ┆ 7549441 ┆ 0      ┆ dramv_hmmscan_cut_ga       │
│ DRAM-V   ┆ dbCAN     ┆ 1136    ┆ 0      ┆ 0       ┆ 1136   ┆ null                       │
│ VIBRANT  ┆ KEGG      ┆ 12641   ┆ 4768   ┆ 7865    ┆ 8      ┆ kofam_v91                  │
│ VIBRANT  ┆ Pfam      ┆ 10031   ┆ 10031  ┆ 0       ┆ 0      ┆ pfam_ga                    │
└──────────┴───────────┴─────────┴────────┴─────────┴────────┴────────────────────────────┘
KEGG rows by KOfam score_type, domain-type rows judged on the full-sequence score:
shape: (7, 3)
┌──────────┬────────────┬────────┐
│ tool     ┆ score_type ┆ rows   │
│ ---      ┆ ---        ┆ ---    │
│ str      ┆ str        ┆ u64    │
╞══════════╪════════════╪════════╡
│ CheckAMG ┆ null       ┆ 2891   │
│ CheckAMG ┆ domain     ┆ 212795 │
│ CheckAMG ┆ full       ┆ 304860 │
│ DRAM-V   ┆ domain     ┆ 24973  │
│ DRAM-V   ┆ full       ┆ 24290  │
│ VIBRANT  ┆ domain     ┆ 4752   │
│ VIBRANT  ┆ full       ┆ 7881   │
└──────────┴────────────┴────────┘
threshold column guards passed