# Run CheckAMG annotate and de-novo on soil and human gut viral datasets

In [20]:
! pip install polars --quiet
! conda install -c bioconda seqkit -y --quiet

Collecting package metadata (current_repodata.json): ...working... WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: ...working... done

# All requested packages already installed.

## Data source

[MetaVR (IMG/VR v5)](https://www.meta-virome.org/) ([Fiamenghi et al. (2026) *Nucleic Acids Res.*](https://doi.org/10.1093/nar/gkaf1283)) will be the source database for virus genomes.

* Obtained a list of soil UViGs (environmental; terrestrial; soil) from the [MetaVR website](https://www.meta-virome.org/Uvigs?hieco=Environmental&hicat=Terrestrial&hitype=Soil&pageSize=20) and human gut UViGs (host-associated; mammals (human); digestive system) from the [MetaVR website](https://www.meta-virome.org/Uvigs?hieco=Host-associated&hicat=Mammals%3A%20Human&hitype=Digestive%20system&pageSize=20), then exported the tables with identifying information and metadata:
    * Soil: 2,054,095 viral genome sequences (1,345,242 vOTUs) in `./data/metavr_uvigs_soil.csv.gz`
    * Human gut: 499,416 viral genome sequences (239,755 vOTUs) in `./data/metavr_uvigs_gut.csv.gz`
* The nucleotide sequences of the MetaVR viruses (`IMGVR5_UViG.fna`) can be downlaoded from [meta-virome.org/Downloads](https://www.meta-virome.org/Downloads) but is too large to be included in this repository
* A key that matches the FASTA headers to the sequence names in the metadata will also be needed to match the metadata properly. This doesn't come with the MetaVR downloads but it can be constructed by parsing the `uvig` column in the metadata tables and string matching to headers in `IMGVR5_UViG.fna`. This also is not included here because of the file size.

Quality filtering will be applied below.

## Load metadata and prepare datasets

In [1]:
import os
os.environ["POLARS_MAX_THREADS"] = str(50)
import polars as pl
pl.Config.set_fmt_str_lengths(100)
pl.Config.set_tbl_rows(10)

polars.config.Config

In [2]:
from pathlib import Path
METAVR_DIR = Path("/storage2/databases/metaVR")
METAVR_UVIG_FNA = METAVR_DIR / "IMGVR5_UViG.fna"
MAIN_DIR = Path("/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript")
DATA_DIR = Path("./data")

In [3]:
metavr_uvig_to_header = (
    pl.read_csv(
        METAVR_DIR / "uvig_to_fastaheader.tsv",
        separator="\t",
        has_header=False,
        new_columns=["uvig", "fasta_header"],
    )
)
metavr_uvig_to_header

shape: (24_635_130, 2)
┌─────────────────────────────────┬─────────────────────────────────────────────────────────────┐
│ uvig                            ┆ fasta_header                                                │
│ ---                             ┆ ---                                                         │
│ str                             ┆ str                                                         │
╞═════════════════════════════════╪═════════════════════════════════════════════════════════════╡
│ IMGVR_UViG_2582581227_000001    ┆ IMGVR_UViG_2582581227_000001|2582581227|2582690522          │
│ IMGVR_UViG_2582581228_000001    ┆ IMGVR_UViG_2582581228_000001|2582581228|2582690523          │
│ IMGVR_UViG_2582581229_000001    ┆ IMGVR_UViG_2582581229_000001|2582581229|2582690524          │
│ IMGVR_UViG_2582581230_000001    ┆ IMGVR_UViG_2582581230_000001|2582581230|2582690525          │
│ IMGVR_UViG_2582581231_000001    ┆ IMGVR_UViG_2582581231_000001|2582581231|2582690526          │
│ …                               ┆ …                                                           │
│ IMGVR_UViG_GVMAG-M-3300047504-3 ┆ IMGVR_UViG_GVMAG-M-3300047504-3|3300047504|Ga0494773_000172 │
│ IMGVR_UViG_GVMAG-M-3300047504-3 ┆ IMGVR_UViG_GVMAG-M-3300047504-3|3300047504|Ga0494773_000174 │
│ IMGVR_UViG_GVMAG-M-3300047504-3 ┆ IMGVR_UViG_GVMAG-M-3300047504-3|3300047504|Ga0494773_000181 │
│ IMGVR_UViG_GVMAG-M-3300047504-3 ┆ IMGVR_UViG_GVMAG-M-3300047504-3|3300047504|Ga0494773_000183 │
│ IMGVR_UViG_GVMAG-M-3300047504-3 ┆ IMGVR_UViG_GVMAG-M-3300047504-3|3300047504|Ga0494773_000187 │
└─────────────────────────────────┴─────────────────────────────────────────────────────────────┘

In [4]:
metavr_uvigs_soil = (
    pl.read_csv(
        DATA_DIR / "metavr_uvigs_soil.csv.gz",
        null_values=["NA", "na", "NaN", "nan", ""],
        infer_schema_length=10000000,
    )
    .join(metavr_uvig_to_header, on="uvig", how="left")
)

In [5]:
metavr_uvigs_soil

shape: (2_056_257, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ uvig      ┆ taxon_oid ┆ discovery ┆ discovery ┆ … ┆ genetic_c ┆ host_taxo ┆ host_taxo ┆ fasta_he │
│ ---       ┆ ---       ┆ ---       ┆ _doi      ┆   ┆ ode       ┆ nomy      ┆ nomy_meth ┆ ader     │
│ str       ┆ i64       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ od        ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IMGVR_UVi ┆ 208809000 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_2088090 ┆ 8         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆           ┆           ┆ iG_20880 │
│ 008_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆           ┆           ┆ 90008_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0001|208 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8090008| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ P3_DRAFT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _NODE_29 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0175_len │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _15711_c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ov_24_19 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6932     │
│ IMGVR_UVi ┆ 208809000 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2088090 ┆ 8         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Chl ┆           ┆ iG_20880 │
│ 008_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ oroflexot ┆           ┆ 90008_00 │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆ a;c__Limn ┆           ┆ 0002|208 │
│           ┆           ┆           ┆           ┆   ┆           ┆ ocylindri ┆           ┆ 8090008| │
│           ┆           ┆           ┆           ┆   ┆           ┆ a;o__Limn ┆           ┆ P3_DRAFT │
│           ┆           ┆           ┆           ┆   ┆           ┆ ocylindra ┆           ┆ _NODE_61 │
│           ┆           ┆           ┆           ┆   ┆           ┆ les;f__CS ┆           ┆ 48_len_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ P1-4;g__S ┆           ┆ 2315_cov │
│           ┆           ┆           ┆           ┆   ┆           ┆ PCO01     ┆           ┆ _71_6959 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00       │
│ IMGVR_UVi ┆ 208809000 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_2088090 ┆ 8         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆           ┆           ┆ iG_20880 │
│ 008_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆           ┆           ┆ 90008_00 │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0003|208 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8090008| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ P3_DRAFT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _NODE_29 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 52_len_9 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 756_cov_ │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 85_33066 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ IMGVR_UVi ┆ 208809000 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_2088090 ┆ 8         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆           ┆           ┆ iG_20880 │
│ 008_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆           ┆           ┆ 90008_00 │
│ 4         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0004|208 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8090008| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ P3_DRAFT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _NODE_22 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3157_len │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _5489_co │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ v_17_049 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 189      │
│ IMGVR_UVi ┆ 208809001 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2088090 ┆ 4         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Act ┆           ┆ iG_20880 │
│ 014_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ inomyceto ┆           ┆ 90014_00 │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆ ta;c__Act ┆           ┆ 0002|208 │
│           ┆           ┆           ┆           ┆   ┆           ┆ inomycete ┆           ┆ 8090014| │
│           ┆           ┆           ┆           ┆   ┆           ┆ s;o__Acti ┆           ┆ GPIPI_16 │
│           ┆           ┆           ┆           ┆   ┆           ┆ nomycetal ┆           ┆ 496951   │
│           ┆           ┆           ┆           ┆   ┆           ┆ es;f__Mic ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ rococcace ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ae        ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IMGVR_UVi ┆ 330005040 ┆ GVMAGs    ┆ null      ┆ … ┆ 106       ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_GVMAG-S ┆ 7         ┆ (2025)    ┆           ┆   ┆           ┆           ┆           ┆ iG_GVMAG │
│ -33000504 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -S-33000 │
│ 07-46     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 50407-46 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ |3300050 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 407|Ga05 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30106_15 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 64       │
│ IMGVR_UVi ┆ 330005040 ┆ GVMAGs    ┆ null      ┆ … ┆ 106       ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_GVMAG-S ┆ 7         ┆ (2025)    ┆           ┆   ┆           ┆           ┆           ┆ iG_GVMAG │
│ -33000504 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -S-33000 │
│ 07-46     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 50407-46 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ |3300050 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 407|Ga05 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30106_21 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 27       │
│ IMGVR_UVi ┆ 330005040 ┆ GVMAGs    ┆ null      ┆ … ┆ 106       ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_GVMAG-S ┆ 7         ┆ (2025)    ┆           ┆   ┆           ┆           ┆           ┆ iG_GVMAG │
│ -33000504 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -S-33000 │
│ 07-46     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 50407-46 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ |3300050 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 407|Ga05 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30106_26 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 51       │
│ IMGVR_UVi ┆ 330005040 ┆ GVMAGs    ┆ null      ┆ … ┆ 106       ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_GVMAG-S ┆ 7         ┆ (2025)    ┆           ┆   ┆           ┆           ┆           ┆ iG_GVMAG │
│ -33000504 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -S-33000 │
│ 07-46     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 50407-46 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ |3300050 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 407|Ga05 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30106_26 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 97       │
│ IMGVR_UVi ┆ 330005040 ┆ GVMAGs    ┆ null      ┆ … ┆ 106       ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_GVMAG-S ┆ 7         ┆ (2025)    ┆           ┆   ┆           ┆           ┆           ┆ iG_GVMAG │
│ -33000504 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -S-33000 │
│ 07-46     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 50407-46 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ |3300050 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 407|Ga05 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30106_27 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 52       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
metavr_uvigs_gut = (
    pl.read_csv(
        DATA_DIR / "metavr_uvigs_gut.csv.gz",
        null_values=["NA", "na", "NaN", "nan", ""],
        infer_schema_length=10000000,
    )
    .join(metavr_uvig_to_header, on="uvig", how="left")
)

In [7]:
metavr_uvigs_gut

shape: (499_568, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ uvig      ┆ taxon_oid ┆ discovery ┆ discovery ┆ … ┆ genetic_c ┆ host_taxo ┆ host_taxo ┆ fasta_he │
│ ---       ┆ ---       ┆ ---       ┆ _doi      ┆   ┆ ode       ┆ nomy      ┆ nomy_meth ┆ ader     │
│ str       ┆ i64       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ od        ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IMGVR_UVi ┆ 204253600 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2042536 ┆ 1         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆           ┆ iG_20425 │
│ 001_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ illota;c_ ┆           ┆ 36001_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆ _Clostrid ┆           ┆ 0001|204 │
│           ┆           ┆           ┆           ┆   ┆           ┆ ia;o__Lac ┆           ┆ 2536001| │
│           ┆           ┆           ┆           ┆   ┆           ┆ hnospiral ┆           ┆ Irish_EM │
│           ┆           ┆           ┆           ┆   ┆           ┆ es;f__Lac ┆           ┆ 03_conti │
│           ┆           ┆           ┆           ┆   ┆           ┆ hnospirac ┆           ┆ g02274   │
│           ┆           ┆           ┆           ┆   ┆           ┆ eae       ┆           ┆          │
│ IMGVR_UVi ┆ 204253600 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ vOTU      ┆ IMGVR_UV │
│ G_2042536 ┆ 1         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆           ┆ iG_20425 │
│ 001_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ teroidota ┆           ┆ 36001_00 │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆ ;c__Bacte ┆           ┆ 0002|204 │
│           ┆           ┆           ┆           ┆   ┆           ┆ roidia;o_ ┆           ┆ 2536001| │
│           ┆           ┆           ┆           ┆   ┆           ┆ _Chitinop ┆           ┆ Irish_EM │
│           ┆           ┆           ┆           ┆   ┆           ┆ hagales;f ┆           ┆ 03_conti │
│           ┆           ┆           ┆           ┆   ┆           ┆ __Chitino ┆           ┆ g03465   │
│           ┆           ┆           ┆           ┆   ┆           ┆ phagaceae ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ;g__Chiti ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ nophaga;s ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ _…        ┆           ┆          │
│ IMGVR_UVi ┆ 204253600 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2042536 ┆ 1         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆           ┆ iG_20425 │
│ 001_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ illota;c_ ┆           ┆ 36001_00 │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆ _Clostrid ┆           ┆ 0003|204 │
│           ┆           ┆           ┆           ┆   ┆           ┆ ia;o__Osc ┆           ┆ 2536001| │
│           ┆           ┆           ┆           ┆   ┆           ┆ illospira ┆           ┆ Irish_EM │
│           ┆           ┆           ┆           ┆   ┆           ┆ les;f__Os ┆           ┆ 03_conti │
│           ┆           ┆           ┆           ┆   ┆           ┆ cillospir ┆           ┆ g08621   │
│           ┆           ┆           ┆           ┆   ┆           ┆ aceae;g__ ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Vescimona ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ s         ┆           ┆          │
│ IMGVR_UVi ┆ 204253600 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2042536 ┆ 1         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆           ┆ iG_20425 │
│ 001_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ teroidota ┆           ┆ 36001_00 │
│ 4         ┆           ┆           ┆           ┆   ┆           ┆ ;c__Bacte ┆           ┆ 0004|204 │
│           ┆           ┆           ┆           ┆   ┆           ┆ roidia;o_ ┆           ┆ 2536001| │
│           ┆           ┆           ┆           ┆   ┆           ┆ _Bacteroi ┆           ┆ Irish_EM │
│           ┆           ┆           ┆           ┆   ┆           ┆ dales;f__ ┆           ┆ 03_conti │
│           ┆           ┆           ┆           ┆   ┆           ┆ Bacteroid ┆           ┆ g24613   │
│           ┆           ┆           ┆           ┆   ┆           ┆ aceae;g__ ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Bacteroid ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ es        ┆           ┆          │
│ IMGVR_UVi ┆ 204253600 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_2042536 ┆ 1         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆           ┆           ┆ iG_20425 │
│ 001_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆           ┆           ┆ 36001_00 │
│ 5         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0005|204 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2536001| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Irish_EM │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 03_conti │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ g06838   │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IMGVR_UVi ┆ 330003932 ┆ GVMAGs    ┆ null      ┆ … ┆ 4         ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_GVMAG-M ┆ 3         ┆ (2025)    ┆           ┆   ┆           ┆           ┆           ┆ iG_GVMAG │
│ -33000393 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -M-33000 │
│ 23-104    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 39323-10 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4|330003 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9323|Ga0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 169852_0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0358     │
│ IMGVR_UVi ┆ 330003932 ┆ GVMAGs    ┆ null      ┆ … ┆ 4         ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_GVMAG-M ┆ 3         ┆ (2025)    ┆           ┆   ┆           ┆           ┆           ┆ iG_GVMAG │
│ -33000393 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -M-33000 │
│ 23-104    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 39323-10 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4|330003 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9323|Ga0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 169852_0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0197     │
│ IMGVR_UVi ┆ 330003932 ┆ GVMAGs    ┆ null      ┆ … ┆ 4         ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_GVMAG-M ┆ 3         ┆ (2025)    ┆           ┆   ┆           ┆           ┆           ┆ iG_GVMAG │
│ -33000393 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -M-33000 │
│ 23-104    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 39323-10 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4|330003 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9323|Ga0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 169852_0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0238     │
│ IMGVR_UVi ┆ 330003932 ┆ GVMAGs    ┆ null      ┆ … ┆ 4         ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_GVMAG-M ┆ 3         ┆ (2025)    ┆           ┆   ┆           ┆           ┆           ┆ iG_GVMAG │
│ -33000393 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -M-33000 │
│ 23-104    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 39323-10 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4|330003 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9323|Ga0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 169852_0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0449     │
│ IMGVR_UVi ┆ 330003932 ┆ GVMAGs    ┆ null      ┆ … ┆ 4         ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_GVMAG-M ┆ 3         ┆ (2025)    ┆           ┆   ┆           ┆           ┆           ┆ iG_GVMAG │
│ -33000393 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ -M-33000 │
│ 23-104    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 39323-10 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4|330003 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9323|Ga0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 169852_0 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0696     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Quality-filter the UViGs

Following the guidelines used by [Graham et al. (2024) *Nat. Microbiol.*](https://doi.org/10.1038/s41564-024-01686-x):

>Virus genomes were selected using the following rules:
>
>(1) contigs of at least 1 kb with high similarity to genomes in the CheckV database (that is, that had high- or medium-quality completeness estimates) or that contained direct terminal repeats were automatically selected;
>
>(2) contigs longer than 10 kb were required to have a geNomad virus score higher than 0.8 and to either encode one virus hallmark (for example, terminase, capsid proteins, portal protein and so on), as determined by geNomad, or to have a geNomad virus marker of at least 5.0;
>
>(3) contigs shorter than 10 kb and longer than 5 kb were required to have a geNomad virus score higher than 0.9, to encode at least one virus hallmark and to have a virus marker enrichment higher than 2.0.

Except **(1)** the metadata for MetaVR does not include columns for "geNomad virus marker" or "virus marker enrichment" so those will be ignored, and **(2)** the above guidelines are for non-proviruses, which will be included here, so proviruses will also be kept if they are at least 10 kb, are CheckV complete, medium-m or high-quality, have a CheckV completeness < 5%, have a geNomad score > 0.8, and have at least 1 viral hallmark gene.

In [8]:
metavr_quality_filter = (
    # GSVA filtering rules (no proviruses)
    (
        (pl.col("uvig_topology").is_in(["Linear", "Direct terminal repeat", "Inverted terminal repeat"])) &
        (       
            (
                (pl.col("uvig_length") >= 1_000) &
                (
                    (pl.col("quality").is_in(["Complete", "High-quality", "Medium-quality"])) |
                    (pl.col("uvig_topology").is_in(["Direct terminal repeat", "Inverted terminal repeat"]))
                )
            ) |
            (
                (pl.col("uvig_length") >= 10_000) &
                (pl.col("genomad_score") > 0.8) &
                (pl.col("n_hallmarks") >= 1) # Metadata does not have "genomad_virus_marker" column
            ) |
            (
                (pl.col("uvig_length") < 10_000) & (pl.col("uvig_length") > 5_000) &
                (pl.col("genomad_score") > 0.9) &
                (pl.col("n_hallmarks") >= 1) # Metadata does not have "genomad_marker_enrichment" column
            )
        )
    ) |
    # Provirus filtering
    (
        (pl.col("uvig_topology").is_in(["Provirus"])) &
        (
            (pl.col("uvig_length") >= 10_000) &
            (pl.col("quality").is_in(["Complete", "High-quality", "Medium-quality"])) &
            (pl.col("checkv_contamination") < 0.05) &
            (pl.col("genomad_score") > 0.8) &
            (pl.col("n_hallmarks") >= 1)
        )
    )
)

### MetaVR soil

In [9]:
metavr_uvigs_soil_filtered = metavr_uvigs_soil.filter(metavr_quality_filter)

In [10]:
metavr_uvigs_soil_filtered

shape: (767_946, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ uvig      ┆ taxon_oid ┆ discovery ┆ discovery ┆ … ┆ genetic_c ┆ host_taxo ┆ host_taxo ┆ fasta_he │
│ ---       ┆ ---       ┆ ---       ┆ _doi      ┆   ┆ ode       ┆ nomy      ┆ nomy_meth ┆ ader     │
│ str       ┆ i64       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ od        ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IMGVR_UVi ┆ 208809000 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_2088090 ┆ 8         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆           ┆           ┆ iG_20880 │
│ 008_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆           ┆           ┆ 90008_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0001|208 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8090008| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ P3_DRAFT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _NODE_29 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0175_len │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ _15711_c │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ov_24_19 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6932     │
│ IMGVR_UVi ┆ 208809000 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2088090 ┆ 8         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Chl ┆           ┆ iG_20880 │
│ 008_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ oroflexot ┆           ┆ 90008_00 │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆ a;c__Limn ┆           ┆ 0002|208 │
│           ┆           ┆           ┆           ┆   ┆           ┆ ocylindri ┆           ┆ 8090008| │
│           ┆           ┆           ┆           ┆   ┆           ┆ a;o__Limn ┆           ┆ P3_DRAFT │
│           ┆           ┆           ┆           ┆   ┆           ┆ ocylindra ┆           ┆ _NODE_61 │
│           ┆           ┆           ┆           ┆   ┆           ┆ les;f__CS ┆           ┆ 48_len_1 │
│           ┆           ┆           ┆           ┆   ┆           ┆ P1-4;g__S ┆           ┆ 2315_cov │
│           ┆           ┆           ┆           ┆   ┆           ┆ PCO01     ┆           ┆ _71_6959 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 00       │
│ IMGVR_UVi ┆ 208809001 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2088090 ┆ 4         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Act ┆           ┆ iG_20880 │
│ 014_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ inomyceto ┆           ┆ 90014_00 │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆ ta;c__Act ┆           ┆ 0002|208 │
│           ┆           ┆           ┆           ┆   ┆           ┆ inomycete ┆           ┆ 8090014| │
│           ┆           ┆           ┆           ┆   ┆           ┆ s;o__Acti ┆           ┆ GPIPI_16 │
│           ┆           ┆           ┆           ┆   ┆           ┆ nomycetal ┆           ┆ 496951   │
│           ┆           ┆           ┆           ┆   ┆           ┆ es;f__Mic ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ rococcace ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ae        ┆           ┆          │
│ IMGVR_UVi ┆ 208809001 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_2088090 ┆ 4         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆           ┆           ┆ iG_20880 │
│ 014_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆           ┆           ┆ 90014_00 │
│ 8         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0008|208 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8090014| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ GPIPI_16 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 804765   │
│ IMGVR_UVi ┆ 208809001 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2088090 ┆ 4         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Pse ┆           ┆ iG_20880 │
│ 014_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ udomonado ┆           ┆ 90014_00 │
│ 9         ┆           ┆           ┆           ┆   ┆           ┆ ta;c__Alp ┆           ┆ 0009|208 │
│           ┆           ┆           ┆           ┆   ┆           ┆ haproteob ┆           ┆ 8090014| │
│           ┆           ┆           ┆           ┆   ┆           ┆ acteria;o ┆           ┆ GPIPI_16 │
│           ┆           ┆           ┆           ┆   ┆           ┆ __Rhodosp ┆           ┆ 855418   │
│           ┆           ┆           ┆           ┆   ┆           ┆ irillales ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ;f__UXAT0 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IMGVR_UVi ┆ 812359602 ┆ Virus     ┆ null      ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_8123596 ┆ 9         ┆ genomes   ┆           ┆   ┆           ┆           ┆           ┆ iG_81235 │
│ 029_00000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 96029_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0001|812 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3596029| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 81235960 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 29       │
│ IMGVR_UVi ┆ 812359612 ┆ Virus     ┆ null      ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_8123596 ┆ 8         ┆ genomes   ┆           ┆   ┆           ┆           ┆           ┆ iG_81235 │
│ 128_00000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 96128_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0001|812 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3596128| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 81235961 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 28       │
│ IMGVR_UVi ┆ 812359617 ┆ Virus     ┆ null      ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_8123596 ┆ 8         ┆ genomes   ┆           ┆   ┆           ┆           ┆           ┆ iG_81235 │
│ 178_00000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 96178_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0001|812 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3596178| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 81235961 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 78       │
│ IMGVR_UVi ┆ 812359627 ┆ Virus     ┆ null      ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_8123596 ┆ 5         ┆ genomes   ┆           ┆   ┆           ┆           ┆           ┆ iG_81235 │
│ 275_00000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 96275_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0001|812 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3596275| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 81235962 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 75       │
│ IMGVR_UVi ┆ 812360313 ┆ Virus     ┆ null      ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_8123603 ┆ 5         ┆ genomes   ┆           ┆   ┆           ┆ ia;p__Act ┆           ┆ iG_81236 │
│ 135_00000 ┆           ┆           ┆           ┆   ┆           ┆ inomyceto ┆           ┆ 03135_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆ ta;c__Act ┆           ┆ 0001|812 │
│           ┆           ┆           ┆           ┆   ┆           ┆ inomycete ┆           ┆ 3603135| │
│           ┆           ┆           ┆           ┆   ┆           ┆ s;o__Myco ┆           ┆ 81236031 │
│           ┆           ┆           ┆           ┆   ┆           ┆ bacterial ┆           ┆ 35       │
│           ┆           ┆           ┆           ┆   ┆           ┆ es;f__Myc ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ obacteria ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ceae;g__G ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ordonia   ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### MetaVR human gut

In [11]:
metavr_uvigs_gut_filtered = metavr_uvigs_gut.filter(metavr_quality_filter)

In [12]:
metavr_uvigs_gut_filtered

shape: (238_034, 26)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ uvig      ┆ taxon_oid ┆ discovery ┆ discovery ┆ … ┆ genetic_c ┆ host_taxo ┆ host_taxo ┆ fasta_he │
│ ---       ┆ ---       ┆ ---       ┆ _doi      ┆   ┆ ode       ┆ nomy      ┆ nomy_meth ┆ ader     │
│ str       ┆ i64       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ od        ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IMGVR_UVi ┆ 204253600 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2042536 ┆ 1         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆           ┆ iG_20425 │
│ 001_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ illota;c_ ┆           ┆ 36001_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆ _Clostrid ┆           ┆ 0001|204 │
│           ┆           ┆           ┆           ┆   ┆           ┆ ia;o__Lac ┆           ┆ 2536001| │
│           ┆           ┆           ┆           ┆   ┆           ┆ hnospiral ┆           ┆ Irish_EM │
│           ┆           ┆           ┆           ┆   ┆           ┆ es;f__Lac ┆           ┆ 03_conti │
│           ┆           ┆           ┆           ┆   ┆           ┆ hnospirac ┆           ┆ g02274   │
│           ┆           ┆           ┆           ┆   ┆           ┆ eae       ┆           ┆          │
│ IMGVR_UVi ┆ 204253600 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ vOTU      ┆ IMGVR_UV │
│ G_2042536 ┆ 1         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆           ┆ iG_20425 │
│ 001_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ teroidota ┆           ┆ 36001_00 │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆ ;c__Bacte ┆           ┆ 0002|204 │
│           ┆           ┆           ┆           ┆   ┆           ┆ roidia;o_ ┆           ┆ 2536001| │
│           ┆           ┆           ┆           ┆   ┆           ┆ _Chitinop ┆           ┆ Irish_EM │
│           ┆           ┆           ┆           ┆   ┆           ┆ hagales;f ┆           ┆ 03_conti │
│           ┆           ┆           ┆           ┆   ┆           ┆ __Chitino ┆           ┆ g03465   │
│           ┆           ┆           ┆           ┆   ┆           ┆ phagaceae ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ;g__Chiti ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ nophaga;s ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ _…        ┆           ┆          │
│ IMGVR_UVi ┆ 204253600 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2042536 ┆ 1         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆           ┆ iG_20425 │
│ 001_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ teroidota ┆           ┆ 36001_00 │
│ 4         ┆           ┆           ┆           ┆   ┆           ┆ ;c__Bacte ┆           ┆ 0004|204 │
│           ┆           ┆           ┆           ┆   ┆           ┆ roidia;o_ ┆           ┆ 2536001| │
│           ┆           ┆           ┆           ┆   ┆           ┆ _Bacteroi ┆           ┆ Irish_EM │
│           ┆           ┆           ┆           ┆   ┆           ┆ dales;f__ ┆           ┆ 03_conti │
│           ┆           ┆           ┆           ┆   ┆           ┆ Bacteroid ┆           ┆ g24613   │
│           ┆           ┆           ┆           ┆   ┆           ┆ aceae;g__ ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Bacteroid ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ es        ┆           ┆          │
│ IMGVR_UVi ┆ 204253600 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2042536 ┆ 1         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆           ┆ iG_20425 │
│ 001_00000 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ teroidota ┆           ┆ 36001_00 │
│ 8         ┆           ┆           ┆           ┆   ┆           ┆ ;c__Bacte ┆           ┆ 0008|204 │
│           ┆           ┆           ┆           ┆   ┆           ┆ roidia;o_ ┆           ┆ 2536001| │
│           ┆           ┆           ┆           ┆   ┆           ┆ _Bacteroi ┆           ┆ Irish_EM │
│           ┆           ┆           ┆           ┆   ┆           ┆ dales;f__ ┆           ┆ 03_conti │
│           ┆           ┆           ┆           ┆   ┆           ┆ Bacteroid ┆           ┆ g06696   │
│           ┆           ┆           ┆           ┆   ┆           ┆ aceae;g__ ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Bacteroid ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ es        ┆           ┆          │
│ IMGVR_UVi ┆ 204253600 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ iPHoP     ┆ IMGVR_UV │
│ G_2042536 ┆ 1         ┆ v1.1.0    ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆           ┆ iG_20425 │
│ 001_00001 ┆           ┆ (2022)    ┆ -01953-y  ┆   ┆           ┆ teroidota ┆           ┆ 36001_00 │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆ ;c__Bacte ┆           ┆ 0010|204 │
│           ┆           ┆           ┆           ┆   ┆           ┆ roidia;o_ ┆           ┆ 2536001| │
│           ┆           ┆           ┆           ┆   ┆           ┆ _Bacteroi ┆           ┆ Irish_EM │
│           ┆           ┆           ┆           ┆   ┆           ┆ dales;f__ ┆           ┆ 03_conti │
│           ┆           ┆           ┆           ┆   ┆           ┆ Bacteroid ┆           ┆ g01092   │
│           ┆           ┆           ┆           ┆   ┆           ┆ aceae;g__ ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Bacteroid ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ es        ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IMGVR_UVi ┆ 812201459 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ Isolate   ┆ IMGVR_UV │
│ G_8122014 ┆ 5         ┆ v1.11.0   ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆ taxonomy  ┆ iG_81220 │
│ 595_00000 ┆           ┆ (2025)    ┆ -01953-y  ┆   ┆           ┆ illota;c_ ┆           ┆ 14595_00 │
│ 5         ┆           ┆           ┆           ┆   ┆           ┆ _Clostrid ┆           ┆ 0005|812 │
│           ┆           ┆           ┆           ┆   ┆           ┆ ia;o__Osc ┆           ┆ 2014595| │
│           ┆           ┆           ┆           ┆   ┆           ┆ illospira ┆           ┆ 81220146 │
│           ┆           ┆           ┆           ┆   ┆           ┆ les;f__Ru ┆           ┆ 48       │
│           ┆           ┆           ┆           ┆   ┆           ┆ minococca ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ceae;g__P ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ orcipelet ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ homonas;s ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ _…        ┆           ┆          │
│ IMGVR_UVi ┆ 812201459 ┆ geNomad   ┆ 10.1038/s ┆ … ┆ 11        ┆ d__Bacter ┆ Isolate   ┆ IMGVR_UV │
│ G_8122014 ┆ 5         ┆ v1.11.0   ┆ 41587-023 ┆   ┆           ┆ ia;p__Bac ┆ taxonomy  ┆ iG_81220 │
│ 595_00000 ┆           ┆ (2025)    ┆ -01953-y  ┆   ┆           ┆ illota;c_ ┆           ┆ 14595_00 │
│ 7         ┆           ┆           ┆           ┆   ┆           ┆ _Clostrid ┆           ┆ 0007|812 │
│           ┆           ┆           ┆           ┆   ┆           ┆ ia;o__Osc ┆           ┆ 2014595| │
│           ┆           ┆           ┆           ┆   ┆           ┆ illospira ┆           ┆ 81220146 │
│           ┆           ┆           ┆           ┆   ┆           ┆ les;f__Ru ┆           ┆ 55       │
│           ┆           ┆           ┆           ┆   ┆           ┆ minococca ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ceae;g__P ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ orcipelet ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ homonas;s ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ _…        ┆           ┆          │
│ IMGVR_UVi ┆ 812360289 ┆ Virus     ┆ null      ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_8123602 ┆ 4         ┆ genomes   ┆           ┆   ┆           ┆           ┆           ┆ iG_81236 │
│ 894_00000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 02894_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0001|812 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3602894| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 81236028 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 94       │
│ IMGVR_UVi ┆ 812360311 ┆ Virus     ┆ null      ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_8123603 ┆ 7         ┆ genomes   ┆           ┆   ┆           ┆           ┆           ┆ iG_81236 │
│ 117_00000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 03117_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0001|812 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3603117| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 81236031 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 17       │
│ IMGVR_UVi ┆ 812360333 ┆ Virus     ┆ null      ┆ … ┆ 11        ┆ null      ┆ null      ┆ IMGVR_UV │
│ G_8123603 ┆ 4         ┆ genomes   ┆           ┆   ┆           ┆           ┆           ┆ iG_81236 │
│ 334_00000 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 03334_00 │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0001|812 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3603334| │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 81236033 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 34       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Write the output filtered sequences

In [13]:
OUT_SOIL_HEADERS = MAIN_DIR / "metavr_uvigs_soil_filtered_headers.txt"
with open(OUT_SOIL_HEADERS, "w") as out:
    for header in metavr_uvigs_soil_filtered.get_column("fasta_header").to_list():
        out.write(header + "\n")

In [14]:
! head {OUT_SOIL_HEADERS}
! wc -l {OUT_SOIL_HEADERS}

IMGVR_UViG_2088090008_000001|2088090008|P3_DRAFT_NODE_290175_len_15711_cov_24_196932
IMGVR_UViG_2088090008_000002|2088090008|P3_DRAFT_NODE_6148_len_12315_cov_71_695900
IMGVR_UViG_2088090014_000002|2088090014|GPIPI_16496951
IMGVR_UViG_2088090014_000008|2088090014|GPIPI_16804765
IMGVR_UViG_2088090014_000009|2088090014|GPIPI_16855418
IMGVR_UViG_2088090014_000010|2088090014|GPIPI_17296344
IMGVR_UViG_2088090014_000011|2088090014|GPIPI_17298922
IMGVR_UViG_2088090014_000012|2088090014|GPIPI_17305223
IMGVR_UViG_2088090014_000016|2088090014|GPIPI_16502255
IMGVR_UViG_2088090014_000017|2088090014|GPIPI_16582498
767946 /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/metavr_uvigs_soil_filtered_headers.txt

In [15]:
! seqkit grep -f {OUT_SOIL_HEADERS} {METAVR_UVIG_FNA} > {MAIN_DIR / "IMGVR5_UViG.soil.filtered.fna"}

[INFO] 767946 patterns loaded from file

In [16]:
! grep -c ">" {MAIN_DIR / "IMGVR5_UViG.soil.filtered.fna"}
! head {MAIN_DIR / "IMGVR5_UViG.soil.filtered.fna"}

767946
>IMGVR_UViG_2700989100_000001|2700989100|2700998900
CCCCCCCCCCCCCCCCCCAGGCCTCTGCGTTCTCAAGAAAGGAGTTTTGGGCGGCCTCTG
GCGTCCCGGACACGGATTGAACCTGTAGGCCGTCGTACCCATCATGATACTGCAGCAAAT
ACACTTTCATTATGCGGACTCCAACAGGAATACAATGTTTTCTACATACGCTTTCTGAAT
CGCATAGACTTCATCAAGCGTGTTGGCCACTTTCTTGTCAATACGGATTTCGGCAAGGCG
CGGTAAGAACAGAGATTTCAACGCGTCGTCCGTCTTATCCTGTACGCCATTGGAGAGCAC
TGCGGCGATCTTACCAATGTAGTCGCCCTGGTTCTCCCACATCCGGAGTCTCAGCTCATC
TGAGATCCCCGAGACGCCAACAACAAGCAAGCCATCGGAAGTCTTGCACAGAAGGGAACC
AAAGGTCTTCGCGTGTTTGCCTTTCTTGTCGGCCTCGTTGAAGCCCACGATTTCAAGGTC
ACACTCCACTTCCATTTTCAACTTCAGACCTTCGGAGGAAGTGCCATCTTCCCACGGCAT

In [17]:
OUT_GUT_HEADERS = MAIN_DIR / "metavr_uvigs_gut_filtered_headers.txt"
with open(OUT_GUT_HEADERS, "w") as out:
    for header in metavr_uvigs_gut_filtered.get_column("fasta_header").to_list():
        out.write(header + "\n")

In [18]:
! head {OUT_GUT_HEADERS}
! wc -l {OUT_GUT_HEADERS}

IMGVR_UViG_2042536001_000001|2042536001|Irish_EM03_contig02274
IMGVR_UViG_2042536001_000002|2042536001|Irish_EM03_contig03465
IMGVR_UViG_2042536001_000004|2042536001|Irish_EM03_contig24613
IMGVR_UViG_2042536001_000008|2042536001|Irish_EM03_contig06696
IMGVR_UViG_2042536001_000010|2042536001|Irish_EM03_contig01092
IMGVR_UViG_2042536001_000012|2042536001|Irish_EM03_contig24596
IMGVR_UViG_2042536001_000017|2042536001|Irish_EM03_contig24598
IMGVR_UViG_2042536001_000018|2042536001|Irish_EM03_contig24593
IMGVR_UViG_2042536001_000023|2042536001|Irish_EM03_contig23565|62382-92740
IMGVR_UViG_2042536001_000025|2042536001|Irish_EM03_contig00101|75099-126401
238034 /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/metavr_uvigs_gut_filtered_headers.txt

In [19]:
! seqkit grep -f {OUT_GUT_HEADERS} {METAVR_UVIG_FNA} > {MAIN_DIR / "IMGVR5_UViG.gut.filtered.fna"}

[INFO] 238034 patterns loaded from file

In [20]:
! grep -c ">" {MAIN_DIR / "IMGVR5_UViG.gut.filtered.fna"}
! head {MAIN_DIR / "IMGVR5_UViG.gut.filtered.fna"}

238034
>IMGVR_UViG_2706795886_000002|2706795886|2706858093
TAATTAACATATTCAACAGGAAAACCACCTAATTAGAATTGCCGACCACAAACTGCCAAA
TACTTCCCCTTTTTTCCATACTTCCTGTTTTACTCATAAATATTCATTAAATTAATTAAT
AATCACCATCATTTCCAGGGAGTGTCCTCTCTGCTATATATTCAATGACAGGTCCGAATG
GCTGAGTTTATGCCGCCAGACGGAGACGGGATCACTTCAGTGACTCCAGGCTGATCTTGG
GCGGGAGCCGAAGGTGAGTGAAACCACCGTAGTCTAGGGGCAATTCGGGCTAGATCAGTC
TGGCGGAACGGGCAAGAAACTTAAATTATTTTATTTTACAGAATGACAACAAGAATTGTA
CCTACAAAAGACAGCATTCGCCAAAAAAATCTAAAATGGATGAACCTCCTAGTACACAGC
CATGACATTTTCTGCGACTGCGACTCACCGCTACAACACACCCTTATTTTAATCTGCCAA
CAAGAACCAAAAATTGAATTAAAACCAATTGAGAAGGATATCATCAAAAAATGCCTTATT

## Run CheckAMG annotate

Since the input sequences were already quality filtered, both `--min-len` and `--min-orf` will be set to `1`.

### MetaVR soil

    nohup checkamg annotate \
        --db-dir ./CheckAMG_annotate_db_v1.1_20260316 \
        --output /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_annotate_v1.1_MetaVRsoil \
        --input-contigs /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/IMGVR5_UViG.soil.filtered.fna \
        --min-len 1 \
        --min-orf 1 \
        --save-to-parquet \
        --threads 100 \
        --mem 1000 \
        > ./logs/checkamg_annotate/CheckAMG_annotate_metavr_soil.log &

In [14]:
! cat ./logs/checkamg_annotate/CheckAMG_annotate_metavr_soil.log

################################################################################
                                                                    ,-^-.
       _____  _                  _               __  __   _____     |\/\|
      / ____|| |                | |       /\    |  \/  | / ____|    `-V-'
     | |     | |__    ___   ___ | | __   /  \   | \  / || |  __       H
     | |     | '_ \  / _ \ / __|| |/ /  / /\ \  | |\/| || | |_ |      H
     | |____ | | | ||  __/| (__ |   <  / ____ \ | |  | || |__| |      H
      \_____||_| |_| \___| \___||_|\_\/_/    \_\|_|  |_| \_____|   .-;":-.
                                                                  ,'|  `; \
################################################################################

2026-07-16 19:45:29 | INFO | CheckAMG version 1.1
2026-07-16 19:45:29 | INFO | Starting CheckAMG annotate...
2026-07-16 19:45:29 | INFO | Command executed: checkamg annotate --db-dir ./CheckAMG_annotate_db_v1.1_20260316 --output /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_annotate_v1.1_MetaVRsoil --input-contigs /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/IMGVR5_UViG.soil.filtered.fna --input-type nucl --min-len 1 --min-orf 1 --min-annot 0.2 --cov-fraction 0.4 --evalue 1e-05 --bitscore 60 --bitscore-fraction-heuristic 0.5 --window-size 5000 --min-flank-vscore 10.0 --min-window-avg-vlscore 3.0 --no-use-hallmark --min-amg-weight 0.6 --no-filter-ambig-regions --filter-avg-arrays --avg-array-limit 3 --filter-presets allow_glucan,allow_nucleotide,allow_methyl,allow_lipid --no-keep-full-hmm-results --save-to-parquet --threads 100 --mem 1000 --no-debug
================================================================================
                Step 1/11: Filter the input sequences by length
================================================================================
2026-07-16 19:45:29 | INFO | Contig length filtering starting...
2026-07-16 19:47:14 | INFO | Number of input sequences: 767,946 (767,946 genomes)
Filtering sequences: 100%|██████████| 767946/767946 [01:37<00:00, 7906.56sequence/s]
2026-07-16 19:51:28 | INFO | Number of sequences filtered by length: 767,946 (767,946 genomes)
2026-07-16 19:51:28 | INFO | Contig length filtering completed.
================================================================================
            Step 2/11: Check the circularity of the input sequences
================================================================================
2026-07-16 19:51:35 | INFO | Sequence circularity check starting...
2026-07-16 19:51:56 | INFO | Total sequences to check: 767,946
Checking circularity: 100%|██████████| 100/100 [00:00<00:00, 526261.48batch/s]
2026-07-16 19:54:57 | INFO | Number of sequences checked: 767,946
2026-07-16 19:54:57 | INFO | Number of circular sequences detected: 31,251
2026-07-16 19:54:57 | INFO | Circularity check completed.
================================================================================
     Step 3/11: Predict ORFs and translate into proteins with pyrodigal-GV
================================================================================
2026-07-16 19:55:01 | INFO | Metapyrodigal-GV run starting...
2026-07-16 19:55:01 | INFO | Running metapyrodigal-GV on contigs with 100 CPUs
Predicting ORFs for each scaffold: 100%|██████████| 767946/767946 [15:43<00:00, 813.72scaffold/s]
2026-07-16 20:11:01 | INFO | Metapyrodigal-GV run completed.
================================================================================
            Step 4/11: Filter the input sequences by number of ORFs
================================================================================
2026-07-16 20:11:02 | INFO | Amino-acid sequence filtering starting...
2026-07-16 20:11:50 | INFO | Single-contig input: 767,786 contigs (767,786 genomes), 16,501,794 ORFs
2026-07-16 20:11:50 | INFO | Bin inputs: 0 contigs (0 genomes), 0 ORFs
2026-07-16 20:11:50 | INFO | Total before filtering: 767,786 contigs (767,786 genomes), 16,501,794 ORFs
2026-07-16 20:11:50 | INFO | Total contigs before filtering: 767,786 (767,786 genomes)
2026-07-16 20:11:50 | INFO | Total amino-acid sequences before filtering: 16,501,794
Filtering contigs: 100%|██████████| 767786/767786 [01:09<00:00, 11122.90contig/s]
2026-07-16 20:15:47 | INFO | Filtered contigs: 767,786 contigs and 16,501,794 ORFs retained
2026-07-16 20:16:51 | INFO | Total contigs after filtering: 767,786 (767,786 genomes)
2026-07-16 20:16:51 | INFO | Total amino-acid sequences after filtering: 16,501,794
2026-07-16 20:16:52 | INFO | Amino-acid sequence filtering completed.
================================================================================
                    Step 5/11: Assign functions to proteins
================================================================================
2026-07-16 20:16:54 | INFO | Protein HMM searches starting...
2026-07-16 20:26:02 | INFO | Splitting 16,501,794 sequences into 11 batches of 1,500,164
2026-07-16 20:26:02 | INFO | Running hmmsearch against FOAM profile HMMs...
hmmsearch (FOAM): 100%|██████████| 11/11 [16:49:58<00:00, 5508.95s/batch]
2026-07-17 13:16:00 | INFO | Running hmmsearch against KEGG profile HMMs...
hmmsearch (KEGG): 100%|██████████| 11/11 [16:02:07<00:00, 5247.92s/batch]
2026-07-18 05:18:08 | INFO | Running hmmsearch against PHROG profile HMMs...
hmmsearch (PHROG): 100%|██████████| 11/11 [7:38:39<00:00, 2501.76s/batch]
2026-07-18 12:56:47 | INFO | Running hmmsearch against Pfam profile HMMs...
hmmsearch (Pfam): 100%|██████████| 11/11 [4:16:50<00:00, 1400.99s/batch]
2026-07-18 17:13:38 | INFO | Running hmmsearch against dbCAN profile HMMs...
hmmsearch (dbCAN): 100%|██████████| 11/11 [12:39<00:00, 69.08s/batch]
2026-07-18 17:26:18 | INFO | Running hmmsearch against CAMPER profile HMMs...
hmmsearch (CAMPER): 100%|██████████| 11/11 [06:20<00:00, 34.55s/batch]
2026-07-18 17:32:38 | INFO | Running hmmsearch against METABOLIC profile HMMs...
hmmsearch (METABOLIC): 100%|██████████| 11/11 [07:25<00:00, 40.46s/batch]
2026-07-18 17:40:03 | INFO | Filtering hmmsearch results...
2026-07-18 17:40:03 | INFO | Filtering results from FOAM...
2026-07-18 17:40:22 | INFO | Filtering results from KEGG...
2026-07-18 17:40:34 | INFO | Filtering results from PHROG...
2026-07-18 17:41:09 | INFO | Filtering results from Pfam...
2026-07-18 17:41:22 | INFO | Filtering results from dbCAN...
2026-07-18 17:41:22 | INFO | Filtering results from CAMPER...
2026-07-18 17:41:23 | INFO | Filtering results from METABOLIC...
2026-07-18 17:41:23 | INFO | Aggregating final hmmsearch results...
2026-07-18 17:41:26 | INFO | Building V/VL-score table from all hits at evalue ≤ 1E-05 (no bitscore/coverage/GA requirements)...
2026-07-18 17:43:58 | INFO | Scoring table: 12,695,963 proteins with a hit at evalue ≤ 1E-05
2026-07-18 17:44:07 | INFO | Protein HMM searches completed.
2026-07-18 17:44:07 | INFO | Best hits per protein: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_annotate_v1.1_MetaVRsoil/wdir/hmm_results.filtered.parquet
================================================================================
                 Step 6/11: Map gene- and genome-level metadata
================================================================================
2026-07-18 17:44:15 | INFO | Starting genome and gene data mapping...
2026-07-18 17:45:27 | INFO | Genome and gene data mapping completed.
================================================================================
         Step 7/11: Merge functional annotations with protein metadata
================================================================================
2026-07-18 17:45:28 | INFO | Processing of V-scores/VL-scores and HMM results starting...
2026-07-18 17:45:50 | INFO | Processing of V-scores/VL-scores and HMM results completed.
================================================================================
             Step 8/11: Analyze the genomic context of annotations
================================================================================
2026-07-18 17:45:56 | INFO | Starting genome context analysis...
2026-07-18 17:46:01 | INFO | Calculating distance to contig ends.
2026-07-18 17:46:05 | INFO | Calculating contig statistics.
2026-07-18 17:46:06 | INFO | Calculating window statistics.
Calculating sliding-window averages: 100%|██████████| 767786/767786 [03:58<00:00, 3216.15contig/s]
2026-07-18 17:52:19 | INFO | Identifying ambiguous viral/nonviral contig regions.
2026-07-18 18:00:31 | INFO | Calculating distance of nearest flanking V-score=10.0 genes.
Checking flanks for V-score=10.0: 100%|██████████| 767786/767786 [00:20<00:00, 37260.34contig/s]
2026-07-18 18:11:30 | INFO | Calculating distance of nearest mobile genetic element genes.
Checking flanks for mobile genes: 100%|██████████| 767786/767786 [00:14<00:00, 52844.95contig/s]
2026-07-18 18:21:32 | INFO | Calculating flanking MGE V/VL-scores.
Checking flanking MGE V/VL-scores: 100%|██████████| 767786/767786 [00:08<00:00, 87019.81contig/s]
2026-07-18 18:34:21 | INFO | Assigning viral origin confidence using LightGBM with genome context features.
Fitting LGBM: 100%|██████████| 83/83 [00:15<00:00,  5.53batch/s]
2026-07-18 18:42:02 | INFO | Genome context analysis completed.
================================================================================
       Step 9/11: Curate the predicted functions based on genomic context
================================================================================
2026-07-18 18:42:27 | INFO | Starting the curation of annotations for metabolism, physiology, and regulation...
2026-07-18 18:43:12 | INFO | Filtering metabolic annotations...
2026-07-18 18:43:14 | INFO | Filtering physiological annotations...
2026-07-18 18:43:15 | INFO | Filtering regulation annotations...
2026-07-18 18:43:17 | INFO | Filtering AVGs present in arrays of 3 or more AVGs in a row...
2026-07-18 18:46:09 | INFO | Total number of genes analyzed: 16,501,794
2026-07-18 18:46:09 | INFO | Filtered 184,724 AMGs from 235,769.
2026-07-18 18:46:10 | INFO | Filtered 157,150 AMGs for reason: AMG weight below minimum
2026-07-18 18:46:10 | INFO | Filtered 26,230 AMGs for reason: other non-auxiliary function
2026-07-18 18:46:10 | INFO | Filtered 1,344 AMGs for reason: 3+ AMGs in a row
2026-07-18 18:46:10 | INFO | Filtered 2,189 APGs from 27,043.
2026-07-18 18:46:10 | INFO | Filtered 1,104 APGs for reason: other non-auxiliary function
2026-07-18 18:46:10 | INFO | Filtered 1,085 APGs for reason: 3+ APGs in a row
2026-07-18 18:46:10 | INFO | Filtered 72,466 AReGs from 193,445.
2026-07-18 18:46:10 | INFO | Filtered 68,949 AReGs for reason: other non-auxiliary function
2026-07-18 18:46:10 | INFO | Filtered 3,517 AReGs for reason: 3+ AReGs in a row
2026-07-18 18:46:10 | INFO | Final number of curated metabolic genes: 51,045
2026-07-18 18:46:10 | INFO | Final number of curated physiology genes: 24,854
2026-07-18 18:46:10 | INFO | Final number of curated regulatory genes: 120,979
2026-07-18 18:46:10 | INFO | Curation of annotations completed.
================================================================================
              Step 10/11: Organize AMGs, APGs, and AReGs proteins
================================================================================
2026-07-18 18:46:13 | INFO | Organizing proteins based on annotations and writing AMG/AReG/APG classifications...
2026-07-18 18:46:45 | INFO | There are a total of 51,045 predicted AMGs.
2026-07-18 18:47:03 | INFO | There are 26,502 AMGs classified as HIGH confidence viral origin.
2026-07-18 18:47:03 | INFO | There are 13,627 AMGs classified as MEDIUM confidence viral origin.
2026-07-18 18:47:03 | INFO | There are 10,916 AMGs classified as LOW confidence viral origin.
2026-07-18 18:47:26 | INFO | There are a total of 24,854 predicted APGs.
2026-07-18 18:47:43 | INFO | There are 17,142 APGs classified as HIGH confidence viral origin.
2026-07-18 18:47:43 | INFO | There are 4,822 APGs classified as MEDIUM confidence viral origin.
2026-07-18 18:47:43 | INFO | There are 2,890 APGs classified as LOW confidence viral origin.
2026-07-18 18:47:57 | INFO | There are a total of 120,979 predicted AReGs.
2026-07-18 18:48:14 | INFO | There are 98,222 AReGs classified as HIGH confidence viral origin.
2026-07-18 18:48:14 | INFO | There are 16,651 AReGs classified as MEDIUM confidence viral origin.
2026-07-18 18:48:14 | INFO | There are 6,106 AReGs classified as LOW confidence viral origin.
2026-07-18 18:49:14 | INFO | Organization completed.
================================================================================
          Step 11/11: Write the final summarized auxiliary gene tables
================================================================================
2026-07-18 18:49:24 | INFO | Generating the final table with proteins, annotations, and classifications...
2026-07-18 18:49:41 | INFO | Final table written to /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_annotate_v1.1_MetaVRsoil/results/final_results.parquet
2026-07-18 18:49:41 | INFO | 51,045 metabolic proteins span:
2026-07-18 18:49:41 | INFO | 	16 level 1 AMG categories
2026-07-18 18:49:41 | INFO | 	134 level 2 AMG cateogires
2026-07-18 18:49:41 | INFO | 	37 level 3 AMG cateogires
2026-07-18 18:49:41 | INFO | 24,843 physiological proteins span:
2026-07-18 18:49:41 | INFO | 	 8 level 1 APG categories
2026-07-18 18:49:41 | INFO | 	16 level 2 APG cateogires
2026-07-18 18:49:41 | INFO | 	 1 level 3 APG cateogires
2026-07-18 18:49:41 | INFO | 117,989 regulatory proteins span:
2026-07-18 18:49:41 | INFO | 	 7 level 1 AReG categories
2026-07-18 18:49:41 | INFO | 	20 level 2 AReG cateogires
2026-07-18 18:49:41 | INFO | 	 1 level 3 AReG cateogires
================================================================================
                  The CheckAMG annotate pipeline is complete.
================================================================================

### MetaVR human gut

    nohup checkamg annotate \
        --db-dir ./CheckAMG_annotate_db_v1.1_20260316 \
        --output /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_annotate_v1.1_MetaVRgut \
        --input-contigs /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/IMGVR5_UViG.gut.filtered.fna \
        --min-len 1 \
        --min-orf 1 \
        --save-to-parquet \
        --threads 100 \
        --mem 1000 \
        > ./logs/checkamg_annotate/CheckAMG_annotate_metavr_gut.log &

In [24]:
! cat ./logs/checkamg_annotate/CheckAMG_annotate_metavr_gut.log

################################################################################
                                                                    ,-^-.
       _____  _                  _               __  __   _____     |\/\|
      / ____|| |                | |       /\    |  \/  | / ____|    `-V-'
     | |     | |__    ___   ___ | | __   /  \   | \  / || |  __       H
     | |     | '_ \  / _ \ / __|| |/ /  / /\ \  | |\/| || | |_ |      H
     | |____ | | | ||  __/| (__ |   <  / ____ \ | |  | || |__| |      H
      \_____||_| |_| \___| \___||_|\_\/_/    \_\|_|  |_| \_____|   .-;":-.
                                                                  ,'|  `; \
################################################################################

2026-07-19 09:12:35 | INFO | CheckAMG version 1.1
2026-07-19 09:12:35 | INFO | Starting CheckAMG annotate...
2026-07-19 09:12:35 | INFO | Command executed: checkamg annotate --db-dir ./CheckAMG_annotate_db_v1.1_20260316 --output /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_annotate_v1.1_MetaVRgut --input-contigs /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/IMGVR5_UViG.gut.filtered.fna --input-type nucl --min-len 1 --min-orf 1 --min-annot 0.2 --cov-fraction 0.4 --evalue 1e-05 --bitscore 60 --bitscore-fraction-heuristic 0.5 --window-size 5000 --min-flank-vscore 10.0 --min-window-avg-vlscore 3.0 --no-use-hallmark --min-amg-weight 0.6 --no-filter-ambig-regions --filter-avg-arrays --avg-array-limit 3 --filter-presets allow_glucan,allow_nucleotide,allow_methyl,allow_lipid --no-keep-full-hmm-results --save-to-parquet --threads 100 --mem 1000 --no-debug
================================================================================
                Step 1/11: Filter the input sequences by length
================================================================================
2026-07-19 09:12:38 | INFO | Contig length filtering starting...
2026-07-19 09:13:13 | INFO | Number of input sequences: 238,034 (238,034 genomes)
Filtering sequences: 100%|██████████| 238034/238034 [00:41<00:00, 5691.93sequence/s]
2026-07-19 09:14:31 | INFO | Number of sequences filtered by length: 238,034 (238,034 genomes)
2026-07-19 09:14:31 | INFO | Contig length filtering completed.
================================================================================
            Step 2/11: Check the circularity of the input sequences
================================================================================
2026-07-19 09:14:32 | INFO | Sequence circularity check starting...
2026-07-19 09:14:44 | INFO | Total sequences to check: 238,034
Checking circularity: 100%|██████████| 100/100 [00:00<00:00, 773856.83batch/s]
2026-07-19 09:16:02 | INFO | Number of sequences checked: 238,034
2026-07-19 09:16:02 | INFO | Number of circular sequences detected: 13,309
2026-07-19 09:16:02 | INFO | Circularity check completed.
================================================================================
     Step 3/11: Predict ORFs and translate into proteins with pyrodigal-GV
================================================================================
2026-07-19 09:16:04 | INFO | Metapyrodigal-GV run starting...
2026-07-19 09:16:04 | INFO | Running metapyrodigal-GV on contigs with 100 CPUs
Predicting ORFs for each scaffold: 100%|██████████| 238034/238034 [06:48<00:00, 583.27scaffold/s]
2026-07-19 09:23:00 | INFO | Metapyrodigal-GV run completed.
================================================================================
            Step 4/11: Filter the input sequences by number of ORFs
================================================================================
2026-07-19 09:23:00 | INFO | Amino-acid sequence filtering starting...
2026-07-19 09:23:21 | INFO | Single-contig input: 238,034 contigs (238,034 genomes), 6,874,008 ORFs
2026-07-19 09:23:21 | INFO | Bin inputs: 0 contigs (0 genomes), 0 ORFs
2026-07-19 09:23:21 | INFO | Total before filtering: 238,034 contigs (238,034 genomes), 6,874,008 ORFs
2026-07-19 09:23:21 | INFO | Total contigs before filtering: 238,034 (238,034 genomes)
2026-07-19 09:23:21 | INFO | Total amino-acid sequences before filtering: 6,874,008
Filtering contigs: 100%|██████████| 238034/238034 [00:24<00:00, 9712.98contig/s]
2026-07-19 09:25:11 | INFO | Filtered contigs: 238,034 contigs and 6,874,008 ORFs retained
2026-07-19 09:25:41 | INFO | Total contigs after filtering: 238,034 (238,034 genomes)
2026-07-19 09:25:41 | INFO | Total amino-acid sequences after filtering: 6,874,008
2026-07-19 09:25:41 | INFO | Amino-acid sequence filtering completed.
================================================================================
                    Step 5/11: Assign functions to proteins
================================================================================
2026-07-19 09:25:42 | INFO | Protein HMM searches starting...
2026-07-19 09:29:44 | INFO | Splitting 6,874,008 sequences into 5 batches of 1,374,802
2026-07-19 09:29:44 | INFO | Running hmmsearch against FOAM profile HMMs...
hmmsearch (FOAM): 100%|██████████| 5/5 [7:40:44<00:00, 5528.92s/batch]
2026-07-19 17:10:28 | INFO | Running hmmsearch against KEGG profile HMMs...
hmmsearch (KEGG): 100%|██████████| 5/5 [8:37:46<00:00, 6213.25s/batch]
2026-07-20 01:48:15 | INFO | Running hmmsearch against PHROG profile HMMs...
hmmsearch (PHROG): 100%|██████████| 5/5 [5:11:26<00:00, 3737.32s/batch]
2026-07-20 06:59:41 | INFO | Running hmmsearch against Pfam profile HMMs...
hmmsearch (Pfam): 100%|██████████| 5/5 [2:56:38<00:00, 2119.61s/batch]
2026-07-20 09:56:19 | INFO | Running hmmsearch against dbCAN profile HMMs...
2026-07-20 10:05:47 | INFO | Running hmmsearch against CAMPER profile HMMs...
hmmsearch (CAMPER): 100%|██████████| 5/5 [03:04<00:00, 36.83s/batch]
2026-07-20 10:08:51 | INFO | Running hmmsearch against METABOLIC profile HMMs...
hmmsearch (METABOLIC): 100%|██████████| 5/5 [08:29<00:00, 101.88s/batch]
2026-07-20 10:17:20 | INFO | Filtering hmmsearch results...
2026-07-20 10:17:20 | INFO | Filtering results from FOAM...
2026-07-20 10:17:39 | INFO | Filtering results from KEGG...
2026-07-20 10:17:47 | INFO | Filtering results from PHROG...
2026-07-20 10:18:15 | INFO | Filtering results from Pfam...
2026-07-20 10:18:24 | INFO | Filtering results from dbCAN...
2026-07-20 10:18:24 | INFO | Filtering results from CAMPER...
2026-07-20 10:18:24 | INFO | Filtering results from METABOLIC...
2026-07-20 10:18:24 | INFO | Aggregating final hmmsearch results...
2026-07-20 10:18:27 | INFO | Building V/VL-score table from all hits at evalue ≤ 1E-05 (no bitscore/coverage/GA requirements)...
2026-07-20 10:20:20 | INFO | Scoring table: 8,193,470 proteins with a hit at evalue ≤ 1E-05
2026-07-20 10:20:25 | INFO | Protein HMM searches completed.
2026-07-20 10:20:25 | INFO | Best hits per protein: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_annotate_v1.1_MetaVRgut/wdir/hmm_results.filtered.parquet
================================================================================
                 Step 6/11: Map gene- and genome-level metadata
================================================================================
2026-07-20 10:20:30 | INFO | Starting genome and gene data mapping...
2026-07-20 10:20:58 | INFO | Genome and gene data mapping completed.
================================================================================
         Step 7/11: Merge functional annotations with protein metadata
================================================================================
2026-07-20 10:20:59 | INFO | Processing of V-scores/VL-scores and HMM results starting...
2026-07-20 10:21:11 | INFO | Processing of V-scores/VL-scores and HMM results completed.
================================================================================
             Step 8/11: Analyze the genomic context of annotations
================================================================================
2026-07-20 10:21:15 | INFO | Starting genome context analysis...
2026-07-20 10:21:17 | INFO | Calculating distance to contig ends.
2026-07-20 10:21:19 | INFO | Calculating contig statistics.
2026-07-20 10:21:19 | INFO | Calculating window statistics.
Calculating sliding-window averages: 100%|██████████| 238034/238034 [01:07<00:00, 3507.32contig/s]
2026-07-20 10:23:09 | INFO | Identifying ambiguous viral/nonviral contig regions.
2026-07-20 10:25:28 | INFO | Calculating distance of nearest flanking V-score=10.0 genes.
Checking flanks for V-score=10.0: 100%|██████████| 238034/238034 [00:05<00:00, 42192.77contig/s]
2026-07-20 10:28:33 | INFO | Calculating distance of nearest mobile genetic element genes.
Checking flanks for mobile genes: 100%|██████████| 238034/238034 [00:05<00:00, 45327.72contig/s]
2026-07-20 10:31:34 | INFO | Calculating flanking MGE V/VL-scores.
Checking flanking MGE V/VL-scores: 100%|██████████| 238034/238034 [00:07<00:00, 31043.60contig/s]
2026-07-20 10:36:47 | INFO | Assigning viral origin confidence using LightGBM with genome context features.
Fitting LGBM: 100%|██████████| 35/35 [00:09<00:00,  3.58batch/s]
2026-07-20 10:39:21 | INFO | Genome context analysis completed.
================================================================================
       Step 9/11: Curate the predicted functions based on genomic context
================================================================================
2026-07-20 10:39:30 | INFO | Starting the curation of annotations for metabolism, physiology, and regulation...
2026-07-20 10:39:54 | INFO | Filtering metabolic annotations...
2026-07-20 10:39:56 | INFO | Filtering physiological annotations...
2026-07-20 10:39:56 | INFO | Filtering regulation annotations...
2026-07-20 10:39:58 | INFO | Filtering AVGs present in arrays of 3 or more AVGs in a row...
2026-07-20 10:40:07 | INFO | Total number of genes analyzed: 6,874,008
2026-07-20 10:40:07 | INFO | Filtered 123,849 AMGs from 154,009.
2026-07-20 10:40:07 | INFO | Filtered 94,544 AMGs for reason: AMG weight below minimum
2026-07-20 10:40:07 | INFO | Filtered 26,489 AMGs for reason: other non-auxiliary function
2026-07-20 10:40:07 | INFO | Filtered 2,816 AMGs for reason: 3+ AMGs in a row
2026-07-20 10:40:07 | INFO | Filtered 4,033 APGs from 40,104.
2026-07-20 10:40:07 | INFO | Filtered 3,420 APGs for reason: 3+ APGs in a row
2026-07-20 10:40:07 | INFO | Filtered 613 APGs for reason: other non-auxiliary function
2026-07-20 10:40:07 | INFO | Filtered 85,786 AReGs from 227,674.
2026-07-20 10:40:07 | INFO | Filtered 75,670 AReGs for reason: other non-auxiliary function
2026-07-20 10:40:07 | INFO | Filtered 10,116 AReGs for reason: 3+ AReGs in a row
2026-07-20 10:40:07 | INFO | Final number of curated metabolic genes: 30,160
2026-07-20 10:40:07 | INFO | Final number of curated physiology genes: 36,071
2026-07-20 10:40:07 | INFO | Final number of curated regulatory genes: 141,888
2026-07-20 10:40:07 | INFO | Curation of annotations completed.
================================================================================
              Step 10/11: Organize AMGs, APGs, and AReGs proteins
================================================================================
2026-07-20 10:40:09 | INFO | Organizing proteins based on annotations and writing AMG/AReG/APG classifications...
2026-07-20 10:40:24 | INFO | There are a total of 30,160 predicted AMGs.
2026-07-20 10:40:32 | INFO | There are 13,692 AMGs classified as HIGH confidence viral origin.
2026-07-20 10:40:32 | INFO | There are 6,426 AMGs classified as MEDIUM confidence viral origin.
2026-07-20 10:40:32 | INFO | There are 10,042 AMGs classified as LOW confidence viral origin.
2026-07-20 10:40:34 | INFO | There are a total of 36,071 predicted APGs.
2026-07-20 10:40:41 | INFO | There are 21,622 APGs classified as HIGH confidence viral origin.
2026-07-20 10:40:41 | INFO | There are 7,091 APGs classified as MEDIUM confidence viral origin.
2026-07-20 10:40:41 | INFO | There are 7,358 APGs classified as LOW confidence viral origin.
2026-07-20 10:40:43 | INFO | There are a total of 141,888 predicted AReGs.
2026-07-20 10:40:50 | INFO | There are 113,633 AReGs classified as HIGH confidence viral origin.
2026-07-20 10:40:50 | INFO | There are 17,287 AReGs classified as MEDIUM confidence viral origin.
2026-07-20 10:40:50 | INFO | There are 10,968 AReGs classified as LOW confidence viral origin.
2026-07-20 10:40:55 | INFO | Organization completed.
================================================================================
          Step 11/11: Write the final summarized auxiliary gene tables
================================================================================
2026-07-20 10:41:00 | INFO | Generating the final table with proteins, annotations, and classifications...
2026-07-20 10:41:11 | INFO | Final table written to /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_annotate_v1.1_MetaVRgut/results/final_results.parquet
2026-07-20 10:41:12 | INFO | 30,160 metabolic proteins span:
2026-07-20 10:41:12 | INFO | 	16 level 1 AMG categories
2026-07-20 10:41:12 | INFO | 	116 level 2 AMG cateogires
2026-07-20 10:41:12 | INFO | 	31 level 3 AMG cateogires
2026-07-20 10:41:12 | INFO | 36,020 physiological proteins span:
2026-07-20 10:41:12 | INFO | 	 7 level 1 APG categories
2026-07-20 10:41:12 | INFO | 	15 level 2 APG cateogires
2026-07-20 10:41:12 | INFO | 	 1 level 3 APG cateogires
2026-07-20 10:41:12 | INFO | 138,971 regulatory proteins span:
2026-07-20 10:41:12 | INFO | 	 7 level 1 AReG categories
2026-07-20 10:41:12 | INFO | 	19 level 2 AReG cateogires
2026-07-20 10:41:12 | INFO | 	 1 level 3 AReG cateogires
================================================================================
                  The CheckAMG annotate pipeline is complete.
================================================================================

## Run CheckAMG de-novo

The inputs are proteins, so they will need to be embedded for PST. This is done automatically by CheckAMG de-novo when proteins are the input, but this means GPUs are needed. So jobs will be submitted to the [UW-Madison Center for High Throughput Computing](https://chtc.cs.wisc.edu/) (CHTC) again, as done with the training jobs in the notebook `train_pst.ipynb`.

The pipeline invoked by `checkamg de-novo` will require:

1. Amino-acid FASTA files for the filtered soil and human gut virus sequences being used
    * Using the filtered proteins predicted by pyrodigal-GV from each CheckAMG annotate run located at `./wdir/filtered_input/filtered_faa_by_cds/single_contig_proteins.faa` for each, renamed to `IMGVR5_UViG.soil.filtered.faa` and `IMGVR5_UViG.gut.filtered.faa`
2. A pre-trained CheckAMG-PST model checkpoint (from the best model chosen in `train_pst.ipynb`) (`checkAMG-PST_TL-P__large_5.ckpt`)
3. Graph-formatted (`.h5`) PST embeddings of training proteins **generated at the end of the training workflow in `checkamg train` for the specific model checkpoint being used** (`checkAMG-PST_TL-P__large_5.PST-EMBED.h5`) **OR**
4. A precomputed train protein FAISS index constructed from the training protein PST embeddings (`checkAMG-PST_TL-P__large_5.PST-EMBED.index.faiss`) **AND**
5. Training protein labels stored in a H5 file under 'label' (`checkAMG-PST_TL-P__large_5.PST-EMBED.labels.h5`)

Either just (3) or (4 AND 5) are required. They will be included in the CheckAMG database automatically in the future but for now it will be provided manually.

### Split the inputs into smaller batches

CheckAMG de-novo should be able to handle each FASTA as single inputs, but since GPU acceleration will be used, it would be faster (in my case) to split the FASTAs into multiple files and run CheckAMG de-novo on each. This is because CheckAMG is not able to handle using multiple GPUs at once, so having multiple CheckAMG de-novo runs going concurrently for each input, each using a GPU, will be faster than running the entire input on one GPU in a single run. Will just need to be sure that proteins encoded on the same scaffold are not split across files.

In [3]:
from collections import defaultdict
from pyfastatools import Parser

N_SPLITS = 16
SPLITS_DIR = MAIN_DIR / "denovo_splits"
SPLITS_DIR.mkdir(exist_ok=True)

INPUT_FAAS = {
    "soil": MAIN_DIR / "IMGVR5_UViG.soil.filtered.faa",
    "gut": MAIN_DIR / "IMGVR5_UViG.gut.filtered.faa",
}

def scaffold_of(protein_name: str) -> str:
    # pyrodigal names proteins <scaffold>_<gene_number>
    return protein_name.rsplit("_", 1)[0]

def split_faa_by_scaffold(faa: Path, name: str, n_splits: int) -> list[Path]:
    sizes: dict[str, int] = defaultdict(int)
    for h in Parser(str(faa)).headers():
        sizes[scaffold_of(h.name)] += 1

    # LPT multiway partition: assign each scaffold (largest first) to the lightest split
    loads = [0] * n_splits
    bin_of: dict[str, int] = {}
    for scaffold, n in sorted(sizes.items(), key=lambda kv: kv[1], reverse=True):
        b = min(range(n_splits), key=loads.__getitem__)
        bin_of[scaffold] = b
        loads[b] += n

    out_paths = [SPLITS_DIR / f"IMGVR5_UViG.{name}.filtered.split{i + 1:02d}.faa" for i in range(n_splits)]
    handles = [p.open("w") for p in out_paths]
    try:
        for rec in Parser(str(faa)):
            h = rec.header
            line = h.name if not h.desc else f"{h.name} {h.desc}"
            handles[bin_of[scaffold_of(h.name)]].write(f">{line}\n{rec.seq}\n")
    finally:
        for fh in handles:
            fh.close()

    print(f"[{name}] {len(sizes):,} scaffolds, {sum(loads):,} proteins -> {n_splits} splits "
          f"(min {min(loads):,}, max {max(loads):,} proteins/split)")
    return out_paths

In [16]:
split_faa_paths = {name: split_faa_by_scaffold(faa, name, N_SPLITS) for name, faa in INPUT_FAAS.items()}
split_faa_paths

[soil] 767,786 scaffolds, 16,501,794 proteins -> 16 splits (min 1,031,362, max 1,031,363 proteins/split)
[gut] 238,034 scaffolds, 6,873,983 proteins -> 16 splits (min 429,623, max 429,624 proteins/split)

{'soil': [PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split01.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split02.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split03.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split04.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split05.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split06.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split07.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split08.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split09.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split10.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split11.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split12.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split13.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split14.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split15.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.soil.filtered.split16.faa')],
 'gut': [PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split01.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split02.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split03.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split04.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split05.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split06.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split07.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split08.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split09.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split10.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split11.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split12.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split13.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split14.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split15.faa'),
  PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_splits/IMGVR5_UViG.gut.filtered.split16.faa')]}

### Generate the CHTC inputs.csv for the splits

One CheckAMG de-novo job per split. Each row is `query_faa,train_index,train_labels,checkpoint,outdir,knn`, where the query FASTA is a single split and `outdir` is suffixed with the split number so concurrent jobs do not collide. The training index, labels, and model checkpoint are shared across all splits.

In [4]:
CHTC_FILES_DIR = Path("./files/checkamg_denovo")
CHTC_FILES_DIR.mkdir(exist_ok=True)
INPUTS_CSV = CHTC_FILES_DIR.joinpath("inputs.csv")

In [5]:
import numpy as np

CHECKAMG_DB_PATTERNS = "CheckAMG_denovo_db_v*_*"
db_paths = [p for p in Path(".").glob(CHECKAMG_DB_PATTERNS) if p.is_dir()]
if not db_paths:
    raise FileNotFoundError(f"No CheckAMG database directories matching {CHECKAMG_DB_PATTERNS}")
MOST_RECENT_DB = db_paths[np.argmax([p.name.split("_")[-1] for p in db_paths])]
print(f"Most recent CheckAMG_db: {MOST_RECENT_DB}")

Most recent CheckAMG_db: CheckAMG_denovo_db_v1.1_20260714

In [6]:
import glob

CKPT = Path(glob.glob(str(MOST_RECENT_DB / "*.ckpt"))[0]).name
TRAIN_INDEX = Path(glob.glob(str(MOST_RECENT_DB / "*.PST-EMBED.index.faiss"))[0]).name
TRAIN_LABELS = Path(glob.glob(str(MOST_RECENT_DB / "*.PST-EMBED.labels.h5"))[0]).name

In [7]:
knn = 20

In [22]:
with open(INPUTS_CSV, "w") as fp:
    for name in INPUT_FAAS:
        for split_faa in sorted(SPLITS_DIR.glob(f"IMGVR5_UViG.{name}.filtered.split*.faa")):
            idx = split_faa.stem.rsplit("split", 1)[-1]
            outdir = f"CheckAMG_denovo_v1.1_MetaVR{name}.split{idx}"
            row = [split_faa.name, TRAIN_INDEX, TRAIN_LABELS, CKPT, outdir, knn]
            fp.write(",".join(map(str, row)) + "\n")

In [23]:
! cat {INPUTS_CSV}

IMGVR5_UViG.soil.filtered.split01.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split01,20
IMGVR5_UViG.soil.filtered.split02.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split02,20
IMGVR5_UViG.soil.filtered.split03.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split03,20
IMGVR5_UViG.soil.filtered.split04.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split04,20
IMGVR5_UViG.soil.filtered.split05.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split05,20
IMGVR5_UViG.soil.filtered.split06.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split06,20
IMGVR5_UViG.soil.filtered.split07.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split07,20
IMGVR5_UViG.soil.filtered.split08.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split08,20
IMGVR5_UViG.soil.filtered.split09.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split09,20
IMGVR5_UViG.soil.filtered.split10.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split10,20
IMGVR5_UViG.soil.filtered.split11.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split11,20
IMGVR5_UViG.soil.filtered.split12.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split12,20
IMGVR5_UViG.soil.filtered.split13.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split13,20
IMGVR5_UViG.soil.filtered.split14.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split14,20
IMGVR5_UViG.soil.filtered.split15.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split15,20
IMGVR5_UViG.soil.filtered.split16.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRsoil.split16,20
IMGVR5_UViG.gut.filtered.split01.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split01,20
IMGVR5_UViG.gut.filtered.split02.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split02,20
IMGVR5_UViG.gut.filtered.split03.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split03,20
IMGVR5_UViG.gut.filtered.split04.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split04,20
IMGVR5_UViG.gut.filtered.split05.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split05,20
IMGVR5_UViG.gut.filtered.split06.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split06,20
IMGVR5_UViG.gut.filtered.split07.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split07,20
IMGVR5_UViG.gut.filtered.split08.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split08,20
IMGVR5_UViG.gut.filtered.split09.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split09,20
IMGVR5_UViG.gut.filtered.split10.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split10,20
IMGVR5_UViG.gut.filtered.split11.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split11,20
IMGVR5_UViG.gut.filtered.split12.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split12,20
IMGVR5_UViG.gut.filtered.split13.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split13,20
IMGVR5_UViG.gut.filtered.split14.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split14,20
IMGVR5_UViG.gut.filtered.split15.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split15,20
IMGVR5_UViG.gut.filtered.split16.faa,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss,checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5,checkAMG-PST_TL-P__large_5.20260714.ckpt,CheckAMG_denovo_v1.1_MetaVRgut.split16,20

## Execute jobs

After transfering the `checkamg_denovo` job files, the query protein FASTAs, the training data index/labels, and the CheckAMG-PST model checkpoint, the CheckAMG de-novo pipeline can be run. This requires a conda environment for CheckAMG (packed into a tarball with `conda-pack`) that was set up for GPU compatibility (PST installed with CUDA libraries and faiss-gpu, see [github.com/AnantharamanLab/CheckAMG](https://github.com/AnantharamanLab/CheckAMG) and [github.com/AnantharamanLab/protein_set_transformer](https://github.com/AnantharamanLab/protein_set_transformer#manually-setup-pytorch) for instructions). The training logs were deposited to `./logs/checkamg_denovo/`.

## Combine results from each CheckAMG de-novo run

Since `checkamg aggregate` expects a pair of directories, one containing `checkamg annotate` and the other containing `checkamg denovo` results, we make a single folder per dataset (soil, human gut) that holds the merged results from all of that dataset's splits.

Each combined folder contains:

* `combined_proteins.filtered.faa` (all split protein FASTAs concatenated)
* `combined_proteins.filtered.graphfmt.h5` (combined ESM2 graph-format embeddings)
* `combined_proteins.filtered.PST-EMBED.h5` (combined PST embeddings)
* `predictions.tsv` (all split predictions, single header)
* `contig_to_genome.tsv` (all split contig-to-genome maps, single header)

Every file type is combined in numeric split order (`split01`, `split02`, ...), so proteins occupy the same row order across the FASTA, both `.h5` files, and the predictions table. The `.h5` files are PyTables arrays. For `graphfmt.h5` the per-protein `data` and `strand` arrays are concatenated, `sizes` is concatenated, `genome_label` is re-indexed across splits, and the CSR `ptr` is offset by the running protein count so it stays monotonic. For `PST-EMBED.h5` the `ctx_ptn` embedding matrix is concatenated.

In [8]:
DENOVO_RUNS_DIR = MAIN_DIR / "denovo_runs"
DENOVO_RUNS_DIR.mkdir(exist_ok=True)
DENOVO_TAR_PATTERN = "CheckAMG_denovo_v1.1_MetaVR*.split*.tar.gz"

In [9]:
import subprocess

files = list(DENOVO_RUNS_DIR.glob(DENOVO_TAR_PATTERN))
processes = []

for f in files:
    print(f"Extracting {f}")
    p = subprocess.Popen([
        "tar",
        "--use-compress-program=pigz -d -p 16",
        "-xf", str(f),
        "-C", str(DENOVO_RUNS_DIR)
    ])
    processes.append((f, p))

for f, p in processes:
    ret = p.wait()
    if ret != 0:
        print(f"FAILED: {f}")
    else:
        print(f"DONE: {f}")

Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split07.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split07.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split12.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split16.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split11.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split02.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split15.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split08.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split04.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split06.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split06.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split15.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split12.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split03.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split14.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split13.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split09.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split02.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split05.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split09.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split10.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split13.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split04.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split16.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split01.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split11.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split14.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split03.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split08.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split05.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split10.tar.gz
Extracting /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split01.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split07.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split07.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split12.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split16.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split11.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split02.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split15.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split08.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split04.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split06.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split06.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split15.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split12.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split03.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split14.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split13.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split09.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split02.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split05.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split09.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split10.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split13.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split04.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split16.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split01.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split11.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split14.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split03.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split08.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split05.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split10.tar.gz
DONE: /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split01.tar.gz

In [10]:
import re
import shutil
import tables

DENOVO_DIR_SOIL_COMBINED = MAIN_DIR / "CheckAMG_denovo_v1.1_MetaVRsoil"
DENOVO_DIR_GUT_COMBINED = MAIN_DIR / "CheckAMG_denovo_v1.1_MetaVRgut"

FAA_NAME = "combined_proteins.filtered.faa"
GRAPHFMT_NAME = "combined_proteins.filtered.graphfmt.h5"
PST_EMBED_NAME = "combined_proteins.filtered.PST-EMBED.h5"
PREDICTIONS_NAME = "predictions.tsv"
CONTIG_TO_GENOME_NAME = "contig_to_genome.tsv"

def ordered_split_dirs(dataset: str) -> list[Path]:
    pattern = f"CheckAMG_denovo_v1.1_MetaVR{dataset}.split*"
    dirs = [d for d in DENOVO_RUNS_DIR.glob(pattern) if d.is_dir()]
    return sorted(dirs, key=lambda d: int(re.search(r"split(\d+)$", d.name).group(1)))

In [11]:
import numpy as np

H5_CHUNK = 50_000

def combine_faa(split_dirs: list[Path], out_path: Path) -> None:
    with open(out_path, "wb") as out:
        for d in split_dirs:
            with open(d / FAA_NAME, "rb") as fh:
                shutil.copyfileobj(fh, out)

def combine_tsv(split_dirs: list[Path], name: str, out_path: Path) -> None:
    # infer_schema_length=0 reads every column as string, preserving exact formatting
    pl.concat(
        [pl.read_csv(d / name, separator="\t", infer_schema_length=0) for d in split_dirs]
    ).write_csv(out_path, separator="\t")

def _append_in_chunks(dst, src) -> None:
    for start in range(0, src.shape[0], H5_CHUNK):
        dst.append(src[start:start + H5_CHUNK])

def combine_graphfmt(split_dirs: list[Path], out_path: Path) -> None:
    srcs = [tables.open_file(str(d / GRAPHFMT_NAME), "r") for d in split_dirs]
    try:
        ref = srcs[0].root
        with tables.open_file(str(out_path), "w") as out:
            data = out.create_earray(
                out.root, "data", atom=tables.Atom.from_dtype(ref.data.dtype),
                shape=(0, ref.data.shape[1]), filters=ref.data.filters,
            )
            strand = out.create_earray(
                out.root, "strand", atom=tables.Atom.from_dtype(ref.strand.dtype),
                shape=(0,), filters=ref.strand.filters,
            )
            comb_ptr = [0]
            comb_sizes = []
            offset = 0
            for f in srcs:
                _append_in_chunks(data, f.root.data)
                _append_in_chunks(strand, f.root.strand)
                ptr = f.root.ptr[:]
                comb_ptr.extend((ptr[1:] + offset).tolist())
                comb_sizes.append(f.root.sizes[:])
                offset += int(ptr[-1])
            comb_sizes = np.concatenate(comb_sizes)
            n_genomes = comb_sizes.shape[0]
            out.create_carray(out.root, "ptr", obj=np.asarray(comb_ptr, dtype=ref.ptr.dtype), filters=ref.ptr.filters)
            out.create_carray(out.root, "sizes", obj=comb_sizes.astype(ref.sizes.dtype), filters=ref.sizes.filters)
            out.create_carray(out.root, "genome_label", obj=np.arange(n_genomes, dtype=ref.genome_label.dtype), filters=ref.genome_label.filters)
    finally:
        for f in srcs:
            f.close()

def combine_pst_embed(split_dirs: list[Path], out_path: Path) -> None:
    with tables.open_file(str(split_dirs[0] / PST_EMBED_NAME), "r") as f0:
        atom = tables.Atom.from_dtype(f0.root.ctx_ptn.dtype)
        width = f0.root.ctx_ptn.shape[1]
        filters = f0.root.ctx_ptn.filters
    with tables.open_file(str(out_path), "w") as out:
        ctx = out.create_earray(out.root, "ctx_ptn", atom=atom, shape=(0, width), filters=filters)
        for d in split_dirs:
            with tables.open_file(str(d / PST_EMBED_NAME), "r") as f:
                _append_in_chunks(ctx, f.root.ctx_ptn)

def combine_denovo_splits(dataset: str, combined_dir: Path) -> list[Path]:
    split_dirs = ordered_split_dirs(dataset)
    if not split_dirs:
        raise FileNotFoundError(f"No extracted split directories found for dataset {dataset!r}")
    combined_dir.mkdir(exist_ok=True)
    print(f"[{dataset}] combining {len(split_dirs)} splits in order: {[d.name for d in split_dirs]}")
    combine_faa(split_dirs, combined_dir / FAA_NAME)
    combine_graphfmt(split_dirs, combined_dir / GRAPHFMT_NAME)
    combine_pst_embed(split_dirs, combined_dir / PST_EMBED_NAME)
    combine_tsv(split_dirs, PREDICTIONS_NAME, combined_dir / PREDICTIONS_NAME)
    combine_tsv(split_dirs, CONTIG_TO_GENOME_NAME, combined_dir / CONTIG_TO_GENOME_NAME)
    print(f"[{dataset}] wrote combined outputs to {combined_dir}")
    return split_dirs

In [12]:
combine_denovo_splits("soil", DENOVO_DIR_SOIL_COMBINED)

[soil] combining 16 splits in order: ['CheckAMG_denovo_v1.1_MetaVRsoil.split01', 'CheckAMG_denovo_v1.1_MetaVRsoil.split02', 'CheckAMG_denovo_v1.1_MetaVRsoil.split03', 'CheckAMG_denovo_v1.1_MetaVRsoil.split04', 'CheckAMG_denovo_v1.1_MetaVRsoil.split05', 'CheckAMG_denovo_v1.1_MetaVRsoil.split06', 'CheckAMG_denovo_v1.1_MetaVRsoil.split07', 'CheckAMG_denovo_v1.1_MetaVRsoil.split08', 'CheckAMG_denovo_v1.1_MetaVRsoil.split09', 'CheckAMG_denovo_v1.1_MetaVRsoil.split10', 'CheckAMG_denovo_v1.1_MetaVRsoil.split11', 'CheckAMG_denovo_v1.1_MetaVRsoil.split12', 'CheckAMG_denovo_v1.1_MetaVRsoil.split13', 'CheckAMG_denovo_v1.1_MetaVRsoil.split14', 'CheckAMG_denovo_v1.1_MetaVRsoil.split15', 'CheckAMG_denovo_v1.1_MetaVRsoil.split16']
[soil] wrote combined outputs to /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_denovo_v1.1_MetaVRsoil

[PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split01'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split02'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split03'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split04'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split05'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split06'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split07'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split08'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split09'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split10'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split11'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split12'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split13'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split14'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split15'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRsoil.split16')]

In [13]:
! mkdir -p {DENOVO_DIR_SOIL_COMBINED / "snakemake"}
! rm {DENOVO_DIR_SOIL_COMBINED / "snakemake" / "run_inference.done"}
! touch {DENOVO_DIR_SOIL_COMBINED / "snakemake" / "filter_prots.done"}
! touch {DENOVO_DIR_SOIL_COMBINED / "snakemake" / "compute_query_esm2.done"}
! touch {DENOVO_DIR_SOIL_COMBINED / "snakemake" / "compute_query_pst.done"}

rm: cannot remove '/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_denovo_v1.1_MetaVRsoil/snakemake/run_inference.done': No such file or directory

    checkamg de-novo \
        --query-proteins /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/IMGVR5_UViG.soil.filtered.faa \
        --train-index-file /storage2/scratch/kosmopoulos/software/CheckAMG/notebooks/CheckAMG_denovo_db_v1.1_20260714/checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss \
        --train-labels-file /storage2/scratch/kosmopoulos/software/CheckAMG/notebooks/CheckAMG_denovo_db_v1.1_20260714/checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5 \
        --model-ckpt /storage2/scratch/kosmopoulos/software/CheckAMG/notebooks/CheckAMG_denovo_db_v1.1_20260714/checkAMG-PST_TL-P__large_5.20260714.ckpt \
        --output /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_denovo_v1.1_MetaVRsoil/ \
        --esm2-ckpt-dir /storage2/scratch/kosmopoulos/projects/checkAMG/pst/training/checkpoints/ \
        --knn 20 \
        -a cpu \
        --devices 200 \
        --mem 1000

In [14]:
combine_denovo_splits("gut", DENOVO_DIR_GUT_COMBINED)

[gut] combining 16 splits in order: ['CheckAMG_denovo_v1.1_MetaVRgut.split01', 'CheckAMG_denovo_v1.1_MetaVRgut.split02', 'CheckAMG_denovo_v1.1_MetaVRgut.split03', 'CheckAMG_denovo_v1.1_MetaVRgut.split04', 'CheckAMG_denovo_v1.1_MetaVRgut.split05', 'CheckAMG_denovo_v1.1_MetaVRgut.split06', 'CheckAMG_denovo_v1.1_MetaVRgut.split07', 'CheckAMG_denovo_v1.1_MetaVRgut.split08', 'CheckAMG_denovo_v1.1_MetaVRgut.split09', 'CheckAMG_denovo_v1.1_MetaVRgut.split10', 'CheckAMG_denovo_v1.1_MetaVRgut.split11', 'CheckAMG_denovo_v1.1_MetaVRgut.split12', 'CheckAMG_denovo_v1.1_MetaVRgut.split13', 'CheckAMG_denovo_v1.1_MetaVRgut.split14', 'CheckAMG_denovo_v1.1_MetaVRgut.split15', 'CheckAMG_denovo_v1.1_MetaVRgut.split16']

[gut] wrote combined outputs to /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_denovo_v1.1_MetaVRgut

[PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split01'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split02'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split03'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split04'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split05'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split06'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split07'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split08'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split09'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split10'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split11'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split12'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split13'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split14'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split15'),
 PosixPath('/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/denovo_runs/CheckAMG_denovo_v1.1_MetaVRgut.split16')]

In [15]:
! mkdir -p {DENOVO_DIR_GUT_COMBINED / "snakemake"}
! rm {DENOVO_DIR_GUT_COMBINED / "snakemake" / "run_inference.done"}
! touch {DENOVO_DIR_GUT_COMBINED / "snakemake" / "filter_prots.done"}
! touch {DENOVO_DIR_GUT_COMBINED / "snakemake" / "compute_query_esm2.done"}
! touch {DENOVO_DIR_GUT_COMBINED / "snakemake" / "compute_query_pst.done"}

rm: cannot remove '/storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_denovo_v1.1_MetaVRgut/snakemake/run_inference.done': No such file or directory

    checkamg de-novo \
        --query-proteins /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/IMGVR5_UViG.gut.filtered.faa \
        --train-index-file /storage2/scratch/kosmopoulos/software/CheckAMG/notebooks/CheckAMG_denovo_db_v1.1_20260714/checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.index.faiss \
        --train-labels-file /storage2/scratch/kosmopoulos/software/CheckAMG/notebooks/CheckAMG_denovo_db_v1.1_20260714/checkAMG-PST_TL-P__large_5.20260714.PST-EMBED.labels.h5 \
        --model-ckpt /storage2/scratch/kosmopoulos/software/CheckAMG/notebooks/CheckAMG_denovo_db_v1.1_20260714/checkAMG-PST_TL-P__large_5.20260714.ckpt \
        --output /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_denovo_v1.1_MetaVRgut \
        --esm2-ckpt-dir /storage2/scratch/kosmopoulos/projects/checkAMG/pst/training/checkpoints/ \
        --knn 20 \
        -a cpu \
        --devices 200 \
        --mem 1000

## Run CheckAMG aggregate

### MetaVR soil

    nohup checkamg aggregate \
        --annotate-dir /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_annotate_v1.1_MetaVRsoil \
        --denovo-dir /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_denovo_v1.1_MetaVRsoil \
        --output /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_aggregate_v1.1_MetaVRsoil \
        --save-to-parquet \
        --threads 100 \
        > ./logs/checkamg_aggregate/CheckAMG_aggregate_metavr_soil.log &

### MetaVR human gut

    nohup checkamg aggregate \
        --annotate-dir /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_annotate_v1.1_MetaVRgut \
        --denovo-dir /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_denovo_v1.1_MetaVRgut \
        --output /storage2/scratch/kosmopoulos/projects/checkAMG/applied_runs_for_manuscript/CheckAMG_aggregate_v1.1_MetaVRgut \
        --save-to-parquet \
        --threads 100 \
        > ./logs/checkamg_aggregate/CheckAMG_aggregate_metavr_gut.log &

## Load the aggregated results

Separatley load and assign confidence bin levels, in case the cutoffs changed.

In [16]:
import json
pst_thresholds = json.load(open("../CheckAMG/files/pst_thresholds.json"))
pst_thresholds

{'AVG-like': {'very_high': 0.89, 'high': 0.201, 'medium': 0.034},
 'Viral': {'very_high': 0.622, 'high': 0.051, 'medium': 0.001},
 'AVG': {'very_high': 0.956, 'high': 0.512, 'medium': 0.096}}

In [17]:
AGGREGATE_DIR_SOIL = MAIN_DIR / "CheckAMG_aggregate_v1.1_MetaVRsoil"
AGGREGATE_DIR_GUT = MAIN_DIR / "CheckAMG_aggregate_v1.1_MetaVRgut"

In [18]:
def pst_confidence_expr(prob_col, cutoffs):
    # explicit null guard so missing de-novo probabilities stay null instead of falling through to "low"
    return (
        pl.when(pl.col(prob_col).is_null()).then(pl.lit(None))
        .when(pl.col(prob_col) >= cutoffs["very_high"]).then(pl.lit("very high"))
        .when(pl.col(prob_col) >= cutoffs["high"]).then(pl.lit("high"))
        .when(pl.col(prob_col) >= cutoffs["medium"]).then(pl.lit("medium"))
        .otherwise(pl.lit("low"))
    )

agg_res_detailed_soil = (
    pl.read_parquet(AGGREGATE_DIR_SOIL / "aggregated_results_detailed.parquet")
    .with_columns([
        pst_confidence_expr("Viral Probability (de-novo)", pst_thresholds["Viral"]).alias("Viral Confidence Level (de-novo)"),
        pst_confidence_expr("AVG-like Probability (de-novo)", pst_thresholds["AVG-like"]).alias("AVG-like Confidence Level (de-novo)"),
        pst_confidence_expr("Final AVG Probability (de-novo)", pst_thresholds["AVG"]).alias("Final AVG Confidence Level (de-novo)"),
    ])
)
agg_res_detailed_soil

shape: (16_501_794, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Protein   ┆ Contig    ┆ Genome    ┆ Viral Pro ┆ … ┆ AVG-like  ┆ AVG-like  ┆ Final AVG ┆ Final    │
│ ---       ┆ ---       ┆ ---       ┆ bability  ┆   ┆ Probabili ┆ Confidenc ┆ Probabili ┆ AVG Conf │
│ str       ┆ str       ┆ str       ┆ (annotate ┆   ┆ ty        ┆ e Level   ┆ ty        ┆ idence   │
│           ┆           ┆           ┆ )         ┆   ┆ (de-novo) ┆ (de-novo) ┆ (de-novo) ┆ Level    │
│           ┆           ┆           ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ (de-novo │
│           ┆           ┆           ┆ f32       ┆   ┆ f64       ┆ str       ┆ f64       ┆ )        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.965619  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_2088090 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 008_00000 ┆ 008_00000 ┆ 008_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|2088090 ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 008|P3_DR ┆ 008|P3_DR ┆ 008|P3_DR ┆           ┆   ┆           ┆           ┆           ┆          │
│ AFT_NODE_ ┆ AFT_NODE_ ┆ AFT_NODE_ ┆           ┆   ┆           ┆           ┆           ┆          │
│ 290175_le ┆ 290175_le ┆ 290175_le ┆           ┆   ┆           ┆           ┆           ┆          │
│ n_15711_c ┆ n_15711_c ┆ n_15711_c ┆           ┆   ┆           ┆           ┆           ┆          │
│ ov_24_196 ┆ ov_24_196 ┆ ov_24_196 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 932_1     ┆ 932       ┆ 932       ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.954897  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_2088090 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 008_00000 ┆ 008_00000 ┆ 008_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|2088090 ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 008|P3_DR ┆ 008|P3_DR ┆ 008|P3_DR ┆           ┆   ┆           ┆           ┆           ┆          │
│ AFT_NODE_ ┆ AFT_NODE_ ┆ AFT_NODE_ ┆           ┆   ┆           ┆           ┆           ┆          │
│ 290175_le ┆ 290175_le ┆ 290175_le ┆           ┆   ┆           ┆           ┆           ┆          │
│ n_15711_c ┆ n_15711_c ┆ n_15711_c ┆           ┆   ┆           ┆           ┆           ┆          │
│ ov_24_196 ┆ ov_24_196 ┆ ov_24_196 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 932_2     ┆ 932       ┆ 932       ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.969051  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_2088090 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 008_00000 ┆ 008_00000 ┆ 008_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|2088090 ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 008|P3_DR ┆ 008|P3_DR ┆ 008|P3_DR ┆           ┆   ┆           ┆           ┆           ┆          │
│ AFT_NODE_ ┆ AFT_NODE_ ┆ AFT_NODE_ ┆           ┆   ┆           ┆           ┆           ┆          │
│ 290175_le ┆ 290175_le ┆ 290175_le ┆           ┆   ┆           ┆           ┆           ┆          │
│ n_15711_c ┆ n_15711_c ┆ n_15711_c ┆           ┆   ┆           ┆           ┆           ┆          │
│ ov_24_196 ┆ ov_24_196 ┆ ov_24_196 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 932_3     ┆ 932       ┆ 932       ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.959374  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_2088090 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 008_00000 ┆ 008_00000 ┆ 008_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|2088090 ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 008|P3_DR ┆ 008|P3_DR ┆ 008|P3_DR ┆           ┆   ┆           ┆           ┆           ┆          │
│ AFT_NODE_ ┆ AFT_NODE_ ┆ AFT_NODE_ ┆           ┆   ┆           ┆           ┆           ┆          │
│ 290175_le ┆ 290175_le ┆ 290175_le ┆           ┆   ┆           ┆           ┆           ┆          │
│ n_15711_c ┆ n_15711_c ┆ n_15711_c ┆           ┆   ┆           ┆           ┆           ┆          │
│ ov_24_196 ┆ ov_24_196 ┆ ov_24_196 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 932_4     ┆ 932       ┆ 932       ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.985477  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_2088090 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 008_00000 ┆ 008_00000 ┆ 008_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|2088090 ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 008|P3_DR ┆ 008|P3_DR ┆ 008|P3_DR ┆           ┆   ┆           ┆           ┆           ┆          │
│ AFT_NODE_ ┆ AFT_NODE_ ┆ AFT_NODE_ ┆           ┆   ┆           ┆           ┆           ┆          │
│ 290175_le ┆ 290175_le ┆ 290175_le ┆           ┆   ┆           ┆           ┆           ┆          │
│ n_15711_c ┆ n_15711_c ┆ n_15711_c ┆           ┆   ┆           ┆           ┆           ┆          │
│ ov_24_196 ┆ ov_24_196 ┆ ov_24_196 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 932_5     ┆ 932       ┆ 932       ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.986737  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_8123603 ┆ G_8123603 ┆ G_8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 135_00000 ┆ 135_00000 ┆ 135_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|8123603 ┆ 1|8123603 ┆ 1|8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 135|81236 ┆ 135|81236 ┆ 135|81236 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 03135_88  ┆ 03135     ┆ 03135     ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.987233  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_8123603 ┆ G_8123603 ┆ G_8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 135_00000 ┆ 135_00000 ┆ 135_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|8123603 ┆ 1|8123603 ┆ 1|8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 135|81236 ┆ 135|81236 ┆ 135|81236 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 03135_89  ┆ 03135     ┆ 03135     ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.988478  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_8123603 ┆ G_8123603 ┆ G_8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 135_00000 ┆ 135_00000 ┆ 135_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|8123603 ┆ 1|8123603 ┆ 1|8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 135|81236 ┆ 135|81236 ┆ 135|81236 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 03135_90  ┆ 03135     ┆ 03135     ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.99194   ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_8123603 ┆ G_8123603 ┆ G_8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 135_00000 ┆ 135_00000 ┆ 135_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|8123603 ┆ 1|8123603 ┆ 1|8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 135|81236 ┆ 135|81236 ┆ 135|81236 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 03135_91  ┆ 03135     ┆ 03135     ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.992442  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_8123603 ┆ G_8123603 ┆ G_8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 135_00000 ┆ 135_00000 ┆ 135_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|8123603 ┆ 1|8123603 ┆ 1|8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 135|81236 ┆ 135|81236 ┆ 135|81236 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 03135_92  ┆ 03135     ┆ 03135     ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [19]:
agg_res_detailed_gut = (
    pl.read_parquet(AGGREGATE_DIR_GUT / "aggregated_results_detailed.parquet")
    .with_columns([
        pst_confidence_expr("Viral Probability (de-novo)", pst_thresholds["Viral"]).alias("Viral Confidence Level (de-novo)"),
        pst_confidence_expr("AVG-like Probability (de-novo)", pst_thresholds["AVG-like"]).alias("AVG-like Confidence Level (de-novo)"),
        pst_confidence_expr("Final AVG Probability (de-novo)", pst_thresholds["AVG"]).alias("Final AVG Confidence Level (de-novo)"),
    ])
)
agg_res_detailed_gut

shape: (6_874_011, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Protein   ┆ Contig    ┆ Genome    ┆ Viral Pro ┆ … ┆ AVG-like  ┆ AVG-like  ┆ Final AVG ┆ Final    │
│ ---       ┆ ---       ┆ ---       ┆ bability  ┆   ┆ Probabili ┆ Confidenc ┆ Probabili ┆ AVG Conf │
│ str       ┆ str       ┆ str       ┆ (annotate ┆   ┆ ty        ┆ e Level   ┆ ty        ┆ idence   │
│           ┆           ┆           ┆ )         ┆   ┆ (de-novo) ┆ (de-novo) ┆ (de-novo) ┆ Level    │
│           ┆           ┆           ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ (de-novo │
│           ┆           ┆           ┆ f32       ┆   ┆ f64       ┆ str       ┆ f64       ┆ )        │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.961994  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_2042536 ┆ G_2042536 ┆ G_2042536 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001_00000 ┆ 001_00000 ┆ 001_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|2042536 ┆ 1|2042536 ┆ 1|2042536 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001|Irish ┆ 001|Irish ┆ 001|Irish ┆           ┆   ┆           ┆           ┆           ┆          │
│ _EM03_con ┆ _EM03_con ┆ _EM03_con ┆           ┆   ┆           ┆           ┆           ┆          │
│ tig02274_ ┆ tig02274  ┆ tig02274  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.956285  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_2042536 ┆ G_2042536 ┆ G_2042536 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001_00000 ┆ 001_00000 ┆ 001_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|2042536 ┆ 1|2042536 ┆ 1|2042536 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001|Irish ┆ 001|Irish ┆ 001|Irish ┆           ┆   ┆           ┆           ┆           ┆          │
│ _EM03_con ┆ _EM03_con ┆ _EM03_con ┆           ┆   ┆           ┆           ┆           ┆          │
│ tig02274_ ┆ tig02274  ┆ tig02274  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.947419  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_2042536 ┆ G_2042536 ┆ G_2042536 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001_00000 ┆ 001_00000 ┆ 001_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|2042536 ┆ 1|2042536 ┆ 1|2042536 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001|Irish ┆ 001|Irish ┆ 001|Irish ┆           ┆   ┆           ┆           ┆           ┆          │
│ _EM03_con ┆ _EM03_con ┆ _EM03_con ┆           ┆   ┆           ┆           ┆           ┆          │
│ tig02274_ ┆ tig02274  ┆ tig02274  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.949114  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_2042536 ┆ G_2042536 ┆ G_2042536 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001_00000 ┆ 001_00000 ┆ 001_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|2042536 ┆ 1|2042536 ┆ 1|2042536 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001|Irish ┆ 001|Irish ┆ 001|Irish ┆           ┆   ┆           ┆           ┆           ┆          │
│ _EM03_con ┆ _EM03_con ┆ _EM03_con ┆           ┆   ┆           ┆           ┆           ┆          │
│ tig02274_ ┆ tig02274  ┆ tig02274  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.938472  ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_2042536 ┆ G_2042536 ┆ G_2042536 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001_00000 ┆ 001_00000 ┆ 001_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|2042536 ┆ 1|2042536 ┆ 1|2042536 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 001|Irish ┆ 001|Irish ┆ 001|Irish ┆           ┆   ┆           ┆           ┆           ┆          │
│ _EM03_con ┆ _EM03_con ┆ _EM03_con ┆           ┆   ┆           ┆           ┆           ┆          │
│ tig02274_ ┆ tig02274  ┆ tig02274  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.99515   ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ G_8123603 ┆ G_8123603 ┆ G_8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 117_00000 ┆ 117_00000 ┆ 117_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|8123603 ┆ 1|8123603 ┆ 1|8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 117|81236 ┆ 117|81236 ┆ 117|81236 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 03117_1   ┆ 03117     ┆ 03117     ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.99515   ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ G_8123603 ┆ G_8123603 ┆ G_8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 334_00000 ┆ 334_00000 ┆ 334_00000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1|8123603 ┆ 1|8123603 ┆ 1|8123603 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 334|81236 ┆ 334|81236 ┆ 334|81236 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 03334_1   ┆ 03334     ┆ 03334     ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ null      ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_3300000 ┆ G_3300000 ┆ G_3300000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 287_00005 ┆ 287_00005 ┆ 287_00005 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5|3300000 ┆ 5|3300000 ┆ 5|3300000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 287|EM272 ┆ 287|EM272 ┆ 287|EM272 ┆           ┆   ┆           ┆           ┆           ┆          │
│ _1050227_ ┆ _1050227  ┆ _1050227  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 16        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ null      ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_3300000 ┆ G_3300000 ┆ G_3300000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 287_00005 ┆ 287_00005 ┆ 287_00005 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5|3300000 ┆ 5|3300000 ┆ 5|3300000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 287|EM272 ┆ 287|EM272 ┆ 287|EM272 ┆           ┆   ┆           ┆           ┆           ┆          │
│ _1050227_ ┆ _1050227  ┆ _1050227  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 15        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ IMGVR_UVi ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ null      ┆ … ┆ 0.0       ┆ low       ┆ 0.0       ┆ low      │
│ G_3300000 ┆ G_3300000 ┆ G_3300000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 287_00005 ┆ 287_00005 ┆ 287_00005 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5|3300000 ┆ 5|3300000 ┆ 5|3300000 ┆           ┆   ┆           ┆           ┆           ┆          │
│ 287|EM272 ┆ 287|EM272 ┆ 287|EM272 ┆           ┆   ┆           ┆           ┆           ┆          │
│ _1050227_ ┆ _1050227  ┆ _1050227  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 17        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
agg_res_detailed_combined = pl.concat([
    agg_res_detailed_soil.with_columns(pl.lit("soil").alias("dataset")),
    agg_res_detailed_gut.with_columns(pl.lit("gut").alias("dataset"))
    ])
agg_res_detailed_combined

shape: (23_375_805, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ Protein    ┆ Contig    ┆ Genome    ┆ Viral Pro ┆ … ┆ AVG-like  ┆ Final AVG ┆ Final AVG ┆ dataset │
│ ---        ┆ ---       ┆ ---       ┆ bability  ┆   ┆ Confidenc ┆ Probabili ┆ Confidenc ┆ ---     │
│ str        ┆ str       ┆ str       ┆ (annotate ┆   ┆ e Level   ┆ ty        ┆ e Level   ┆ str     │
│            ┆           ┆           ┆ )         ┆   ┆ (de-novo) ┆ (de-novo) ┆ (de-novo) ┆         │
│            ┆           ┆           ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆         │
│            ┆           ┆           ┆ f32       ┆   ┆ str       ┆ f64       ┆ str       ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.965619  ┆ … ┆ low       ┆ 0.0       ┆ low       ┆ soil    │
│ _208809000 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8_000001|2 ┆ 008_00000 ┆ 008_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 088090008| ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ P3_DRAFT_N ┆ 008|P3_DR ┆ 008|P3_DR ┆           ┆   ┆           ┆           ┆           ┆         │
│ ODE_290175 ┆ AFT_NODE_ ┆ AFT_NODE_ ┆           ┆   ┆           ┆           ┆           ┆         │
│ _len_15711 ┆ 290175_le ┆ 290175_le ┆           ┆   ┆           ┆           ┆           ┆         │
│ _cov_24_19 ┆ n_15711_c ┆ n_15711_c ┆           ┆   ┆           ┆           ┆           ┆         │
│ 6932_1     ┆ ov_24_196 ┆ ov_24_196 ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 932       ┆ 932       ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.954897  ┆ … ┆ low       ┆ 0.0       ┆ low       ┆ soil    │
│ _208809000 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8_000001|2 ┆ 008_00000 ┆ 008_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 088090008| ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ P3_DRAFT_N ┆ 008|P3_DR ┆ 008|P3_DR ┆           ┆   ┆           ┆           ┆           ┆         │
│ ODE_290175 ┆ AFT_NODE_ ┆ AFT_NODE_ ┆           ┆   ┆           ┆           ┆           ┆         │
│ _len_15711 ┆ 290175_le ┆ 290175_le ┆           ┆   ┆           ┆           ┆           ┆         │
│ _cov_24_19 ┆ n_15711_c ┆ n_15711_c ┆           ┆   ┆           ┆           ┆           ┆         │
│ 6932_2     ┆ ov_24_196 ┆ ov_24_196 ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 932       ┆ 932       ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.969051  ┆ … ┆ low       ┆ 0.0       ┆ low       ┆ soil    │
│ _208809000 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8_000001|2 ┆ 008_00000 ┆ 008_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 088090008| ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ P3_DRAFT_N ┆ 008|P3_DR ┆ 008|P3_DR ┆           ┆   ┆           ┆           ┆           ┆         │
│ ODE_290175 ┆ AFT_NODE_ ┆ AFT_NODE_ ┆           ┆   ┆           ┆           ┆           ┆         │
│ _len_15711 ┆ 290175_le ┆ 290175_le ┆           ┆   ┆           ┆           ┆           ┆         │
│ _cov_24_19 ┆ n_15711_c ┆ n_15711_c ┆           ┆   ┆           ┆           ┆           ┆         │
│ 6932_3     ┆ ov_24_196 ┆ ov_24_196 ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 932       ┆ 932       ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.959374  ┆ … ┆ low       ┆ 0.0       ┆ low       ┆ soil    │
│ _208809000 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8_000001|2 ┆ 008_00000 ┆ 008_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 088090008| ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ P3_DRAFT_N ┆ 008|P3_DR ┆ 008|P3_DR ┆           ┆   ┆           ┆           ┆           ┆         │
│ ODE_290175 ┆ AFT_NODE_ ┆ AFT_NODE_ ┆           ┆   ┆           ┆           ┆           ┆         │
│ _len_15711 ┆ 290175_le ┆ 290175_le ┆           ┆   ┆           ┆           ┆           ┆         │
│ _cov_24_19 ┆ n_15711_c ┆ n_15711_c ┆           ┆   ┆           ┆           ┆           ┆         │
│ 6932_4     ┆ ov_24_196 ┆ ov_24_196 ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 932       ┆ 932       ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.985477  ┆ … ┆ low       ┆ 0.0       ┆ low       ┆ soil    │
│ _208809000 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8_000001|2 ┆ 008_00000 ┆ 008_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 088090008| ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ P3_DRAFT_N ┆ 008|P3_DR ┆ 008|P3_DR ┆           ┆   ┆           ┆           ┆           ┆         │
│ ODE_290175 ┆ AFT_NODE_ ┆ AFT_NODE_ ┆           ┆   ┆           ┆           ┆           ┆         │
│ _len_15711 ┆ 290175_le ┆ 290175_le ┆           ┆   ┆           ┆           ┆           ┆         │
│ _cov_24_19 ┆ n_15711_c ┆ n_15711_c ┆           ┆   ┆           ┆           ┆           ┆         │
│ 6932_5     ┆ ov_24_196 ┆ ov_24_196 ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 932       ┆ 932       ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.99515   ┆ … ┆ null      ┆ null      ┆ null      ┆ gut     │
│ _812360311 ┆ G_8123603 ┆ G_8123603 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 7_000001|8 ┆ 117_00000 ┆ 117_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 123603117| ┆ 1|8123603 ┆ 1|8123603 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8123603117 ┆ 117|81236 ┆ 117|81236 ┆           ┆   ┆           ┆           ┆           ┆         │
│ _1         ┆ 03117     ┆ 03117     ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.99515   ┆ … ┆ null      ┆ null      ┆ null      ┆ gut     │
│ _812360333 ┆ G_8123603 ┆ G_8123603 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 4_000001|8 ┆ 334_00000 ┆ 334_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 123603334| ┆ 1|8123603 ┆ 1|8123603 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8123603334 ┆ 334|81236 ┆ 334|81236 ┆           ┆   ┆           ┆           ┆           ┆         │
│ _1         ┆ 03334     ┆ 03334     ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ null      ┆ … ┆ low       ┆ 0.0       ┆ low       ┆ gut     │
│ _330000028 ┆ G_3300000 ┆ G_3300000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 7_000055|3 ┆ 287_00005 ┆ 287_00005 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 300000287| ┆ 5|3300000 ┆ 5|3300000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ EM272_1050 ┆ 287|EM272 ┆ 287|EM272 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 227_16     ┆ _1050227  ┆ _1050227  ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ null      ┆ … ┆ low       ┆ 0.0       ┆ low       ┆ gut     │
│ _330000028 ┆ G_3300000 ┆ G_3300000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 7_000055|3 ┆ 287_00005 ┆ 287_00005 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 300000287| ┆ 5|3300000 ┆ 5|3300000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ EM272_1050 ┆ 287|EM272 ┆ 287|EM272 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 227_15     ┆ _1050227  ┆ _1050227  ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ null      ┆ … ┆ low       ┆ 0.0       ┆ low       ┆ gut     │
│ _330000028 ┆ G_3300000 ┆ G_3300000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 7_000055|3 ┆ 287_00005 ┆ 287_00005 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 300000287| ┆ 5|3300000 ┆ 5|3300000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ EM272_1050 ┆ 287|EM272 ┆ 287|EM272 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 227_17     ┆ _1050227  ┆ _1050227  ┆           ┆   ┆           ┆           ┆           ┆         │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

In [21]:
agg_res_detailed_combined.write_parquet(MAIN_DIR / "aggregated_results_combined.parquet")

In [22]:
agg_res_detailed_combined.filter((pl.col("Classification (annotate)") == "unclassified") & (pl.col("Final AVG Confidence Level (de-novo)").is_in(["high", "very high"])))

shape: (71_235, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ Protein    ┆ Contig    ┆ Genome    ┆ Viral Pro ┆ … ┆ AVG-like  ┆ Final AVG ┆ Final AVG ┆ dataset │
│ ---        ┆ ---       ┆ ---       ┆ bability  ┆   ┆ Confidenc ┆ Probabili ┆ Confidenc ┆ ---     │
│ str        ┆ str       ┆ str       ┆ (annotate ┆   ┆ e Level   ┆ ty        ┆ e Level   ┆ str     │
│            ┆           ┆           ┆ )         ┆   ┆ (de-novo) ┆ (de-novo) ┆ (de-novo) ┆         │
│            ┆           ┆           ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆         │
│            ┆           ┆           ┆ f32       ┆   ┆ str       ┆ f64       ┆ str       ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.99721   ┆ … ┆ very high ┆ 0.955     ┆ high      ┆ soil    │
│ _208809001 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 5_000001|2 ┆ 015_00000 ┆ 015_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 088090015| ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ GPICI_5395 ┆ 015|GPICI ┆ 015|GPICI ┆           ┆   ┆           ┆           ┆           ┆         │
│ 867_16     ┆ _5395867  ┆ _5395867  ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.998103  ┆ … ┆ high      ┆ 0.6442    ┆ high      ┆ soil    │
│ _208809001 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 5_000074|2 ┆ 015_00007 ┆ 015_00007 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 088090015| ┆ 4|2088090 ┆ 4|2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ GPICI_8944 ┆ 015|GPICI ┆ 015|GPICI ┆           ┆   ┆           ┆           ┆           ┆         │
│ 106_6      ┆ _8944106  ┆ _8944106  ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.993693  ┆ … ┆ high      ┆ 0.7429    ┆ high      ┆ soil    │
│ _208809001 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 5_000101|2 ┆ 015_00010 ┆ 015_00010 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 088090015| ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ GPICI_9056 ┆ 015|GPICI ┆ 015|GPICI ┆           ┆   ┆           ┆           ┆           ┆         │
│ 187_71     ┆ _9056187  ┆ _9056187  ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.521914  ┆ … ┆ very high ┆ 0.8974    ┆ high      ┆ soil    │
│ _208809001 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 5_000294|2 ┆ 015_00029 ┆ 015_00029 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 088090015| ┆ 4|2088090 ┆ 4|2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ GPICI_8678 ┆ 015|GPICI ┆ 015|GPICI ┆           ┆   ┆           ┆           ┆           ┆         │
│ 465_10     ┆ _8678465  ┆ _8678465  ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.845711  ┆ … ┆ high      ┆ 0.6038    ┆ high      ┆ soil    │
│ _208809001 ┆ G_2088090 ┆ G_2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 5_000371|2 ┆ 015_00037 ┆ 015_00037 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 088090015| ┆ 1|2088090 ┆ 1|2088090 ┆           ┆   ┆           ┆           ┆           ┆         │
│ GPICI_8802 ┆ 015|GPICI ┆ 015|GPICI ┆           ┆   ┆           ┆           ┆           ┆         │
│ 683_6      ┆ _8802683  ┆ _8802683  ┆           ┆   ┆           ┆           ┆           ┆         │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.998714  ┆ … ┆ high      ┆ 0.648     ┆ high      ┆ gut     │
│ _812086204 ┆ G_8120862 ┆ G_8120862 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 9_000001|8 ┆ 049_00000 ┆ 049_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 120862049| ┆ 1|8120862 ┆ 1|8120862 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8120862136 ┆ 049|81208 ┆ 049|81208 ┆           ┆   ┆           ┆           ┆           ┆         │
│ |6313-4224 ┆ 62136|631 ┆ 62136|631 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 4_26       ┆ 3-42244   ┆ 3-42244   ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.995395  ┆ … ┆ very high ┆ 1.0       ┆ very high ┆ gut     │
│ _812114364 ┆ G_8121143 ┆ G_8121143 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 1_000002|8 ┆ 641_00000 ┆ 641_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 121143641| ┆ 2|8121143 ┆ 2|8121143 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8121143641 ┆ 641|81211 ┆ 641|81211 ┆           ┆   ┆           ┆           ┆           ┆         │
│ |3750603-3 ┆ 43641|375 ┆ 43641|375 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 792852_22  ┆ 0603-3792 ┆ 0603-3792 ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 852       ┆ 852       ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.99502   ┆ … ┆ very high ┆ 1.0       ┆ very high ┆ gut     │
│ _812120627 ┆ G_8121206 ┆ G_8121206 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 5_000002|8 ┆ 275_00000 ┆ 275_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 121206275| ┆ 2|8121206 ┆ 2|8121206 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8121206275 ┆ 275|81212 ┆ 275|81212 ┆           ┆   ┆           ┆           ┆           ┆         │
│ |2595527-2 ┆ 06275|259 ┆ 06275|259 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 631438_29  ┆ 5527-2631 ┆ 5527-2631 ┆           ┆   ┆           ┆           ┆           ┆         │
│            ┆ 438       ┆ 438       ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.995266  ┆ … ┆ very high ┆ 1.0       ┆ very high ┆ gut     │
│ _812201459 ┆ G_8122014 ┆ G_8122014 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 5_000001|8 ┆ 595_00000 ┆ 595_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 122014595| ┆ 1|8122014 ┆ 1|8122014 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8122014634 ┆ 595|81220 ┆ 595|81220 ┆           ┆   ┆           ┆           ┆           ┆         │
│ _10        ┆ 14634     ┆ 14634     ┆           ┆   ┆           ┆           ┆           ┆         │
│ IMGVR_UViG ┆ IMGVR_UVi ┆ IMGVR_UVi ┆ 0.938652  ┆ … ┆ high      ┆ 0.8098    ┆ high      ┆ gut     │
│ _812201459 ┆ G_8122014 ┆ G_8122014 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 5_000001|8 ┆ 595_00000 ┆ 595_00000 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 122014595| ┆ 1|8122014 ┆ 1|8122014 ┆           ┆   ┆           ┆           ┆           ┆         │
│ 8122014634 ┆ 595|81220 ┆ 595|81220 ┆           ┆   ┆           ┆           ┆           ┆         │
│ _34        ┆ 14634     ┆ 14634     ┆           ┆   ┆           ┆           ┆           ┆         │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘